import { defineCards } from '@/content/defineCards';

export const fractionsAsDivisionCards = defineCards('fractions-as-division', ['fractions', 'division'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What does a fraction mean as division?',
    back: 'The fraction bar means “divided by.” a/b is the same as a ÷ b.',
    example: '3/4 = 3 ÷ 4',
    memoryHook: 'A fraction is a division problem waiting to be shared.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'If 3 pizzas are shared equally among 4 people, how much does each person get?',
    back: '3 ÷ 4 = 3/4 of a pizza.',
    explanation: 'Cut each pizza into 4 slices. Each person gets 1 slice from each pizza: 3 slices, or 3/4.',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'What happens when the number being shared is bigger than the number of people?',
    back: 'Each share is more than 1 whole. 7 ÷ 4 = 7/4 = 1 3/4.',
    after: [2],
  },
  {
    n: 4, type: 'visual', difficulty: 1,
    front: '3 pizzas are shared by 4 people. What fraction of a pizza does each person get?',
    back: '3/4 of a pizza (3 ÷ 4)',
    visual: { kind: 'fraction-circle', numerator: 3, denominator: 4 },
    answerVisual: { kind: 'fraction-circle', numerator: 3, denominator: 4, label: '3 ÷ 4 = 3/4' },
    after: [2],
  },
  {
    n: 5, type: 'solve', difficulty: 1,
    front: 'Write 1 ÷ 2 as a fraction.',
    back: '1/2',
    after: [1],
    explanation: 'The number being shared (1) goes on top, and the number of shares (2) goes on the bottom.',
  },
  {
    n: 6, type: 'solve', difficulty: 2,
    front: 'Write 2 ÷ 5 as a fraction.',
    back: '2/5',
    steps: ['The number being shared goes on top.', 'The number of shares goes on the bottom.'],
    after: [2],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: 'Write 9 ÷ 4 as a fraction and as a mixed number.',
    back: '9/4 = 2 1/4',
    steps: ['9 ÷ 4 = 9/4.', '9 divided by 4 is 2 with 1 left over.', '2 1/4'],
    after: [3],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'Write 4 ÷ 8 as a simplified fraction.',
    back: '1/2',
    steps: ['4 ÷ 8 = 4/8.', 'Divide top and bottom by 4: 1/2.'],
    after: [6],
  },
  {
    n: 9, type: 'solve', difficulty: 3,
    front: 'What division problem is 5/6, and what could it mean?',
    back: '5 ÷ 6. For example, 5 pizzas shared equally by 6 people means each person gets 5/6 of a pizza.',
    after: [6],
    explanation: '5 ÷ 6 and 5/6 are the same thing: 5 wholes cut into 6 equal shares.',
  },
  {
    n: 10, type: 'misconception', difficulty: 5,
    front: 'True or False: 3 ÷ 4 = 4/3.',
    back: 'False. 3 ÷ 4 = 3/4. The number being divided goes on top.',
    commonMistake: 'Flipping the numerator and denominator.',
    after: [2],
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'True or False: You can’t divide a smaller number by a bigger number.',
    back: 'False. 3 ÷ 4 = 3/4. The answer is just a fraction of a whole.',
    after: [2],
  },
  {
    n: 12, type: 'real-life', difficulty: 3,
    front: '5 friends share 2 sandwiches equally. How much sandwich does each friend get?',
    back: '2/5 of a sandwich',
    steps: ['Equal sharing → divide: 2 ÷ 5.', '2 ÷ 5 = 2/5.'],
    after: [6],
  },
  {
    n: 13, type: 'challenge', difficulty: 4,
    front: '6 kids share 9 granola bars equally. How much does each kid get? Write it as a mixed number.',
    back: '9/6 = 1 1/2 bars',
    steps: ['9 ÷ 6 = 9/6.', 'Simplify: 9/6 = 3/2.', '3/2 = 1 1/2.'],
    after: [7, 8],
  },
  {
    n: 14, type: 'challenge', difficulty: 4,
    front: 'Which is greater: 7 ÷ 8 or 8 ÷ 7? Explain without calculating decimals.',
    back: '8 ÷ 7 = 8/7 is greater. It is more than 1 whole, while 7/8 is less than 1.',
    after: [7],
    steps: ['7 ÷ 8 = 7/8, which is less than 1.', '8 ÷ 7 = 8/7, which is more than 1.', 'So 8 ÷ 7 is greater.'],
  },
]);
