import { defineCards } from '@/content/defineCards';

export const fractionsCompareCards = defineCards('fractions-compare', ['fractions', 'comparing'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'How do you compare two fractions?',
    back: 'Make the pieces comparable: use the same denominator, or the same numerator, or compare each to a benchmark like 1/2.',
    memoryHook: 'You can only compare slices of the same size.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'How do you compare fractions with the same denominator?',
    back: 'Compare the numerators. The greater numerator is the greater fraction.',
    example: '3/8 < 5/8',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'How do you compare fractions with the same numerator?',
    back: 'The one with the SMALLER denominator is greater, because its pieces are bigger.',
    example: '3/4 > 3/8',
    after: [1],
  },
  {
    n: 4, type: 'rule', difficulty: 3,
    front: 'How do you compare fractions with different numerators AND denominators?',
    back: 'Rename them with a common denominator (the LCM), then compare numerators. Or compare each to a benchmark such as 1/2.',
    example: '3/4 vs 5/6 → 9/12 vs 10/12 → 3/4 < 5/6',
    after: [2, 3],
  },
  {
    n: 5, type: 'visual', difficulty: 1,
    front: 'Which is greater, 3/4 or 3/8?',
    back: '3/4',
    explanation: 'Both have 3 pieces, but fourths are bigger than eighths, so the 3/4 bar is longer.',
    visual: { kind: 'fraction-strip-stack', showAlignment: true, strips: [{ numerator: 3, denominator: 4 }, { numerator: 3, denominator: 8 }] },
    after: [3],
  },
  {
    n: 6, type: 'visual', difficulty: 2,
    front: 'Which is greater, 2/3 or 3/4? Use the number line.',
    back: '3/4, because it is farther to the right.',
    explanation: 'In twelfths: 2/3 = 8/12 and 3/4 = 9/12.',
    visual: {
      kind: 'number-line', min: 0, max: 1, partsPerWhole: 12,
      marks: [
        { value: { numerator: 2, denominator: 3 }, label: '2/3', position: 'below' },
        { value: { numerator: 3, denominator: 4 }, label: '3/4', position: 'above' },
      ],
    },
    after: [2, 3],
  },
  {
    n: 7, type: 'solve', difficulty: 1,
    front: 'Compare: 2/5 ○ 4/5',
    back: '2/5 < 4/5',
    steps: ['Same denominator, so compare numerators: 2 < 4.'],
    after: [2],
  },
  {
    n: 8, type: 'solve', difficulty: 2,
    front: 'Compare: 5/6 ○ 5/8',
    back: '5/6 > 5/8',
    steps: ['Same numerator, so the smaller denominator is greater.', 'Sixths are bigger than eighths.'],
    after: [3],
  },
  {
    n: 9, type: 'solve', difficulty: 3,
    front: 'Compare: 3/4 ○ 5/6',
    back: '3/4 < 5/6',
    steps: ['LCM of 4 and 6 is 12.', '3/4 = 9/12 and 5/6 = 10/12.', '9 < 10'],
    after: [4],
  },
  {
    n: 10, type: 'solve', difficulty: 3,
    front: 'Compare 4/9 and 1/2 using the benchmark 1/2.',
    back: '4/9 < 1/2',
    steps: ['Half of 9 is 4 1/2, and 4 is less than that.', 'So 4/9 is less than half.'],
    after: [4],
  },
  {
    n: 11, type: 'solve', difficulty: 3,
    front: 'Compare: 7/12 ○ 5/8',
    back: '7/12 < 5/8',
    steps: ['LCM of 12 and 8 is 24.', '7/12 = 14/24 and 5/8 = 15/24.', '14 < 15'],
    after: [9],
  },
  {
    n: 12, type: 'misconception', difficulty: 5,
    front: 'Jo says 5/9 is greater than 5/7 because 9 is greater than 7. Is he right?',
    back: 'No. The numerators are equal, so the fraction with the smaller denominator is greater. 5/7 > 5/9.',
    commonMistake: 'Thinking a bigger denominator means a bigger fraction.',
    after: [3],
  },
  {
    n: 13, type: 'misconception', difficulty: 5,
    front: 'True or False: 3/10 is greater than 2/3 because 3 is greater than 2.',
    back: 'False. 3/10 is less than half, while 2/3 is more than half. 2/3 is greater.',
    explanation: 'You can’t compare numerators alone when the denominators differ.',
    after: [4],
  },
  {
    n: 14, type: 'real-life', difficulty: 3,
    front: 'Ana ran 3/4 mile. Ben ran 5/8 mile. Who ran farther?',
    back: 'Ana',
    steps: ['3/4 = 6/8.', '6/8 > 5/8.'],
    after: [9],
  },
  {
    n: 15, type: 'challenge', difficulty: 4,
    front: 'Which is greater, 7/8 or 9/10? Use how far each is from 1 whole.',
    back: '9/10',
    steps: ['7/8 is 1/8 short of 1. 9/10 is 1/10 short of 1.', '1/10 is smaller than 1/8, so 9/10 is closer to 1 — and greater.'],
    after: [9],
  },
  {
    n: 16, type: 'challenge', difficulty: 4,
    front: 'Name a fraction that is greater than 1/3 but less than 1/2.',
    back: 'For example 5/12 (since 4/12 < 5/12 < 6/12).',
    hint: 'Write both with the same denominator, like twelfths.',
    after: [9],
  },
]);
