import { defineCards } from '@/content/defineCards';

const MEMORY_HOOK = 'Same pizza, different number of slices.';

export const equivalentFractionCards = defineCards('fractions-equivalent', ['fractions', 'equivalent-fractions'], [
  // 1 · Understand the concept
  {
    n: 1,
    type: 'concept',
    difficulty: 1,
    front: 'What are equivalent fractions?',
    back: 'Fractions that look different but name the same amount.',
    rule: 'Multiply or divide the numerator and denominator by the same number.',
    example: '1/2 = 2/4 = 4/8',
    memoryHook: MEMORY_HOOK,
    commonMistake: 'Changing only the numerator or only the denominator.',
    prerequisites: ['fractions-parts-001'],
  },
  {
    n: 2,
    type: 'concept',
    difficulty: 2,
    front: 'Why does multiplying the top AND bottom by the same number keep a fraction’s value the same?',
    back: 'Because you are really multiplying by 1 — a fraction like 2/2 or 3/3. Multiplying by 1 never changes a number.',
    explanation: 'Cutting every slice in half doubles the slices you have AND the total slices. The amount of pizza doesn’t change.',
    example: '1/3 × 2/2 = 2/6',
    memoryHook: MEMORY_HOOK,
    after: [1],
  },

  // 2 · Learn the rule
  {
    n: 3,
    type: 'rule',
    difficulty: 2,
    front: 'How do you make an equivalent fraction?',
    back: 'Multiply (or divide) the numerator AND the denominator by the same number.',
    example: '3/4 → × 2 → 6/8      6/8 → ÷ 2 → 3/4',
    memoryHook: 'Whatever you do to the top, do to the bottom.',
    commonMistake: 'Multiplying only the denominator.',
    after: [1],
  },
  {
    n: 4,
    type: 'rule',
    difficulty: 2,
    front: 'How can you check whether two fractions are equivalent?',
    back: 'Simplify both to simplest form. If they match, they are equivalent.',
    explanation: 'Simplest form is like a fraction’s “home address” — equivalent fractions all live at the same one.',
    example: '4/6 → 2/3 and 6/9 → 2/3, so 4/6 = 6/9',
    after: [3],
  },

  // 3 · See a visual
  {
    n: 5,
    type: 'visual',
    difficulty: 1,
    front: 'What do these two pizzas prove?',
    back: '1/2 = 2/4',
    explanation: 'The same amount of pizza is shaded. The second pizza is just cut into more slices.',
    memoryHook: MEMORY_HOOK,
    visual: {
      kind: 'row',
      separator: 'vs',
      items: [
        { kind: 'fraction-circle', numerator: 1, denominator: 2, label: '1/2' },
        { kind: 'fraction-circle', numerator: 2, denominator: 4, label: '2/4' },
      ],
    },
  },
  {
    n: 6,
    type: 'visual',
    difficulty: 2,
    front: 'Look at the shaded parts of these chocolate bars. Which fractions are equal?',
    back: '1/3 = 2/6 = 4/12',
    explanation: 'All three shaded parts end at the same line, so they are the same length — the same amount.',
    visual: {
      kind: 'fraction-strip-stack',
      showAlignment: true,
      strips: [
        { numerator: 1, denominator: 3 },
        { numerator: 2, denominator: 6 },
        { numerator: 4, denominator: 12 },
      ],
    },
    after: [5],
  },
  {
    n: 7,
    type: 'visual',
    difficulty: 2,
    front: '3/4 is marked above the number line and 6/8 below it. What do you notice?',
    back: 'They land on the same point, so 3/4 = 6/8.',
    explanation: 'Equivalent fractions are the same distance from 0 — they are the same number with a different name.',
    visual: {
      kind: 'number-line',
      min: 0,
      max: 1,
      partsPerWhole: 8,
      marks: [
        { value: { numerator: 3, denominator: 4 }, label: '3/4', position: 'above' },
        { value: { numerator: 6, denominator: 8 }, label: '6/8', position: 'below' },
      ],
    },
    after: [5],
  },

  // 4 · Solve an easy example
  {
    n: 8,
    type: 'solve',
    difficulty: 2,
    front: '1/3 = ?/6',
    back: '1/3 = 2/6',
    hint: 'What do you multiply 3 by to get 6?',
    steps: ['What turns 3 into 6? × 2', 'Do the same to the top: 1 × 2 = 2', 'So 1/3 = 2/6'],
    answerVisual: { kind: 'fraction-strip-stack', showAlignment: true, strips: [{ numerator: 1, denominator: 3 }, { numerator: 2, denominator: 6 }] },
    after: [3],
  },
  {
    n: 9,
    type: 'solve',
    difficulty: 2,
    front: '1/2 = ?/10',
    back: '1/2 = 5/10',
    hint: 'What do you multiply 2 by to get 10?',
    steps: ['What turns 2 into 10? × 5', 'Do the same to the top: 1 × 5 = 5', 'So 1/2 = 5/10'],
    after: [3],
  },

  // 5 · Solve a normal problem
  {
    n: 10,
    type: 'solve',
    difficulty: 3,
    front: '3/5 = ?/20',
    back: '3/5 = 12/20',
    hint: 'Find the number that turns 5 into 20.',
    steps: ['What turns 5 into 20? × 4', 'Do the same to the top: 3 × 4 = 12', 'So 3/5 = 12/20'],
    after: [8, 9],
  },
  {
    n: 11,
    type: 'solve',
    difficulty: 3,
    front: '2/3 = 10/?',
    back: '2/3 = 10/15',
    hint: 'This time the numerator is given. What turns 2 into 10?',
    steps: ['What turns 2 into 10? × 5', 'Do the same to the bottom: 3 × 5 = 15', 'So 2/3 = 10/15'],
    after: [8],
  },
  {
    n: 12,
    type: 'solve',
    difficulty: 3,
    front: '8/12 = ?/3',
    back: '8/12 = 2/3',
    hint: 'The denominator got smaller, so divide.',
    steps: ['What turns 12 into 3? ÷ 4', 'Do the same to the top: 8 ÷ 4 = 2', 'So 8/12 = 2/3'],
    memoryHook: 'Dividing top and bottom = gluing small slices into bigger ones.',
    after: [8],
  },

  // 6 · Detect a common mistake
  {
    n: 13,
    type: 'misconception',
    difficulty: 5,
    front: 'True or False: To change 2/3 into sixths, multiply only the denominator by 2.',
    back: 'False. Multiply the numerator AND the denominator by 2: 2/3 = 4/6.',
    explanation: 'Multiplying only the bottom gives 2/6, which is just 1/3 — less than 2/3.',
    commonMistake: 'Changing the denominator but forgetting the numerator.',
    answerVisual: {
      kind: 'fraction-strip-stack',
      showAlignment: true,
      strips: [
        { numerator: 2, denominator: 3 },
        { numerator: 4, denominator: 6 },
        { numerator: 2, denominator: 6 },
      ],
    },
    after: [3],
  },
  {
    n: 14,
    type: 'misconception',
    difficulty: 5,
    front: 'Sam says 2/3 = 3/4 because he added 1 to the top and 1 to the bottom. Is Sam right?',
    back: 'No. Adding the same number to the top and bottom changes the amount. Only multiplying or dividing both keeps fractions equivalent.',
    explanation: 'Compare the bars: 3/4 is longer than 2/3.',
    commonMistake: 'Adding instead of multiplying to make equivalent fractions.',
    answerVisual: {
      kind: 'fraction-strip-stack',
      showAlignment: true,
      strips: [{ numerator: 2, denominator: 3 }, { numerator: 3, denominator: 4 }],
    },
    after: [3],
  },
  {
    n: 15,
    type: 'misconception',
    difficulty: 5,
    front: 'Explain why multiplying ONLY the denominator changes a fraction’s value. Use 1/2 as your example.',
    back: '1/2 would become 1/4. Doubling the denominator cuts the pizza into twice as many slices, so each slice is smaller — but you still only have 1 slice. You end up with less pizza.',
    memoryHook: 'More slices in the pizza = smaller slices.',
    answerVisual: {
      kind: 'row',
      separator: '≠',
      items: [
        { kind: 'fraction-circle', numerator: 1, denominator: 2, label: '1/2' },
        { kind: 'fraction-circle', numerator: 1, denominator: 4, label: '1/4' },
      ],
    },
    after: [2, 13],
  },

  // 7 · Solve a real-world problem
  {
    n: 16,
    type: 'real-life',
    difficulty: 3,
    front: 'Maya ate 2/8 of a pizza. Leo ate 1/4 of a pizza the same size. Who ate more?',
    back: 'Neither — they ate the same amount, because 1/4 = 2/8.',
    steps: ['Give both fractions the same denominator: 1/4 × 2/2 = 2/8', 'Compare: 2/8 and 2/8 are the same', 'They ate equal amounts'],
    answerVisual: {
      kind: 'row',
      separator: '=',
      items: [
        { kind: 'fraction-circle', numerator: 2, denominator: 8, label: 'Maya 2/8' },
        { kind: 'fraction-circle', numerator: 1, denominator: 4, label: 'Leo 1/4' },
      ],
    },
    after: [8],
  },
  {
    n: 17,
    type: 'real-life',
    difficulty: 3,
    front: 'A recipe needs 1/2 cup of milk, but you only have a 1/4-cup scoop. How many scoops do you need?',
    back: '2 scoops, because 1/2 = 2/4.',
    hint: 'How many fourths make one half?',
    answerVisual: {
      kind: 'fraction-strip-stack',
      showAlignment: true,
      strips: [{ numerator: 1, denominator: 2 }, { numerator: 2, denominator: 4 }],
    },
    after: [8],
  },
  {
    n: 18,
    type: 'real-life',
    difficulty: 2,
    front: 'You have 3 pizzas and cut each one in half. How many halves do you have? Write it as a fraction.',
    back: '6 halves, so 3 = 6/2.',
    explanation: 'A whole number is a fraction too: 3 = 3/1. Multiply top and bottom by 2 → 6/2.',
    after: [3],
  },

  // 8 · Solve a challenge problem
  {
    n: 19,
    type: 'challenge',
    difficulty: 4,
    front: 'Find two different fractions equivalent to 7/8.',
    back: 'For example: 14/16 and 21/24.',
    steps: ['Multiply top and bottom by 2: 7/8 = 14/16', 'Multiply top and bottom by 3: 7/8 = 21/24', 'Any number works, as long as top and bottom use the same one'],
    after: [10],
  },
  {
    n: 20,
    type: 'challenge',
    difficulty: 5,
    front: 'Which fraction is NOT equivalent to 3/4?\n6/8 · 9/12 · 12/15 · 15/20',
    back: '12/15',
    hint: 'For each one, find what the 3 was multiplied by. Was the 4 multiplied by the same number?',
    steps: [
      '6/8: 3 × 2 = 6 and 4 × 2 = 8 ✓',
      '9/12: 3 × 3 = 9 and 4 × 3 = 12 ✓',
      '12/15: 3 × 4 = 12 but 4 × 4 = 16, not 15 ✗ (12/15 = 4/5)',
      '15/20: 3 × 5 = 15 and 4 × 5 = 20 ✓',
    ],
    after: [10, 11],
  },
  {
    n: 21,
    type: 'challenge',
    difficulty: 4,
    front: '4/6 = 6/?',
    back: '4/6 = 6/9',
    hint: 'No whole number turns 4 into 6. Try simplifying 4/6 first.',
    steps: ['Simplify first: 4/6 ÷ 2/2 = 2/3', 'Now what turns 2 into 6? × 3', 'Do the same to the bottom: 3 × 3 = 9', 'So 4/6 = 2/3 = 6/9'],
    after: [11, 12],
  },
]);
