import { defineCards } from '@/content/defineCards';

export const fasLikeCards = defineCards('fas-like', ['fractions', 'addition', 'like-denominators'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What does it mean to add fractions with the same denominator?',
    back: 'You are joining slices that are the same size, so you just count the total number of slices.',
    memoryHook: 'Same-size slices: count them up.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'How do you add fractions with the same denominator?',
    back: 'Add the numerators. Keep the denominator.',
    example: '2/8 + 3/8 = 5/8',
    memoryHook: 'The denominator names the slice size, and it doesn’t change.',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'What do you do if the sum is an improper fraction?',
    back: 'Rename it as a mixed number, and simplify if you can.',
    example: '3/4 + 3/4 = 6/4 = 1 2/4 = 1 1/2',
    after: [2],
  },
  {
    n: 4, type: 'visual', difficulty: 1,
    front: 'These bars show 2/8 and 3/8 joined together. What is 2/8 + 3/8?',
    back: '5/8',
    explanation: '2 eighths + 3 eighths = 5 eighths.',
    visual: {
      kind: 'fraction-strip-stack',
      strips: [{ numerator: 2, denominator: 8 }, { numerator: 3, denominator: 8 }, { numerator: 5, denominator: 8 }],
    },
    after: [2],
  },
  {
    n: 5, type: 'solve', difficulty: 1,
    front: '1/5 + 2/5 = ?',
    back: '3/5',
    steps: ['1 + 2 = 3.', 'Keep the denominator 5.'],
    after: [2],
  },
  {
    n: 6, type: 'solve', difficulty: 2,
    front: '4/9 + 2/9 = ? (Simplify.)',
    back: '2/3',
    steps: ['4 + 2 = 6, so 6/9.', 'Divide top and bottom by 3: 2/3.'],
    after: [2],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: '5/6 + 4/6 = ? (Write it as a mixed number in simplest form.)',
    back: '1 1/2',
    steps: ['5 + 4 = 9, so 9/6.', '9 ÷ 6 = 1 R 3, so 1 3/6.', 'Simplify: 3/6 = 1/2 → 1 1/2.'],
    after: [3],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: '7/10 + 5/10 = ? (Mixed number, simplest form.)',
    back: '1 1/5',
    steps: ['7 + 5 = 12, so 12/10.', '12 ÷ 10 = 1 R 2, so 1 2/10.', 'Simplify: 2/10 = 1/5 → 1 1/5.'],
    after: [7],
  },
  {
    n: 9, type: 'solve', difficulty: 3,
    front: '1/12 + 5/12 + 3/12 = ?',
    back: '3/4',
    steps: ['1 + 5 + 3 = 9, so 9/12.', 'Simplify: ÷ 3 → 3/4.'],
    after: [6],
  },
  {
    n: 10, type: 'misconception', difficulty: 5,
    front: 'True or False: 1/4 + 2/4 = 3/8.',
    back: 'False. The slices are still fourths, so the sum is 3/4. Adding denominators makes the slices smaller, which doesn’t make sense.',
    commonMistake: 'Adding the denominators.',
    after: [2],
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'Sam says 3/5 + 4/5 = 7/10. How can you tell this is unreasonable?',
    back: '3/5 is already more than half, so adding 4/5 must be more than 1. 7/10 is less than 1. The right answer is 7/5 = 1 2/5.',
    after: [3],
  },
  {
    n: 12, type: 'real-life', difficulty: 3,
    front: 'Ana ate 2/8 of a pizza and Ben ate 3/8 of the same pizza. How much did they eat together?',
    back: '5/8 of the pizza',
    after: [5],
  },
  {
    n: 13, type: 'challenge', difficulty: 4,
    front: 'Tom walks 3/10 mile on Monday, 4/10 mile on Tuesday and 5/10 mile on Wednesday. How far does he walk in all?',
    back: '1 1/5 miles',
    steps: ['3 + 4 + 5 = 12, so 12/10.', '12/10 = 1 2/10 = 1 1/5.'],
    after: [8],
  },
  {
    n: 14, type: 'challenge', difficulty: 4,
    front: 'Find the missing numerator: 3/7 + ?/7 = 6/7.',
    back: '3',
    steps: ['Think: 3 + ? = 6.', '3 + 3 = 6 ✓'],
    after: [6],
  },
]);
