import { defineCards } from '@/content/defineCards';

export const fasUnlikeCards = defineCards('fas-unlike', ['fractions', 'addition', 'subtraction', 'unlike-denominators'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'Why can’t you simply add 1/2 + 1/3 by adding the tops and bottoms?',
    back: 'The slices are different sizes. You can only add slices that are the same size, so first rename both fractions with the same denominator.',
    memoryHook: 'Make the slices match before you count them.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'What are the steps to add or subtract fractions with unlike denominators?',
    back: '1) Find a common denominator (the LCM).\n2) Rename each fraction.\n3) Add or subtract the numerators; keep the denominator.\n4) Simplify.',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'Which common denominator should you use?',
    back: 'The least common multiple (LCM) of the denominators keeps the numbers small. Any common multiple works, but you may need to simplify more.',
    example: '1/4 + 1/6: LCM(4, 6) = 12',
    after: [2],
  },
  {
    n: 4, type: 'visual', difficulty: 2,
    front: 'Cut both bars into sixths. What is 1/2 + 1/3?',
    back: '5/6',
    explanation: '1/2 = 3/6 and 1/3 = 2/6, so 3/6 + 2/6 = 5/6.',
    visual: {
      kind: 'fraction-strip-stack',
      strips: [{ numerator: 1, denominator: 2 }, { numerator: 1, denominator: 3 }, { numerator: 5, denominator: 6 }],
    },
    after: [2],
  },
  {
    n: 5, type: 'solve', difficulty: 1,
    front: '1/2 + 1/4 = ?',
    back: '3/4',
    steps: ['1/2 = 2/4.', '2/4 + 1/4 = 3/4.'],
    after: [2],
  },
  {
    n: 6, type: 'solve', difficulty: 2,
    front: '1/3 + 1/6 = ?',
    back: '1/2',
    steps: ['1/3 = 2/6.', '2/6 + 1/6 = 3/6.', 'Simplify: 3/6 = 1/2.'],
    after: [5],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: '2/3 + 1/4 = ?',
    back: '11/12',
    steps: ['LCM of 3 and 4 is 12.', '2/3 = 8/12 and 1/4 = 3/12.', '8/12 + 3/12 = 11/12.'],
    after: [6],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: '5/6 − 1/4 = ?',
    back: '7/12',
    steps: ['LCM of 6 and 4 is 12.', '5/6 = 10/12 and 1/4 = 3/12.', '10/12 − 3/12 = 7/12.'],
    after: [7],
  },
  {
    n: 9, type: 'solve', difficulty: 3,
    front: '3/4 − 2/3 = ?',
    back: '1/12',
    steps: ['3/4 = 9/12 and 2/3 = 8/12.', '9/12 − 8/12 = 1/12.'],
    after: [7],
  },
  {
    n: 10, type: 'solve', difficulty: 3,
    front: '3/8 + 5/12 = ?',
    back: '19/24',
    steps: ['LCM of 8 and 12 is 24.', '3/8 = 9/24 and 5/12 = 10/24.', '9/24 + 10/24 = 19/24.'],
    after: [7],
  },
  {
    n: 11, type: 'solve', difficulty: 4,
    front: '7/10 + 4/15 = ?',
    back: '29/30',
    steps: ['LCM of 10 and 15 is 30.', '7/10 = 21/30 and 4/15 = 8/30.', '21/30 + 8/30 = 29/30.'],
    after: [10],
  },
  {
    n: 12, type: 'misconception', difficulty: 5,
    front: 'True or False: 1/2 + 1/3 = 2/5.',
    back: 'False. You can’t add numerators and denominators. 1/2 + 1/3 = 3/6 + 2/6 = 5/6.',
    explanation: '2/5 is less than 1/2, which can’t be right when you add something to 1/2.',
    after: [2],
  },
  {
    n: 13, type: 'misconception', difficulty: 5,
    front: 'True or False: You must use the LEAST common multiple as the common denominator.',
    back: 'False. Any common multiple works; the LCM just keeps the numbers smaller. Simplify at the end.',
    example: '1/4 + 1/6 with 24: 6/24 + 4/24 = 10/24 = 5/12',
    after: [3],
  },
  {
    n: 14, type: 'real-life', difficulty: 3,
    front: 'A recipe uses 3/4 cup of sugar and 1/6 cup of honey. How much sweetener is that in all?',
    back: '11/12 cup',
    steps: ['LCM of 4 and 6 is 12.', '3/4 = 9/12 and 1/6 = 2/12.', '9/12 + 2/12 = 11/12.'],
    after: [7],
  },
  {
    n: 15, type: 'challenge', difficulty: 4,
    front: 'A tank is 1/3 full of water and 1/4 full of juice. How full is it? How much of the tank is empty?',
    back: '7/12 is full, so 5/12 is empty.',
    steps: ['1/3 + 1/4 = 4/12 + 3/12 = 7/12.', 'Empty: 12/12 − 7/12 = 5/12.'],
    after: [10],
  },
  {
    n: 16, type: 'challenge', difficulty: 4,
    front: 'Find two fractions with different denominators that add to exactly 1.',
    back: 'For example 1/2 + 2/4 = 1, or 1/3 + 4/6 = 1.',
    hint: 'Start with a pair of equal fractions that add to 1, like 1/2 + 1/2, and rename one.',
    after: [9],
  },
]);
