import { defineCards } from '@/content/defineCards';

export const fdivUnitByWholeCards = defineCards('fdiv-unit-by-whole', ['fractions', 'division', 'unit-fractions'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What does 1/3 ÷ 2 mean?',
    back: 'Share one-third equally into 2 parts. Each part is smaller than 1/3.',
    memoryHook: 'Sharing a piece makes smaller pieces.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'How do you divide a unit fraction by a whole number?',
    back: 'Multiply the denominator by the whole number. The numerator stays 1.',
    example: '1/3 ÷ 2 = 1/(3 × 2) = 1/6',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'Why does that rule work?',
    back: 'Cutting each piece into 2 smaller pieces makes twice as many pieces in the whole, so each piece is 1/6 of the whole instead of 1/3.',
    after: [2],
  },
  {
    n: 4, type: 'visual', difficulty: 2,
    front: 'Half a bar is cut into 3 equal pieces. How big is each piece compared with the whole bar?',
    back: '1/6 of the whole bar (1/2 ÷ 3 = 1/6)',
    explanation: 'Three of those small pieces fill the half; six would fill the whole bar.',
    visual: { kind: 'fraction-strip-stack', strips: [{ numerator: 1, denominator: 2 }, { numerator: 1, denominator: 6 }] },
    after: [2],
  },
  {
    n: 5, type: 'solve', difficulty: 1,
    front: '1/2 ÷ 2 = ?',
    back: '1/4',
    steps: ['2 × 2 = 4 for the new denominator.'],
    after: [2],
  },
  {
    n: 6, type: 'solve', difficulty: 2,
    front: '1/3 ÷ 4 = ?',
    back: '1/12',
    steps: ['3 × 4 = 12.'],
    after: [5],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: '1/5 ÷ 3 = ?',
    back: '1/15',
    steps: ['5 × 3 = 15.', 'CHECK: 3 × 1/15 = 3/15 = 1/5 ✓'],
    after: [6],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: '1/8 ÷ 2 = ?',
    back: '1/16',
    after: [6],
    steps: ['8 × 2 = 16 for the new denominator.', 'CHECK: 2 × 1/16 = 2/16 = 1/8 ✓'],
  },
  {
    n: 9, type: 'solve', difficulty: 3,
    front: '1/4 ÷ 5 = ?',
    back: '1/20',
    steps: ['4 × 5 = 20.'],
    after: [6],
  },
  {
    n: 10, type: 'misconception', difficulty: 5,
    front: 'True or False: 1/3 ÷ 2 = 2/3.',
    back: 'False. 1/3 ÷ 2 = 1/6. Sharing a third can’t make it bigger than a third.',
    after: [2],
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'Max says 1/4 ÷ 2 = 1/2, because he divided the denominator 4 by 2. What’s wrong?',
    back: 'Dividing a fraction by 2 makes the pieces smaller, so the denominator should get bigger: 1/4 ÷ 2 = 1/8.',
    commonMistake: 'Dividing the denominator instead of multiplying.',
    after: [7],
  },
  {
    n: 12, type: 'real-life', difficulty: 3,
    front: '1/2 of a pizza is left. It is shared equally among 3 friends. What fraction of the whole pizza does each friend get?',
    back: '1/6 of the pizza',
    steps: ['1/2 ÷ 3 = 1/(2 × 3) = 1/6.'],
    after: [5],
  },
  {
    n: 13, type: 'real-life', difficulty: 3,
    front: '1/3 gallon of paint is split equally among 4 rooms. How much paint does each room get?',
    back: '1/12 gallon',
    after: [6],
  },
  {
    n: 14, type: 'challenge', difficulty: 4,
    front: '1/4 of a cake is left and 3 kids share it equally. One kid gives half of her share to the dog. What fraction of the whole cake does the dog get?',
    back: '1/24 of the cake',
    steps: ['Each kid: 1/4 ÷ 3 = 1/12.', 'Dog: half of 1/12 = 1/12 ÷ 2 = 1/24.'],
    after: [7],
  },
  {
    n: 15, type: 'challenge', difficulty: 4,
    front: 'Use multiplication to check that 1/6 ÷ 3 = 1/18.',
    back: '1/18 × 3 = 3/18 = 1/6 ✓',
    after: [7],
    steps: ['Multiply the answer by the divisor: 3 × 1/18 = 3/18.', '3/18 = 1/6, which is the number we started with.'],
  },
]);
