import { defineCards } from '@/content/defineCards';

export const fdivVisualCards = defineCards('fdiv-visual', ['fractions', 'division', 'visual-models'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'How can you picture fraction division?',
    back: 'Draw the amount being divided. Then either cut it into pieces of the divisor’s size and count how many fit, or share it equally and find the size of each share.',
    memoryHook: 'Divide a fraction by a fraction: how many fit? Divide a fraction by a whole: how big is each share?',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'Which question does each kind of fraction division ask?',
    back: 'Dividing by a fraction (whole ÷ 1/4) asks “how many of that size fit?”\nDividing by a whole number (1/4 ÷ 3) asks “how big is each share?”',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'How can you check a fraction division?',
    back: 'Multiply the answer by the divisor. You should get the number you started with.',
    example: '3 ÷ 1/4 = 12, and 12 × 1/4 = 3 ✓',
    after: [2],
  },
  {
    n: 4, type: 'visual', difficulty: 1,
    front: 'The bar shows 2 1/2 cut into halves. How many halves fit in 2 1/2?',
    back: '5 halves, so 2 1/2 ÷ 1/2 = 5.',
    visual: {
      kind: 'bar-model',
      total: '2 1/2',
      bars: [{ segments: Array.from({ length: 5 }, () => ({ label: '1/2', size: 1 })) }],
    },
    after: [2],
  },
  {
    n: 5, type: 'visual', difficulty: 2,
    front: 'One-fourth of a bar is cut into 3 equal pieces. How big is each piece compared with the whole bar?',
    back: '1/12 of the whole bar (1/4 ÷ 3 = 1/12)',
    visual: { kind: 'fraction-strip-stack', strips: [{ numerator: 1, denominator: 4 }, { numerator: 1, denominator: 12 }] },
    after: [2],
  },
  {
    n: 6, type: 'solve', difficulty: 1,
    front: 'How many halves fit in 3?',
    back: '6',
    steps: ['Each whole holds 2 halves.', '3 × 2 = 6.'],
    after: [2],
  },
  {
    n: 7, type: 'solve', difficulty: 2,
    front: 'How many 1/4s are in 2 1/4?',
    back: '9',
    steps: ['2 wholes = 8 fourths.', 'Plus 1 fourth = 9 fourths.'],
    after: [6],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'Draw and solve 1/3 ÷ 3.',
    back: '1/9',
    steps: ['Cut 1/3 into 3 equal pieces.', 'Three of them fill 1/3, so nine would fill the whole.', '1/3 ÷ 3 = 1/9.'],
    after: [5],
  },
  {
    n: 9, type: 'solve', difficulty: 3,
    front: 'Solve 4 ÷ 1/3 and check your answer.',
    back: '12. CHECK: 12 × 1/3 = 4 ✓',
    steps: ['Each whole holds 3 thirds.', '4 × 3 = 12.'],
    after: [6, 3],
  },
  {
    n: 10, type: 'solve', difficulty: 3,
    front: 'How many 1/4-cup scoops fit in 1 1/2 cups?',
    back: '6 scoops',
    steps: ['1 1/2 cups = 6 fourths (4 + 2).', 'So 6 scoops of 1/4 cup.'],
    after: [7],
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'True or False: 1/2 ÷ 3 = 3/2.',
    back: 'False. 1/2 ÷ 3 = 1/6. Sharing a half among 3 makes 3 small pieces, each a sixth of the whole.',
    commonMistake: 'Swapping numbers and getting a number greater than the half you started with.',
    after: [5],
  },
  {
    n: 12, type: 'misconception', difficulty: 5,
    front: 'Which picture matches 3 ÷ 1/4? (a) Cut 3 wholes into fourths and count the pieces. (b) Cut 1/4 into 3 equal pieces.',
    back: '(a). 3 ÷ 1/4 asks how many fourths fit in 3. Picture (b) is 1/4 ÷ 3.',
    after: [3],
  },
  {
    n: 13, type: 'real-life', difficulty: 3,
    front: 'A 1/2-pound block of cheese is cut into 4 equal pieces. How much does each piece weigh?',
    back: '1/8 pound',
    steps: ['1/2 ÷ 4 = 1/(2 × 4) = 1/8.'],
    after: [5],
  },
  {
    n: 14, type: 'real-life', difficulty: 3,
    front: 'A ribbon 3 meters long is cut into pieces that are 1/5 meter long. How many pieces?',
    back: '15 pieces',
    steps: ['3 ÷ 1/5 = 3 × 5 = 15.'],
    after: [9],
  },
  {
    n: 15, type: 'challenge', difficulty: 4,
    front: 'A bottle holds 2 1/2 liters. Cups hold 1/4 liter. How many cups can be filled?',
    back: '10 cups',
    steps: ['2 1/2 L = 10 quarters of a liter (2 × 4 + 2).', '10 ÷ 1 → 10 cups.'],
    after: [10],
  },
  {
    n: 16, type: 'challenge', difficulty: 4,
    front: 'Compare 1/2 ÷ 4 and 4 ÷ 1/2. Which is greater, and by how much?',
    back: '4 ÷ 1/2 = 8 is greater than 1/2 ÷ 4 = 1/8, by 7 7/8.',
    steps: ['1/2 ÷ 4 = 1/8.', '4 ÷ 1/2 = 8.', '8 − 1/8 = 7 7/8.'],
    after: [9],
  },
]);
