import { defineCards } from '@/content/defineCards';

export const fmulWholeCards = defineCards('fmul-whole', ['fractions', 'multiplication', 'whole-numbers'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What does 3 × 2/5 mean?',
    back: '3 groups of 2/5. It is repeated addition: 2/5 + 2/5 + 2/5 = 6/5.',
    memoryHook: 'Multiplying by a whole number counts the same slices again and again.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'How do you multiply a fraction by a whole number?',
    back: 'Multiply the numerator by the whole number. Keep the denominator. Simplify or rename as a mixed number.',
    example: '4 × 2/5 = 8/5 = 1 3/5',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'How do you find a fraction OF a whole number, like 3/4 of 20?',
    back: 'Divide the number by the denominator to find one part, then multiply by the numerator.',
    example: '3/4 of 20: 20 ÷ 4 = 5, then 3 × 5 = 15.',
    after: [2],
  },
  {
    n: 4, type: 'visual', difficulty: 1,
    front: 'Three copies of 1/4 are shaded. What is 3 × 1/4?',
    back: '3/4',
    visual: { kind: 'fraction-strip', numerator: 3, denominator: 4 },
    answerVisual: { kind: 'fraction-strip', numerator: 3, denominator: 4, label: '3 × 1/4 = 3/4' },
    after: [1],
  },
  {
    n: 5, type: 'solve', difficulty: 1,
    front: '2 × 1/3 = ?',
    back: '2/3',
    steps: ['1/3 + 1/3 = 2/3.'],
    after: [2],
  },
  {
    n: 6, type: 'solve', difficulty: 2,
    front: '4 × 2/5 = ? (Write a mixed number.)',
    back: '8/5 = 1 3/5',
    steps: ['4 × 2 = 8, so 8/5.', '8 ÷ 5 = 1 R 3, so 1 3/5.'],
    after: [2],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: '6 × 3/8 = ? (Simplest form.)',
    back: '9/4 = 2 1/4',
    steps: ['6 × 3 = 18, so 18/8.', 'Simplify: 18/8 = 9/4.', '9 ÷ 4 = 2 R 1 → 2 1/4.'],
    after: [6],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'What is 1/3 of 12?',
    back: '4',
    steps: ['12 ÷ 3 = 4.'],
    after: [3],
  },
  {
    n: 9, type: 'solve', difficulty: 3,
    front: 'What is 3/5 of 25?',
    back: '15',
    steps: ['25 ÷ 5 = 5 (one fifth).', '3 × 5 = 15.'],
    after: [3],
  },
  {
    n: 10, type: 'solve', difficulty: 4,
    front: 'What is 5/6 of 18?',
    back: '15',
    steps: ['18 ÷ 6 = 3 (one sixth).', '5 × 3 = 15.'],
    after: [9],
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'True or False: 4 × 2/5 = 8/20, because you multiply the denominator by 4 too.',
    back: 'False. The size of the slices (the denominator) doesn’t change. 4 × 2/5 = 8/5.',
    commonMistake: 'Multiplying the numerator and the denominator by the whole number.',
    after: [2],
  },
  {
    n: 12, type: 'misconception', difficulty: 5,
    front: 'True or False: 1/4 of 20 is 80.',
    back: 'False. 1/4 of 20 is 5. A part of a number is less than the number.',
    memoryHook: '“Of” a fraction less than 1 gives something smaller.',
    after: [3],
  },
  {
    n: 13, type: 'real-life', difficulty: 3,
    front: 'A recipe needs 3/4 cup of milk per batch. How much milk is needed for 5 batches?',
    back: '3 3/4 cups',
    steps: ['5 × 3/4 = 15/4.', '15 ÷ 4 = 3 R 3 → 3 3/4.'],
    after: [6],
  },
  {
    n: 14, type: 'real-life', difficulty: 3,
    front: 'There are 24 students and 5/8 of them wear glasses. How many wear glasses?',
    back: '15 students',
    steps: ['24 ÷ 8 = 3 students in each eighth.', '5 × 3 = 15.'],
    after: [9],
  },
  {
    n: 15, type: 'challenge', difficulty: 4,
    front: 'A rope is 18 m long. 2/3 of it is used for a swing and 1/2 of what is left for a hammock. How much rope is still unused?',
    back: '3 m',
    steps: ['Swing: 2/3 of 18 = 12 m.', 'Left: 18 − 12 = 6 m.', 'Hammock: 1/2 of 6 = 3 m.', 'Unused: 6 − 3 = 3 m.'],
    after: [10],
  },
  {
    n: 16, type: 'challenge', difficulty: 4,
    front: 'Which is greater: 3 × 5/6 or 2 × 7/6?',
    back: '3 × 5/6',
    steps: ['3 × 5/6 = 15/6.', '2 × 7/6 = 14/6.', '15/6 > 14/6.'],
    after: [7],
  },
]);
