import { defineCards } from '@/content/defineCards';

export const fmulFractionCards = defineCards('fmul-fraction', ['fractions', 'multiplication'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What does 1/2 × 1/3 mean?',
    back: 'Half of one-third. When you multiply two fractions, you take a part of a part.',
    memoryHook: '“Of” means multiply: 1/2 of 1/3.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'How do you multiply two fractions?',
    back: 'Multiply the numerators. Multiply the denominators. Simplify.',
    example: '2/3 × 3/4 = 6/12 = 1/2',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'Why is the product of two proper fractions smaller than both fractions?',
    back: 'You are taking a part of a part, which is always less than the part you started with.',
    after: [2],
  },
  {
    n: 4, type: 'visual', difficulty: 1,
    front: 'Yellow rows show 1/2 and blue columns show 3/4. The green overlap is 1/2 of 3/4. What is 1/2 × 3/4?',
    back: '3/8',
    explanation: 'The square has 8 cells, and 3 of them are green.',
    visual: { kind: 'fraction-area-model', rows: 2, cols: 4, shadeRows: 1, shadeCols: 3 },
    answerVisual: { kind: 'fraction-area-model', rows: 2, cols: 4, shadeRows: 1, shadeCols: 3, label: '1/2 × 3/4 = 3/8' },
    after: [2],
  },
  {
    n: 5, type: 'visual', difficulty: 2,
    front: 'Yellow rows show 2/3 and blue columns show 3/5. What is 2/3 × 3/5?',
    back: '6/15 = 2/5',
    explanation: '6 of the 15 cells overlap. Simplify 6/15 by dividing by 3.',
    visual: { kind: 'fraction-area-model', rows: 3, cols: 5, shadeRows: 2, shadeCols: 3 },
    answerVisual: { kind: 'fraction-area-model', rows: 3, cols: 5, shadeRows: 2, shadeCols: 3, label: '2/3 × 3/5 = 6/15 = 2/5' },
    after: [4],
  },
  {
    n: 6, type: 'solve', difficulty: 1,
    front: '1/2 × 1/4 = ?',
    back: '1/8',
    steps: ['1 × 1 = 1.', '2 × 4 = 8.'],
    after: [2],
  },
  {
    n: 7, type: 'solve', difficulty: 2,
    front: '2/3 × 3/4 = ?',
    back: '1/2',
    steps: ['2 × 3 = 6 and 3 × 4 = 12.', '6/12 = 1/2.'],
    after: [6],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: '3/5 × 5/6 = ?',
    back: '1/2',
    steps: ['3 × 5 = 15 and 5 × 6 = 30.', '15/30 = 1/2.'],
    after: [7],
  },
  {
    n: 9, type: 'solve', difficulty: 3,
    front: '2/5 × 3/4 = ?',
    back: '3/10',
    steps: ['2 × 3 = 6 and 5 × 4 = 20.', '6/20 = 3/10.'],
    after: [7],
  },
  {
    n: 10, type: 'solve', difficulty: 3,
    front: '5/6 × 3/10 = ?',
    back: '1/4',
    steps: ['5 × 3 = 15 and 6 × 10 = 60.', '15/60 = 1/4.'],
    after: [9],
  },
  {
    n: 11, type: 'solve', difficulty: 4,
    front: '5/8 × 4/15 = ?',
    back: '1/6',
    hint: 'Look for a number that divides one numerator and one denominator.',
    steps: ['5 and 15 share 5; 4 and 8 share 4.', '5/8 × 4/15 → (1/2) × (1/3) after dividing by 5 and 4.', '= 1/6. (Check: 20/120 = 1/6.)'],
    after: [10],
  },
  {
    n: 12, type: 'misconception', difficulty: 5,
    front: 'True or False: To multiply 1/2 × 1/3 you need a common denominator first.',
    back: 'False. You only need common denominators to ADD or SUBTRACT. To multiply, just multiply across: 1/2 × 1/3 = 1/6.',
    commonMistake: 'Using the rules for adding when multiplying.',
    after: [2],
  },
  {
    n: 13, type: 'misconception', difficulty: 5,
    front: 'True or False: 2/3 × 3/4 is greater than 3/4.',
    back: 'False. It is 1/2, which is less than 3/4. Multiplying by a fraction less than 1 makes a number smaller.',
    after: [3],
  },
  {
    n: 14, type: 'real-life', difficulty: 3,
    front: 'You have 3/4 of a pizza left and eat 1/3 of it. What fraction of the whole pizza did you eat?',
    back: '1/4 of the pizza',
    steps: ['1/3 × 3/4 = 3/12.', '3/12 = 1/4.'],
    after: [9],
  },
  {
    n: 15, type: 'real-life', difficulty: 3,
    front: 'A garden covers 2/3 of a yard. Tomatoes grow on 1/2 of the garden. What fraction of the yard has tomatoes?',
    back: '1/3 of the yard',
    steps: ['1/2 × 2/3 = 2/6.', '2/6 = 1/3.'],
    after: [7],
  },
  {
    n: 16, type: 'challenge', difficulty: 4,
    front: 'What is 3/4 of 2/5 of 100?',
    back: '30',
    steps: ['2/5 of 100: 100 ÷ 5 = 20, then 2 × 20 = 40.', '3/4 of 40: 40 ÷ 4 = 10, then 3 × 10 = 30.'],
    after: [9],
  },
  {
    n: 17, type: 'challenge', difficulty: 4,
    front: 'A path is 3/5 mile long. Ned walked 2/3 of it. How far did he walk?',
    back: '2/5 mile',
    steps: ['2/3 × 3/5 = 6/15.', '6/15 = 2/5.'],
    after: [8],
  },
]);
