import { defineCards } from '@/content/defineCards';

export const fractionPartsCards = defineCards('fractions-parts', ['fractions', 'numerator', 'denominator'], [
  {
    n: 1,
    type: 'concept',
    difficulty: 1,
    front: 'In the fraction 3/8, what do the 3 and the 8 mean?',
    back: 'The 8 (denominator) is how many equal slices the whole is cut into. The 3 (numerator) is how many of those slices we have.',
    memoryHook: 'Numerator = slices you picked. Denominator = equal slices in the whole pizza.',
    example: '3/8 → 3 slices out of 8 equal slices',
    visual: { kind: 'fraction-circle', numerator: 3, denominator: 8 },
  },
  {
    n: 2,
    type: 'rule',
    difficulty: 1,
    front: 'What must be true about the parts of a whole before we can name them with a fraction?',
    back: 'The parts must all be the same size — equal parts.',
    explanation: 'If one slice is huge and another is tiny, “1 out of 4 slices” doesn’t tell you how much you got.',
    commonMistake: 'Counting unequal pieces as if they were fourths or thirds.',
  },
  {
    n: 3,
    type: 'visual',
    difficulty: 1,
    front: 'What fraction of this pizza is shaded?',
    back: '5/6',
    explanation: 'The pizza is cut into 6 equal slices (denominator) and 5 are shaded (numerator).',
    visual: { kind: 'fraction-circle', numerator: 5, denominator: 6 },
    after: [1],
  },
  {
    n: 4,
    type: 'solve',
    difficulty: 2,
    front: 'What fraction of this chocolate bar is NOT shaded?',
    back: '2/5',
    hint: 'Count all the pieces first. That number goes on the bottom.',
    steps: ['The bar has 5 equal pieces → denominator is 5.', '3 are shaded, so 5 − 3 = 2 are not.', 'Answer: 2/5.'],
    visual: { kind: 'fraction-strip', numerator: 3, denominator: 5 },
    after: [3],
  },
  {
    n: 5,
    type: 'misconception',
    difficulty: 5,
    front: 'True or False: 1/8 is bigger than 1/4 because 8 is bigger than 4.',
    back: 'False. 1/4 is bigger.',
    explanation: 'A bigger denominator means the whole is cut into MORE pieces, so each piece is SMALLER.',
    commonMistake: 'Comparing denominators like whole numbers.',
    memoryHook: 'Share a pizza with 8 friends and you get a smaller slice than sharing with 4.',
    answerVisual: { kind: 'fraction-strip-stack', strips: [{ numerator: 1, denominator: 4 }, { numerator: 1, denominator: 8 }] },
    after: [1],
  },
  {
    n: 6,
    type: 'real-life',
    difficulty: 3,
    front: 'A chocolate bar has 12 equal squares. You eat 5. What fraction did you eat, and what fraction is left?',
    back: 'You ate 5/12. 7/12 is left.',
    steps: ['Whole bar = 12 equal squares → denominator 12.', 'Eaten: 5 squares → 5/12.', 'Left: 12 − 5 = 7 squares → 7/12.'],
    answerVisual: { kind: 'shaded-grid', rows: 2, cols: 6, shaded: 5, label: '5 of 12 eaten' },
    after: [4],
  },

  {
    n: 7,
    type: 'rule',
    difficulty: 2,
    front: 'How do you read a fraction aloud?',
    back: 'Say the numerator as a counting number, then the denominator as a part name (halves, thirds, fourths, fifths …).',
    example: '3/4 → “three fourths”     1/2 → “one half”',
    memoryHook: 'Top counts, bottom names.',
    after: [1],
  },
  {
    n: 8,
    type: 'solve',
    difficulty: 3,
    front: 'A pizza is cut into 12 equal slices. You eat 5 and your friend eats 4. What fraction did each of you eat, and what fraction is left?',
    back: 'You: 5/12. Friend: 4/12 (= 1/3). Left: 3/12 (= 1/4).',
    steps: ['Whole = 12 equal slices → denominator 12.', 'You: 5/12. Friend: 4/12.', 'Left: 12 − 5 − 4 = 3 slices → 3/12.'],
    after: [4],
  },
  {
    n: 9,
    type: 'misconception',
    difficulty: 5,
    front: 'A rectangle is split into 4 parts of different sizes, and 1 part is shaded. Jo says 1/4 is shaded. Is he right?',
    back: 'No. The parts must be EQUAL for the shaded part to be 1/4.',
    explanation: 'If one part is much bigger, shading it covers more than a quarter of the rectangle.',
    commonMistake: 'Counting parts without checking they are the same size.',
    after: [2],
  },
  {
    n: 10,
    type: 'real-life',
    difficulty: 3,
    front: 'A class has 20 students. 9 of them are wearing red. What fraction of the class is wearing red?',
    back: '9/20',
    steps: ['The whole is the whole class: 20 students → denominator 20.', '9 are wearing red → numerator 9.'],
    after: [4],
  },
  {
    n: 11,
    type: 'challenge',
    difficulty: 4,
    front: 'A bag has 10 marbles: 3 red, 2 blue and the rest green. What fraction of the marbles are green? What fraction are NOT green?',
    back: 'Green: 5/10 (= 1/2). Not green: 5/10 (= 1/2).',
    steps: ['Green = 10 − 3 − 2 = 5 marbles.', 'Green: 5/10. Not green: 3 + 2 = 5, so 5/10.'],
    after: [8],
  },
  {
    n: 12,
    type: 'challenge',
    difficulty: 4,
    front: 'A fraction has a denominator of 8. It is more than 1/2 but less than 1. What could its numerator be?',
    back: '5, 6 or 7 (so 5/8, 6/8 or 7/8).',
    hint: 'Half of 8 is 4. The numerator must be more than that but less than 8.',
    after: [8],
  },
]);
