import { defineCards } from '@/content/defineCards';

export const fractionsSimplifyingCards = defineCards('fractions-simplifying', ['fractions', 'simplifying'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What does it mean to simplify a fraction?',
    back: 'To write it with the smallest possible numerator and denominator without changing its value. This is called simplest form (or lowest terms).',
    example: '6/8 = 3/4',
    memoryHook: 'Same pizza, fewer (bigger) slices.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'How do you simplify a fraction?',
    back: 'Divide the numerator and denominator by a common factor. Repeat until they share no common factor except 1 — or divide by the GCF once.',
    example: '12/18 ÷ 6/6 = 2/3',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'How can you tell a fraction is in simplest form?',
    back: 'The only common factor of the numerator and denominator is 1 (their GCF is 1).',
    example: '7/12 is simplest: 7 is prime and doesn’t divide 12.',
    after: [2],
  },
  {
    n: 4, type: 'visual', difficulty: 2,
    front: 'These bars show 6/8 and 3/4. What is 6/8 in simplest form?',
    back: '3/4',
    explanation: 'Both bars are the same length. 6/8 uses 8 small pieces, but pairs of pieces can be joined into 4 bigger pieces.',
    visual: { kind: 'fraction-strip-stack', showAlignment: true, strips: [{ numerator: 6, denominator: 8 }, { numerator: 3, denominator: 4 }] },
    after: [2],
  },
  {
    n: 5, type: 'solve', difficulty: 1,
    front: 'Simplify 2/4.',
    back: '1/2',
    steps: ['Divide top and bottom by 2.', '2 ÷ 2 = 1 and 4 ÷ 2 = 2.'],
    after: [2],
  },
  {
    n: 6, type: 'solve', difficulty: 2,
    front: 'Simplify 6/9.',
    back: '2/3',
    steps: ['The common factor is 3.', '6 ÷ 3 = 2 and 9 ÷ 3 = 3.'],
    after: [5],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: 'Simplify 12/18.',
    back: '2/3',
    steps: ['GCF of 12 and 18 is 6.', '12 ÷ 6 = 2 and 18 ÷ 6 = 3.'],
    after: [6],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'Simplify 15/45.',
    back: '1/3',
    steps: ['GCF of 15 and 45 is 15.', '15 ÷ 15 = 1 and 45 ÷ 15 = 3.'],
    after: [6],
  },
  {
    n: 9, type: 'solve', difficulty: 3,
    front: 'Simplify 28/42.',
    back: '2/3',
    steps: ['GCF of 28 and 42 is 14.', '28 ÷ 14 = 2 and 42 ÷ 14 = 3.'],
    after: [7],
  },
  {
    n: 10, type: 'solve', difficulty: 3,
    front: 'Is 7/12 in simplest form?',
    back: 'Yes. 7 is prime and doesn’t divide 12, so the only common factor is 1.',
    after: [3],
    explanation: 'The factors of 12 are 1, 2, 3, 4, 6, 12. Only 1 is also a factor of 7, so no simplifying is possible.',
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'True or False: You can simplify 8/12 by subtracting 4 from the top and bottom to get 4/8.',
    back: 'False. 4/8 = 1/2, not 2/3. Simplify by DIVIDING both by the same number: 8/12 = 2/3.',
    commonMistake: 'Subtracting instead of dividing.',
    after: [2],
  },
  {
    n: 12, type: 'misconception', difficulty: 5,
    front: 'Ben simplifies 12/16 by dividing by 2 and gets 6/8. He says it’s done. Is it?',
    back: 'No. 6 and 8 still share the factor 2. Divide again to get 3/4 (or divide 12/16 by 4 at once).',
    commonMistake: 'Stopping before the fraction is fully simplified.',
    after: [3],
  },
  {
    n: 13, type: 'real-life', difficulty: 3,
    front: '8 of the 20 students in a class play soccer. What fraction play soccer, in simplest form?',
    back: '2/5',
    steps: ['8/20.', 'GCF of 8 and 20 is 4.', '8 ÷ 4 = 2 and 20 ÷ 4 = 5.'],
    after: [7],
  },
  {
    n: 14, type: 'challenge', difficulty: 4,
    front: 'Simplify 36/84 using the GCF.',
    back: '3/7',
    steps: ['Factors of 36: 1, 2, 3, 4, 6, 9, 12, 18, 36.', 'The GCF with 84 is 12.', '36 ÷ 12 = 3 and 84 ÷ 12 = 7.'],
    after: [9],
  },
  {
    n: 15, type: 'challenge', difficulty: 4,
    front: 'Find a fraction equal to 3/5 that has an even numerator and a denominator less than 20.',
    back: '6/10',
    steps: ['Multiply top and bottom by 2: 6/10.', 'Check others: 9/15 has an odd numerator; 12/20 has a denominator that isn’t less than 20.'],
    after: [7],
  },
]);
