import { defineCards } from '@/content/defineCards';

export const nsCompareDecimalsCards = defineCards('ns-compare-decimals', ['number-sense', 'comparing', 'decimals'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'How do you compare decimals?',
    back: 'Line up the decimal points and compare from the left. Add zeros at the end if it helps — they don’t change the value.',
    example: '0.6 vs 0.58 → 0.60 vs 0.58 → 0.60 > 0.58',
    memoryHook: 'More digits does NOT mean a bigger number.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'Does adding a zero to the end of a decimal change its value?',
    back: 'No. 0.5 = 0.50 = 0.500.',
    explanation: '5 tenths is the same amount as 50 hundredths.',
    memoryHook: 'Zeros at the end of a decimal are empty seats — they change nothing.',
    after: [1],
  },
  {
    n: 3, type: 'visual', difficulty: 1,
    front: 'Which decimal is greater: 0.6 or 0.58?',
    back: '0.6 is greater (60 hundredths > 58 hundredths).',
    explanation: 'The first grid has more squares shaded.',
    visual: {
      kind: 'row',
      separator: 'vs',
      items: [
        { kind: 'shaded-grid', rows: 10, cols: 10, shaded: 60, label: '0.6 = 0.60' },
        { kind: 'shaded-grid', rows: 10, cols: 10, shaded: 58, label: '0.58' },
      ],
    },
    after: [2],
  },
  {
    n: 4, type: 'solve', difficulty: 1,
    front: 'Compare: 0.7 ○ 0.3',
    back: '0.7 > 0.3',
    steps: ['Same place (tenths): 7 tenths vs 3 tenths.', '7 > 3, so 0.7 > 0.3.'],
    after: [1],
  },
  {
    n: 5, type: 'solve', difficulty: 2,
    front: 'Compare: 0.4 ○ 0.40',
    back: '0.4 = 0.40',
    steps: ['Write 0.4 as 0.40.', '40 hundredths = 40 hundredths.'],
    after: [2],
  },
  {
    n: 6, type: 'solve', difficulty: 3,
    front: 'Compare: 0.35 ○ 0.4',
    back: '0.35 < 0.4',
    steps: ['Write 0.4 as 0.40.', '35 hundredths < 40 hundredths.', '0.35 < 0.40'],
    after: [2],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: 'Compare: 2.508 ○ 2.58',
    back: '2.508 < 2.58',
    steps: ['Write 2.58 as 2.580.', 'Wholes and tenths match (2 and 5).', 'Hundredths: 0 < 8, so 2.508 < 2.580.'],
    after: [6],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'Compare: 0.09 ○ 0.1',
    back: '0.09 < 0.1',
    steps: ['Write 0.1 as 0.10.', '9 hundredths < 10 hundredths.'],
    after: [6],
  },
  {
    n: 9, type: 'misconception', difficulty: 5,
    front: 'True or False: 0.25 is greater than 0.3 because 25 is greater than 3.',
    back: 'False. 0.3 = 0.30, which is greater than 0.25.',
    explanation: '0.3 is 30 hundredths. 0.25 is 25 hundredths.',
    commonMistake: 'Reading the digits after the point as a whole number.',
    memoryHook: 'Make the places match first, then compare.',
    after: [6],
  },
  {
    n: 10, type: 'misconception', difficulty: 5,
    front: 'True or False: 0.5 and 0.50 are different numbers.',
    back: 'False. They are equal.',
    explanation: '5 tenths = 50 hundredths.',
    after: [2],
  },
  {
    n: 11, type: 'real-life', difficulty: 3,
    front: 'Ben ran the race in 11.62 seconds. Cal ran it in 11.6 seconds. Who was faster?',
    back: 'Cal, because 11.60 s is less time than 11.62 s.',
    steps: ['Write 11.6 as 11.60.', '11.60 < 11.62.', 'A smaller time means faster.'],
    after: [6],
  },
  {
    n: 12, type: 'challenge', difficulty: 4,
    front: 'Which digits can replace ■ so that 0.4■ < 0.43 is true?',
    back: '0, 1 or 2',
    steps: ['Tenths match (4).', 'Hundredths: ■ must be less than 3.', '■ can be 0, 1 or 2.'],
    after: [7],
  },
  {
    n: 13, type: 'challenge', difficulty: 4,
    front: 'Write a decimal that is between 0.3 and 0.4.',
    back: 'Many answers work, for example 0.35 (or 0.31, 0.38, 0.305 …).',
    hint: 'Write 0.3 as 0.30 and 0.4 as 0.40. What is between 30 and 40 hundredths?',
    explanation: 'There are always more decimals between two decimals.',
    after: [6, 8],
  },
]);
