import { defineCards } from '@/content/defineCards';
import { wholeChart } from './charts';

export const nsCompareWholeCards = defineCards('ns-compare-whole', ['number-sense', 'comparing'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'How do you compare two whole numbers?',
    back: 'Line up the places and compare digits from the LEFT. The first place where they differ decides which number is greater.',
    example: '4,625 vs 4,598\nThousands match (4). Hundreds: 6 > 5, so 4,625 is greater.',
    memoryHook: 'Start where the biggest places are.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'What do the symbols <, > and = mean?',
    back: '< means “is less than”, > means “is greater than”, = means “is equal to”.',
    memoryHook: 'The hungry alligator mouth opens toward the bigger number.',
    example: '3 < 7    9 > 4    5 = 5',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'If two whole numbers have a different number of digits, which is greater?',
    back: 'The one with more digits (as long as it doesn’t start with 0).',
    example: '12,000 > 9,999 because 12,000 has 5 digits and 9,999 has 4.',
    after: [1],
  },
  {
    n: 4, type: 'visual', difficulty: 1,
    front: 'Compare these two numbers. Which is greater and why?',
    back: '52,430 > 52,340. The first digits match until the hundreds, where 4 > 3.',
    visual: { kind: 'row', separator: 'vs', items: [wholeChart('52430', [2]), wholeChart('52340', [2])] },
    after: [1],
  },
  {
    n: 5, type: 'solve', difficulty: 1,
    front: 'Compare: 345 ○ 354',
    back: '345 < 354',
    steps: ['Hundreds: 3 and 3 — same.', 'Tens: 4 and 5 — 4 < 5.', 'So 345 < 354.'],
    after: [2],
  },
  {
    n: 6, type: 'solve', difficulty: 2,
    front: 'Compare: 7,208 ○ 7,280',
    back: '7,208 < 7,280',
    steps: ['Thousands and hundreds match.', 'Tens: 0 < 8.', '7,208 < 7,280'],
    after: [5],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: 'Compare: 46,019 ○ 46,109',
    back: '46,019 < 46,109',
    steps: ['Ten thousands and thousands match (4 and 6, 6).', 'Hundreds: 0 < 1.', 'So 46,019 < 46,109.'],
    after: [5],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'Compare: 1,000,000 ○ 999,999',
    back: '1,000,000 > 999,999',
    hint: 'Count the digits first.',
    steps: ['1,000,000 has 7 digits; 999,999 has 6.', 'More digits means greater.', '1,000,000 > 999,999. It is exactly 1 more.'],
    after: [3],
  },
  {
    n: 9, type: 'misconception', difficulty: 5,
    front: 'True or False: 9,999 is greater than 10,000 because 9 is greater than 1.',
    back: 'False. 10,000 is greater.',
    explanation: '10,000 has 5 digits, so its first digit is in the ten thousands place. Compare place by place, not digit by digit regardless of place.',
    commonMistake: 'Comparing the first digits of numbers that have different lengths.',
    after: [3],
  },
  {
    n: 10, type: 'misconception', difficulty: 5,
    front: 'Mia compared 6,481 and 6,148 by looking at the ones digits (1 and 8) and said 6,148 is greater. What went wrong?',
    back: 'She started on the right. Start on the left: hundreds 4 > 1, so 6,481 is greater.',
    commonMistake: 'Comparing from the ones place.',
    memoryHook: 'Biggest places first.',
    after: [6],
  },
  {
    n: 11, type: 'real-life', difficulty: 3,
    front: 'City A has 245,600 people. City B has 245,060. Which has more people?',
    back: 'City A',
    steps: ['Ten thousands, thousands: 4 and 5 match.', 'Hundreds: 6 > 0.', '245,600 > 245,060.'],
    after: [7],
  },
  {
    n: 12, type: 'challenge', difficulty: 4,
    front: 'Which digits can replace ■ so that 4,■72 > 4,572 is true?',
    back: '6, 7, 8 or 9',
    hint: 'Only the hundreds digit is unknown. What must it be bigger than?',
    steps: ['4,■72 > 4,572: thousands match.', 'Hundreds must be greater than 5.', 'If ■ = 5 the numbers are equal, so ■ can be 6, 7, 8 or 9.'],
    after: [7],
  },
  {
    n: 13, type: 'challenge', difficulty: 4,
    front: 'Compare: 5 × 10,000 ○ 49,999 + 2',
    back: '50,000 < 50,001',
    steps: ['5 × 10,000 = 50,000', '49,999 + 2 = 50,001', '50,000 < 50,001'],
    after: [8],
  },
]);
