import { defineCards } from '@/content/defineCards';
import { wholeChart } from './charts';

export const nsFormsCards = defineCards('ns-forms', ['number-sense', 'standard-form', 'expanded-form', 'word-form'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What are the three ways to write a number?',
    back: 'Standard form (digits), expanded form (a sum of each digit’s value) and word form (words).',
    example: '5,203\n5,000 + 200 + 3\nfive thousand, two hundred three',
    memoryHook: 'Same number, three outfits.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'How do you write a number in expanded form?',
    back: 'Write the value of each digit and add them. Skip any place that has a 0.',
    example: '4,075 = 4,000 + 70 + 5',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'How do you read a large number in word form?',
    back: 'Read each group of three digits like a small number, then say the group’s name (thousand, million …).',
    example: '34,500 → thirty-four thousand, five hundred',
    memoryHook: 'Commas are signposts: say the name wherever you see one. Never say “and” inside a whole number.',
    after: [1],
  },
  {
    n: 4, type: 'visual', difficulty: 1,
    front: 'Use the chart to write this number in expanded form.',
    back: '5,000 + 200 + 3',
    explanation: 'The 0 in the tens place adds nothing, so it is skipped.',
    visual: wholeChart('5203'),
    after: [2],
  },
  {
    n: 5, type: 'solve', difficulty: 1,
    front: 'Write 6,482 in expanded form.',
    back: '6,000 + 400 + 80 + 2',
    steps: ['6 is in the thousands → 6,000', '4 is in the hundreds → 400', '8 is in the tens → 80', '2 is in the ones → 2'],
    after: [2],
  },
  {
    n: 6, type: 'solve', difficulty: 2,
    front: 'Write “three thousand, forty-six” in standard form.',
    back: '3,046',
    steps: ['3 thousands → 3,___', 'No hundreds are named → 0', '46 → 4 tens and 6 ones', '3,046'],
    after: [3],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: 'Write 70,805 in word form.',
    back: 'Seventy thousand, eight hundred five',
    steps: ['Groups: 70 | 805', '70 → seventy thousand', '805 → eight hundred five'],
    after: [3],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'Write 200,000 + 6,000 + 40 + 9 in standard form.',
    back: '206,049',
    hint: 'Draw a place-value chart. Which places are empty?',
    steps: ['2 in the hundred thousands, 6 in the thousands, 4 in the tens, 9 in the ones.', 'The ten thousands and hundreds are empty → 0.', '206,049'],
    after: [2],
  },
  {
    n: 9, type: 'solve', difficulty: 3,
    front: 'Write 3,060,400 in word form.',
    back: 'Three million, sixty thousand, four hundred',
    steps: ['Groups: 3 | 060 | 400', '3 → three million', '060 → sixty thousand', '400 → four hundred'],
    after: [7],
  },
  {
    n: 10, type: 'misconception', difficulty: 5,
    front: 'True or False: “Five thousand twenty” is written 5,20.',
    back: 'False. It is 5,020.',
    explanation: 'Zeros hold the empty hundreds place so every digit stays in the right column.',
    commonMistake: 'Leaving out placeholder zeros.',
    answerVisual: wholeChart('5020'),
    after: [6],
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'Is 3,000 + 40 + 5 the same as 3,405?',
    back: 'No. It is 3,045.',
    explanation: 'The 40 means 4 tens, so the 4 goes in the tens place. 3,405 would need 400.',
    after: [8],
  },
  {
    n: 12, type: 'real-life', difficulty: 3,
    front: 'Mount Everest is about 29,032 feet tall. Write that height in words.',
    back: 'Twenty-nine thousand, thirty-two feet',
    steps: ['Groups: 29 | 032', '29 → twenty-nine thousand', '032 → thirty-two'],
    after: [7],
  },
  {
    n: 13, type: 'challenge', difficulty: 4,
    front: 'Write 12,000,900 in expanded form and in word form.',
    back: '10,000,000 + 2,000,000 + 900\nTwelve million, nine hundred',
    steps: ['Groups: 12 | 000 | 900', '1 ten million + 2 million + 9 hundreds', 'Words: twelve million, (zero thousands is skipped), nine hundred'],
    after: [8, 9],
  },
]);
