import { defineCards } from '@/content/defineCards';

export const nsRoundWholeCards = defineCards('ns-round-whole', ['number-sense', 'rounding'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What does rounding mean?',
    back: 'Replacing a number with a nearby “friendly” number (like a multiple of 10, 100 or 1,000) that is the closest one.',
    memoryHook: 'Rounding is finding the nearest town on the road.',
    example: '47 is closest to 50 → 47 rounds to 50 (nearest ten)',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'What are the steps for rounding a whole number to a place?',
    back: 'Underline the place. Look at the digit to its right: 5 or more → round up. 4 or less → keep the digit. Then make every digit to the right 0.',
    example: '3,476 to the nearest hundred: the digit to the right of hundreds is 7 → round up → 3,500',
    memoryHook: 'Five or more, raise the score. Four or less, let it rest.',
    after: [1],
  },
  {
    n: 3, type: 'visual', difficulty: 1,
    front: '346 sits between 340 and 350. Which ten is it closer to?',
    back: '350',
    explanation: 'The halfway point is 345. 346 is past halfway, so it rounds up to 350.',
    visual: { kind: 'rounding-line', min: 340, max: 350, step: 10, value: 346, roundsTo: 350, showMidpoint: true },
    after: [1],
  },
  {
    n: 4, type: 'visual', difficulty: 2,
    front: 'Round 3,640 to the nearest thousand. Use the number line.',
    back: '4,000',
    explanation: 'The halfway point between 3,000 and 4,000 is 3,500. 3,640 is past it, so it rounds up.',
    visual: { kind: 'rounding-line', min: 3000, max: 4000, step: 1000, value: 3640, roundsTo: 4000, showMidpoint: true },
    after: [3],
  },
  {
    n: 5, type: 'solve', difficulty: 1,
    front: 'Round 47 to the nearest ten.',
    back: '50',
    steps: ['The tens place is 4. Look at the ones digit: 7.', '7 is 5 or more → round up.', '47 → 50'],
    after: [2],
  },
  {
    n: 6, type: 'solve', difficulty: 2,
    front: 'Round 628 to the nearest hundred.',
    back: '600',
    steps: ['The hundreds digit is 6. Look at the tens digit: 2.', '2 is 4 or less → keep the 6.', 'Zeros after it → 600'],
    after: [5],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: 'Round 4,951 to the nearest hundred.',
    back: '5,000',
    steps: ['Hundreds digit is 9. Look at the tens digit: 5.', '5 → round up. 9 hundreds + 1 = 10 hundreds.', '10 hundreds is 1,000, so 4,000 + 1,000 = 5,000.'],
    after: [6],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'Round 36,482 to the nearest thousand.',
    back: '36,000',
    steps: ['Thousands digit is 6. Look at the hundreds digit: 4.', '4 → keep the 6.', '36,000'],
    after: [6],
  },
  {
    n: 9, type: 'solve', difficulty: 3,
    front: 'Round 249,500 to the nearest ten thousand.',
    back: '250,000',
    steps: ['Ten thousands digit is 4. Look at the thousands digit: 9.', '9 → round up: 4 → 5 ten thousands.', '250,000'],
    after: [7],
  },
  {
    n: 10, type: 'solve', difficulty: 4,
    front: 'Round 1,995,000 to the nearest million.',
    back: '2,000,000',
    hint: 'Look at the hundred thousands digit.',
    steps: ['Millions digit is 1. Look at the hundred thousands digit: 9.', '9 → round up: 1 million + 1 million = 2 million.', '2,000,000'],
    after: [9],
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'True or False: To round 2,449 to the nearest hundred, round the 9 up to 2,450, then round again to 2,500.',
    back: 'False. 2,400.',
    explanation: 'Only look at the digit right next to the place you’re rounding to — the tens digit, 4. It is less than 5, so keep 4 hundreds.',
    commonMistake: 'Rounding step by step from the right (“double rounding”).',
    after: [7],
  },
  {
    n: 12, type: 'misconception', difficulty: 5,
    front: 'True or False: 85 rounds to 80 to the nearest ten because it’s exactly halfway.',
    back: 'False. Halfway numbers round up, so 85 rounds to 90.',
    explanation: 'The rule is “5 or more rounds up”, and that includes exactly halfway.',
    after: [5],
  },
  {
    n: 13, type: 'real-life', difficulty: 3,
    front: 'A stadium has 42,687 fans. A reporter says “about ___ fans,” rounding to the nearest thousand. What does the reporter say?',
    back: 'About 43,000 fans',
    steps: ['Thousands digit is 2. Look at the hundreds digit: 6.', '6 → round up: 42 → 43 thousands.', '43,000'],
    after: [8],
  },
  {
    n: 14, type: 'challenge', difficulty: 4,
    front: 'A whole number rounds to 700 when rounded to the nearest hundred. What are the least and greatest numbers it could be?',
    back: 'Least 650, greatest 749.',
    hint: 'Where is the halfway point below 700? Above 700?',
    steps: ['Halfway between 600 and 700 is 650. Halfway between 700 and 800 is 750.', '650 is the first number that rounds up to 700 (649 rounds down to 600).', '749 is the last number that rounds down to 700 (750 rounds up to 800).'],
    after: [9],
  },
  {
    n: 15, type: 'challenge', difficulty: 4,
    front: 'Estimate 38 + 52 + 19 by rounding each number to the nearest ten. Is the exact sum a little more or a little less?',
    back: 'Estimate: 40 + 50 + 20 = 110. The exact sum is 109, a little less.',
    steps: ['38 → 40, 52 → 50, 19 → 20', '40 + 50 + 20 = 110', 'Exact: 38 + 52 + 19 = 109'],
    after: [6],
  },
]);
