import { defineCards } from '@/content/defineCards';

export const nsRoundDecimalsCards = defineCards('ns-round-decimals', ['number-sense', 'rounding', 'decimals'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'How is rounding a decimal like rounding a whole number?',
    back: 'It’s the same idea: find the closest number with the place you want, using the digit to the right to decide.',
    memoryHook: 'Same rule, other side of the decimal point.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'How do you round a decimal to the nearest tenth or hundredth?',
    back: 'Look at the digit one place to the right of your target place. 5 or more → round up. 4 or less → stay. Then drop the digits after your place.',
    example: '3.67 to the nearest tenth: the next digit is 7 → round up → 3.7',
    after: [1],
  },
  {
    n: 3, type: 'visual', difficulty: 1,
    front: '0.37 is between 0.3 and 0.4. Which tenth is it closer to?',
    back: '0.4',
    explanation: 'The halfway point is 0.35. 0.37 is past it, so it rounds up to 0.4.',
    visual: { kind: 'rounding-line', min: 0.3, max: 0.4, step: 0.1, value: 0.37, roundsTo: 0.4, showMidpoint: true },
    after: [1],
  },
  {
    n: 4, type: 'solve', difficulty: 1,
    front: 'Round 6.3 to the nearest whole number.',
    back: '6',
    steps: ['Ones digit is 6. Look at the tenths digit: 3.', '3 → stay.', '6'],
    after: [2],
  },
  {
    n: 5, type: 'solve', difficulty: 2,
    front: 'Round 5.78 to the nearest tenth.',
    back: '5.8',
    steps: ['Tenths digit is 7. Look at the hundredths digit: 8.', '8 → round up: 7 → 8.', '5.8'],
    after: [4],
  },
  {
    n: 6, type: 'solve', difficulty: 3,
    front: 'Round 4.236 to the nearest hundredth.',
    back: '4.24',
    steps: ['Hundredths digit is 3. Look at the thousandths digit: 6.', '6 → round up: 3 → 4.', '4.24'],
    after: [5],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: 'Round 12.349 to the nearest tenth.',
    back: '12.3',
    hint: 'Only look at the hundredths digit — not the 9.',
    steps: ['Tenths digit is 3. Look at the hundredths digit: 4.', '4 → stay.', '12.3'],
    after: [5],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'Round 8.5 to the nearest whole number.',
    back: '9',
    steps: ['Ones digit is 8. Look at the tenths digit: 5.', '5 → round up.', '9'],
    after: [4],
  },
  {
    n: 9, type: 'solve', difficulty: 4,
    front: 'Round 0.996 to the nearest hundredth.',
    back: '1.00',
    hint: 'What happens when you round up a 9?',
    steps: ['Hundredths digit is 9. Look at the thousandths digit: 6.', '6 → round up: 9 hundredths + 1 = 10 hundredths.', '99 hundredths + 1 more hundredth = 100 hundredths = 1.00.'],
    after: [6],
  },
  {
    n: 10, type: 'misconception', difficulty: 5,
    front: 'True or False: 3.45 rounded to the nearest tenth is 3.4 because 4 is less than 5.',
    back: 'False. It rounds to 3.5.',
    explanation: 'You decide using the digit to the RIGHT of the tenths place — the hundredths digit, 5.',
    commonMistake: 'Looking at the digit in the place being rounded instead of the digit to its right.',
    after: [5],
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'Ben rounds 7.296 to the nearest hundredth by chopping off the last digit and writes 7.29. What’s wrong?',
    back: 'Chopping isn’t rounding. The thousandths digit is 6, so round up to 7.30.',
    after: [6],
  },
  {
    n: 12, type: 'real-life', difficulty: 3,
    front: 'Gas costs $3.789 per gallon. What is the price to the nearest cent?',
    back: '$3.79',
    steps: ['Cents are hundredths. Hundredths digit is 8. Look at thousandths: 9.', '9 → round up: 8 → 9.', '$3.79'],
    after: [6],
  },
  {
    n: 13, type: 'challenge', difficulty: 4,
    front: 'A number rounds to 4.5 to the nearest tenth. What are the least and greatest two-decimal-place numbers it could be?',
    back: 'Least 4.45, greatest 4.54.',
    hint: 'Which hundredths values round to 4.5?',
    steps: ['4.45 rounds up to 4.5 (5 rounds up).', '4.54 rounds to 4.5 (4 stays).', '4.55 would round up to 4.6, 4.44 would round down to 4.4.'],
    after: [7, 9],
  },
]);
