import { defineCards } from '@/content/defineCards';
import { decimalChart } from './charts';

export const pvDecimalCards = defineCards('pv-decimal', ['number-sense', 'place-value', 'decimals'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What does the decimal point do?',
    back: 'It separates whole-number places (left) from parts-of-a-whole places (right).',
    example: '3.45 → 3 wholes and 45 hundredths',
    memoryHook: 'Wholes live on the left. Pieces live on the right.',
    visual: decimalChart('3.45'),
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'What are the first three places after the decimal point, in order?',
    back: 'Tenths, hundredths, thousandths.',
    rule: 'Each place is one-tenth of the place to its left.',
    example: '0.1 → 0.01 → 0.001',
    memoryHook: 'Places that end in “-ths” are fractions of one whole.',
    after: [1],
  },
  {
    n: 3, type: 'visual', difficulty: 1,
    front: 'What is the value of the highlighted digit?',
    back: '0.07 (7 hundredths)',
    explanation: 'The 7 sits under “Hundredths”, so it is worth 7 hundredths.',
    visual: decimalChart('6.275', [2]),
    after: [2],
  },
  {
    n: 4, type: 'visual', difficulty: 2,
    front: 'This grid has 100 squares. What decimal does the shaded part show?',
    back: '0.37',
    explanation: '37 of 100 squares are shaded, so it is 37 hundredths.',
    memoryHook: 'Hundredths = one square out of a hundred.',
    visual: { kind: 'shaded-grid', rows: 10, cols: 10, shaded: 37, label: '37 of 100 squares' },
    after: [2],
  },
  {
    n: 5, type: 'solve', difficulty: 2,
    front: 'What is the value of the 8 in 4.286?',
    back: '0.08 (8 hundredths)',
    steps: ['After the decimal point: 2 is tenths, 8 is hundredths, 6 is thousandths.', 'The 8 is in the hundredths place.', '8 hundredths = 0.08.'],
    answerVisual: decimalChart('4.286', [2]),
    after: [3],
  },
  {
    n: 6, type: 'solve', difficulty: 3,
    front: 'In 0.763, which digit is in the tenths place? The hundredths? The thousandths?',
    back: 'Tenths 7, hundredths 6, thousandths 3.',
    steps: ['Read the digits after the decimal point from left to right.', 'First place is tenths → 7', 'Second place is hundredths → 6', 'Third place is thousandths → 3'],
    answerVisual: decimalChart('0.763'),
    after: [3],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: 'Write 5 tenths, 3 hundredths and 2 thousandths as a decimal.',
    back: '0.532',
    steps: ['Tenths first: 5', 'Hundredths next: 3', 'Thousandths last: 2', 'Put them after the decimal point: 0.532'],
    after: [3],
  },
  {
    n: 8, type: 'misconception', difficulty: 5,
    front: 'True or False: The 3 in 0.03 and the 3 in 0.3 are worth the same.',
    back: 'False. 0.3 is 3 tenths. 0.03 is 3 hundredths, which is 10 times smaller.',
    commonMistake: 'Ignoring which place a digit is in.',
    answerVisual: { kind: 'row', separator: '≠', items: [decimalChart('0.3', [1]), decimalChart('0.03', [2])] },
    after: [2],
  },
  {
    n: 9, type: 'misconception', difficulty: 5,
    front: 'Ria says the thousandths place is the biggest decimal place because “thousand” is a big number. Is she right?',
    back: 'No. Thousandths is the smallest of the three places: 1 thousandth = 0.001.',
    explanation: 'Moving right means cutting the whole into more and more pieces, so each piece gets smaller.',
    memoryHook: 'Think pizza: cut it in 1,000 slices and each slice is tiny.',
    after: [2],
  },
  {
    n: 10, type: 'real-life', difficulty: 3,
    front: 'A runner finishes in 12.48 seconds. What does the 8 stand for?',
    back: '8 hundredths of a second (0.08 s).',
    steps: ['12 is the whole seconds.', 'After the decimal point: 4 tenths, 8 hundredths.', 'So the 8 means 0.08 seconds.'],
    answerVisual: decimalChart('12.48', [3]),
    after: [5],
  },
  {
    n: 11, type: 'challenge', difficulty: 4,
    front: 'Which digit 4 is worth more: the one in 6.043 or the one in 6.304? How many times more?',
    back: 'The 4 in 6.043 (0.04) is worth 10 times as much as the 4 in 6.304 (0.004).',
    steps: ['6.043: the 4 is in the hundredths place → 0.04', '6.304: the 4 is in the thousandths place → 0.004', '0.04 ÷ 0.004 = 10'],
    after: [5, 6],
  },
  {
    n: 12, type: 'challenge', difficulty: 5,
    front: 'Find my number: my ones digit is 6. My tenths digit is half my ones digit. My hundredths digit is 1 less than my tenths digit. My thousandths digit is double my hundredths digit.',
    back: '6.324',
    steps: ['Ones: 6', 'Tenths: half of 6 = 3', 'Hundredths: 3 − 1 = 2', 'Thousandths: 2 × 2 = 4', 'The number is 6.324'],
    after: [6, 7],
  },
]);
