import { defineCards } from '@/content/defineCards';
import { wholeChart } from './charts';

export const pvWholeCards = defineCards('pv-whole', ['number-sense', 'place-value'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What is place value?',
    back: 'The value of a digit depends on its position (its place) in the number.',
    example: 'In 3,333 the four 3s are worth different amounts:\n3,000 · 300 · 30 · 3',
    memoryHook: 'Each place is worth 10× the place to its right.',
    visual: wholeChart('3333'),
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'How do the values of neighboring places compare?',
    back: 'Each place is 10 times the value of the place to its right.',
    explanation: 'Going left, values grow ×10 each step. Going right, they shrink to one-tenth.',
    example: '10 is 10 × 1\n100 is 10 × 10\n1,000 is 10 × 100',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'What are the place names from the ones place all the way up to billions?',
    back: 'Ones, tens, hundreds, thousands, ten thousands, hundred thousands, millions, ten millions, hundred millions, billions.',
    memoryHook: 'Digits come in groups of three — ones, thousands, millions, billions. The commas are signposts between groups.',
    example: '4,207,319,586 → 4 billion · 207 million · 319 thousand · 586',
    after: [2],
  },
  {
    n: 4, type: 'visual', difficulty: 1,
    front: 'Look at the chart. What is the value of the highlighted digit?',
    back: '80,000 — the 8 is in the ten thousands place.',
    explanation: 'Read the column name above the digit, then say the digit times that place: 8 × 10,000.',
    visual: wholeChart('3482916', [2]),
    after: [3],
  },
  {
    n: 5, type: 'solve', difficulty: 2,
    front: 'What is the value of the 7 in 5,274?',
    back: '70',
    hint: 'Count places from the right: ones, tens, hundreds, thousands.',
    steps: ['Digits from the right: 4 is ones, 7 is tens.', 'The 7 is in the tens place.', '7 tens = 70.'],
    answerVisual: wholeChart('5274', [2]),
    after: [3],
  },
  {
    n: 6, type: 'solve', difficulty: 3,
    front: 'What is the value of the 4 in 4,308,127?',
    back: '4,000,000 (four million)',
    steps: ['Count the digits: 4,308,127 has 7 digits.', 'The first digit of a 7-digit number is in the millions place.', '4 millions = 4,000,000.'],
    after: [5],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: 'In 63,490,215, which digit is in the ten millions place, and what is it worth?',
    back: 'The 6 — it is worth 60,000,000.',
    hint: 'This number has 8 digits. Name the places from the left: ten millions, millions, …',
    steps: [
      'Name the places from the right: ones 5, tens 1, hundreds 2, thousands 0, ten thousands 9, hundred thousands 4, millions 3, ten millions 6.',
      'The ten millions digit is 6.',
      '6 × 10,000,000 = 60,000,000.',
    ],
    after: [5],
  },
  {
    n: 8, type: 'misconception', difficulty: 5,
    front: 'True or False: In 2,050 the 0 in the hundreds place doesn’t matter, because zero means “nothing.”',
    back: 'False. The 0 is a placeholder that keeps the 2 in the thousands place.',
    explanation: 'Without it you would have 250, a much smaller number.',
    commonMistake: 'Dropping placeholder zeros.',
    answerVisual: wholeChart('2050', [2]),
    after: [3],
  },
  {
    n: 9, type: 'misconception', difficulty: 5,
    front: 'True or False: The 5 in 5,000 is worth the same as the 5 in 500, because both digits are 5.',
    back: 'False. The 5 in 5,000 is worth 5,000, which is 10 times as much as the 5 in 500.',
    commonMistake: 'Thinking a digit always has the same value.',
    memoryHook: 'Same digit, different floor of the building.',
    after: [2],
  },
  {
    n: 10, type: 'real-life', difficulty: 3,
    front: 'A city has 3,482,916 people. Read the number aloud, then say what the 4 stands for.',
    back: 'Three million, four hundred eighty-two thousand, nine hundred sixteen. The 4 stands for 400,000.',
    steps: ['Split into groups: 3 | 482 | 916.', 'Say each group with its name: 3 million, 482 thousand, 916.', 'The 4 is in the hundred thousands place → 400,000.'],
    answerVisual: wholeChart('3482916', [1]),
    after: [6],
  },
  {
    n: 11, type: 'challenge', difficulty: 4,
    front: 'Use the digits 7, 0, 4, 9 and 2 once each. Make the greatest and the least 5-digit number.',
    back: 'Greatest: 97,420. Least: 20,479.',
    hint: 'A number can’t start with 0 if you want it to really have 5 digits.',
    steps: ['Greatest: put the biggest digits in the biggest places → 9, 7, 4, 2, 0 = 97,420.', 'Least: smallest digit that can lead is 2, then 0, 4, 7, 9 → 20,479.'],
    after: [6, 7],
  },
  {
    n: 12, type: 'challenge', difficulty: 5,
    front: 'How many times as much is the 9 in 9,000,000,000 as the 9 in 900,000,000?',
    back: '10 times as much.',
    explanation: '9 billion ÷ 900 million = 10. One place to the left is always ×10.',
    visual: wholeChart('9000000000', [0]),
    after: [3, 6],
  },
]);
