import { defineCards } from '@/content/defineCards';

export const intAddDifferentCards = defineCards('int-add-different', ['integers', 'addition', 'different-signs'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What happens when you add a positive and a negative number?',
    back: 'They partly cancel each other out. The answer has the sign of the number that is farther from zero.',
    memoryHook: 'Different signs: subtract the sizes, keep the sign of the bigger one.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'What is the rule for adding two numbers with different signs?',
    back: 'Subtract the smaller absolute value from the larger. Give the answer the sign of the number with the larger absolute value.',
    example: '−8 + 3: 8 − 3 = 5, and 8 is bigger and negative → −5',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'What is a zero pair?',
    back: 'A +1 and a −1 together. They cancel to make 0. Any number plus its opposite is 0.',
    example: '5 + (−5) = 0',
    after: [1],
  },
  {
    n: 4, type: 'visual', difficulty: 1,
    front: 'Match each yellow + with a red −. What is left over? What is 3 + (−5)?',
    back: '2 red counters are left, so 3 + (−5) = −2.',
    explanation: 'Three zero pairs cancel to 0, leaving two −1s.',
    visual: { kind: 'counters', positive: 3, negative: 5 },
    answerVisual: { kind: 'counters', positive: 3, negative: 5, showPairs: true },
    after: [3],
  },
  {
    n: 5, type: 'visual', difficulty: 2,
    front: 'Start at 4 and jump 7 to the left. Where do you land? What is 4 + (−7)?',
    back: '−3, so 4 + (−7) = −3.',
    visual: { kind: 'integer-line', min: -6, max: 6, start: 4, jumps: [{ by: -7 }], showEnd: false },
    answerVisual: { kind: 'integer-line', min: -6, max: 6, start: 4, jumps: [{ by: -7 }] },
    after: [2],
  },
  {
    n: 6, type: 'solve', difficulty: 1,
    front: '7 + (−2) = ?',
    back: '5',
    steps: ['Sizes: 7 − 2 = 5.', '7 is bigger and positive → 5.'],
    after: [2],
  },
  {
    n: 7, type: 'solve', difficulty: 2,
    front: '−9 + 4 = ?',
    back: '−5',
    steps: ['Sizes: 9 − 4 = 5.', '9 is bigger and negative → −5.'],
    after: [6],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: '12 + (−20) = ?',
    back: '−8',
    steps: ['Sizes: 20 − 12 = 8.', '20 is bigger and negative → −8.'],
    after: [7],
  },
  {
    n: 9, type: 'solve', difficulty: 3,
    front: '−15 + 15 = ?',
    back: '0',
    explanation: 'Opposites cancel: they form 15 zero pairs.',
    after: [3],
  },
  {
    n: 10, type: 'solve', difficulty: 3,
    front: '−6 + 10 + (−3) = ?',
    back: '1',
    steps: ['−6 + 10 = 4.', '4 + (−3) = 1.'],
    after: [7],
  },
  {
    n: 11, type: 'solve', difficulty: 4,
    front: '45 + (−62) = ?',
    back: '−17',
    steps: ['Sizes: 62 − 45 = 17.', '62 is bigger and negative → −17.'],
    after: [8],
  },
  {
    n: 12, type: 'misconception', difficulty: 5,
    front: 'Ben says −8 + 3 = −11. What did he do wrong?',
    back: 'He added the sizes. With different signs you subtract them: 8 − 3 = 5, so −8 + 3 = −5.',
    commonMistake: 'Adding sizes when the signs are different.',
    after: [7],
  },
  {
    n: 13, type: 'misconception', difficulty: 5,
    front: 'True or False: A positive plus a negative is always negative.',
    back: 'False. It depends on which is farther from 0. 9 + (−4) = 5 is positive.',
    after: [6],
  },
  {
    n: 14, type: 'real-life', difficulty: 3,
    front: 'You have $15 and buy something for $22 on credit. What is your balance as an integer?',
    back: '−7 (you owe $7).',
    steps: ['15 + (−22).', 'Sizes: 22 − 15 = 7.', '22 is bigger and negative → −7.'],
    after: [8],
  },
  {
    n: 15, type: 'real-life', difficulty: 3,
    front: 'A football team loses 8 yards, then gains 13 yards. What is the total change?',
    back: 'A gain of 5 yards (+5)',
    steps: ['−8 + 13.', 'Sizes: 13 − 8 = 5.', '13 is bigger and positive → 5.'],
    after: [7],
  },
  {
    n: 16, type: 'challenge', difficulty: 4,
    front: 'Find the missing number: −7 + ___ = 4',
    back: '11',
    steps: ['From −7, how far right do you go to reach 4?', '7 steps to 0, then 4 more: 11.', 'CHECK: −7 + 11 = 4 ✓'],
    after: [10],
  },
  {
    n: 17, type: 'challenge', difficulty: 4,
    front: 'In the morning it is −6 °. By noon it rises 9 °, and by night it falls 5 °. What is the night temperature?',
    back: '−2 °',
    steps: ['−6 + 9 = 3.', '3 + (−5) = −2.'],
    after: [10],
  },
]);
