import { defineCards } from '@/content/defineCards';

export const intAddSameCards = defineCards('int-add-same', ['integers', 'addition', 'same-signs'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What happens when you add two positives? Two negatives?',
    back: 'Positive + positive is positive. Negative + negative is negative — like owing $3 and then owing $5 more: now you owe $8.',
    memoryHook: 'Same signs: add the sizes, keep the sign.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'What is the rule for adding two numbers with the same sign?',
    back: 'Add their absolute values (sizes) and keep the sign they share.',
    example: '−3 + (−5): 3 + 5 = 8, both negative → −8',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'On a number line, what does adding a negative number look like?',
    back: 'Adding a positive moves you right. Adding a negative moves you left.',
    after: [1],
  },
  {
    n: 4, type: 'visual', difficulty: 1,
    front: 'Start at −3 and jump 5 to the left. Where do you land? What is −3 + (−5)?',
    back: '−8, so −3 + (−5) = −8.',
    visual: { kind: 'integer-line', min: -10, max: 2, start: -3, jumps: [{ by: -5 }], showEnd: false },
    answerVisual: { kind: 'integer-line', min: -10, max: 2, start: -3, jumps: [{ by: -5 }] },
    after: [3],
  },
  {
    n: 5, type: 'solve', difficulty: 1,
    front: '4 + 7 = ?',
    back: '11',
    explanation: 'Both positive, so the answer is positive.',
    after: [2],
  },
  {
    n: 6, type: 'solve', difficulty: 2,
    front: '−2 + (−6) = ?',
    back: '−8',
    steps: ['Same signs: add the sizes, 2 + 6 = 8.', 'Both are negative → −8.'],
    after: [2],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: '−15 + (−9) = ?',
    back: '−24',
    steps: ['15 + 9 = 24.', 'Both negative → −24.'],
    after: [6],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: '−7 + (−3) + (−5) = ?',
    back: '−15',
    steps: ['7 + 3 + 5 = 15.', 'All negative → −15.'],
    after: [6],
  },
  {
    n: 9, type: 'solve', difficulty: 4,
    front: '−125 + (−75) = ?',
    back: '−200',
    steps: ['125 + 75 = 200.', 'Both negative → −200.'],
    after: [7],
  },
  {
    n: 10, type: 'misconception', difficulty: 5,
    front: 'True or False: −4 + (−6) = 10, because 4 + 6 = 10.',
    back: 'False. Two negatives make a bigger negative: −4 + (−6) = −10.',
    commonMistake: 'Dropping the negative sign.',
    after: [6],
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'Lee says −2 + (−3) = 5 because “two negatives make a positive.” What is wrong?',
    back: '“Two negatives make a positive” is the rule for MULTIPLYING, not adding. When you add, −2 + (−3) = −5.',
    commonMistake: 'Using the multiplication sign rule for addition.',
    after: [6],
  },
  {
    n: 12, type: 'real-life', difficulty: 3,
    front: 'You owe $12. Then you borrow $8 more. What is your balance as an integer?',
    back: '−20 (you owe $20).',
    steps: ['Owing is negative: −12 + (−8).', '12 + 8 = 20, keep the negative sign.'],
    after: [7],
  },
  {
    n: 13, type: 'real-life', difficulty: 3,
    front: 'The temperature is −4 °. It drops 7 more degrees. What is the new temperature?',
    back: '−11 °',
    steps: ['−4 + (−7).', '4 + 7 = 11, keep the negative sign.'],
    after: [6],
  },
  {
    n: 14, type: 'challenge', difficulty: 4,
    front: 'How many different pairs of negative integers add up to −10? (Count −1 and −9 the same as −9 and −1.)',
    back: '5 pairs: −1 and −9, −2 and −8, −3 and −7, −4 and −6, −5 and −5.',
    hint: 'The sizes must add to 10.',
    after: [8],
  },
]);
