import { defineCards } from '@/content/defineCards';

export const intDivideCards = defineCards('int-divide', ['integers', 'division', 'sign-rules'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'How is dividing integers like multiplying them?',
    back: 'It uses the same sign rule: same signs → positive, different signs → negative.',
    memoryHook: 'Division follows the same sign rule as multiplication.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'What is the sign rule for dividing integers?',
    back: 'Divide the sizes as usual. Same signs → positive answer. Different signs → negative answer.',
    example: '−12 ÷ 3 = −4    −12 ÷ (−3) = 4',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'How can you check that −12 ÷ (−3) = 4?',
    back: 'Multiply back: 4 × (−3) = −12 ✓. Division and multiplication undo each other.',
    after: [2],
  },
  {
    n: 4, type: 'visual', difficulty: 2,
    front: 'From 0 to −12 in 3 equal jumps. How big is each jump? What is −12 ÷ 3?',
    back: 'Each jump is −4, so −12 ÷ 3 = −4.',
    visual: { kind: 'integer-line', min: -13, max: 1, start: 0, jumps: [{ by: -4, label: '?' }, { by: -4, label: '?' }, { by: -4, label: '?' }] },
    answerVisual: { kind: 'integer-line', min: -13, max: 1, start: 0, jumps: [{ by: -4 }, { by: -4 }, { by: -4 }] },
    after: [2],
  },
  {
    n: 5, type: 'solve', difficulty: 1,
    front: '−20 ÷ 4 = ?',
    back: '−5',
    steps: ['20 ÷ 4 = 5.', 'Different signs → negative: −5.'],
    after: [2],
  },
  {
    n: 6, type: 'solve', difficulty: 2,
    front: '36 ÷ (−9) = ?',
    back: '−4',
    steps: ['36 ÷ 9 = 4.', 'Different signs → negative: −4.'],
    after: [5],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: '−45 ÷ (−5) = ?',
    back: '9',
    steps: ['45 ÷ 5 = 9.', 'Same signs → positive: 9.', 'CHECK: 9 × (−5) = −45 ✓'],
    after: [3],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: '0 ÷ (−7) = ?',
    back: '0',
    explanation: 'Zero divided by any non-zero number is 0.',
    after: [5],
  },
  {
    n: 9, type: 'solve', difficulty: 3,
    front: '−56 ÷ 8 = ?',
    back: '−7',
    steps: ['56 ÷ 8 = 7.', 'Different signs → negative: −7.'],
    after: [6],
  },
  {
    n: 10, type: 'solve', difficulty: 4,
    front: '(−72 ÷ 8) ÷ (−3) = ?',
    back: '3',
    steps: ['−72 ÷ 8 = −9.', '−9 ÷ (−3) = 3.'],
    after: [7],
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'True or False: −18 ÷ (−3) = −6.',
    back: 'False. Same signs give a positive answer: −18 ÷ (−3) = 6.',
    after: [2],
  },
  {
    n: 12, type: 'misconception', difficulty: 5,
    front: 'True or False: −10 ÷ 2 and 10 ÷ (−2) give different answers.',
    back: 'False. Both have different signs, so both equal −5.',
    after: [6],
  },
  {
    n: 13, type: 'real-life', difficulty: 3,
    front: 'The temperature dropped 15 degrees evenly over 5 hours. What was the change each hour?',
    back: '−3 degrees per hour',
    steps: ['−15 ÷ 5 = −3.'],
    after: [6],
  },
  {
    n: 14, type: 'real-life', difficulty: 3,
    front: 'A diver goes from 0 m down to −60 m in 4 equal stages. How deep is each stage?',
    back: '−15 m per stage',
    steps: ['−60 ÷ 4 = −15.'],
    after: [6],
  },
  {
    n: 15, type: 'challenge', difficulty: 4,
    front: 'What number divided by −6 gives 7?',
    back: '−42',
    steps: ['Undo the division by multiplying: 7 × (−6) = −42.', 'CHECK: −42 ÷ (−6) = 7 ✓'],
    after: [7],
  },
  {
    n: 16, type: 'challenge', difficulty: 4,
    front: 'Find the average (mean) of −8, −2, 4 and −6.',
    back: '−3',
    steps: ['Add them: −8 + (−2) + 4 + (−6) = −12.', 'Divide by how many there are: −12 ÷ 4 = −3.'],
    after: [9],
  },
]);
