import { defineCards } from '@/content/defineCards';

export const intMeaningCards = defineCards('int-meaning', ['integers', 'negative-numbers'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What is a negative number?',
    back: 'A number less than zero. It is written with a minus sign, like −4, and sits 4 steps to the LEFT of 0 on the number line.',
    memoryHook: 'Below zero, like a thermometer on a freezing day.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'Where do you see negative numbers in real life?',
    back: 'Temperatures below zero, money you owe, places below sea level, points lost in a game, and floors below the ground floor.',
    example: '−5 °C, owing $8 → −8, 20 m below sea level → −20',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'What are opposites?',
    back: 'Two numbers the same distance from 0 on opposite sides, like 5 and −5. Opposites always add up to 0.',
    example: '7 and −7 are opposites. 7 + (−7) = 0',
    after: [1],
  },
  {
    n: 4, type: 'visual', difficulty: 1,
    front: 'What number is marked on this number line?',
    back: '−3',
    explanation: 'It is 3 steps to the left of 0.',
    visual: { kind: 'integer-line', min: -5, max: 5, marks: [{ value: -3, label: '' }] },
    answerVisual: { kind: 'integer-line', min: -5, max: 5, marks: [{ value: -3, label: '−3' }] },
    after: [1],
  },
  {
    n: 5, type: 'solve', difficulty: 1,
    front: 'It is 4 degrees below zero. Write the temperature as an integer.',
    back: '−4',
    explanation: 'Below zero means negative.',
    after: [2],
  },
  {
    n: 6, type: 'solve', difficulty: 2,
    front: 'What is the opposite of 7? What is the opposite of −12?',
    back: '−7 and 12',
    explanation: 'The opposite is the same distance from 0 on the other side.',
    after: [3],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: 'A diver is 20 feet below sea level. A bird is 15 feet above sea level. Write both heights as integers.',
    back: 'Diver: −20. Bird: 15.',
    explanation: 'Sea level is 0. Below it is negative and above it is positive.',
    after: [5],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'Write an integer for each: owing $8, gaining 6 yards, 3 floors below ground.',
    back: '−8, 6 and −3',
    steps: ['Owing money is negative: −8.', 'Gaining is positive: 6.', 'Below ground is negative: −3.'],
    after: [5],
  },
  {
    n: 9, type: 'misconception', difficulty: 5,
    front: 'True or False: Zero is a negative number.',
    back: 'False. Zero is neither positive nor negative. It is the point that separates them.',
    after: [1],
  },
  {
    n: 10, type: 'misconception', difficulty: 5,
    front: 'True or False: −10 is bigger than −2 because 10 is bigger than 2.',
    back: 'False. −10 is farther left on the number line, so it is smaller. Think temperature: −10 ° is colder than −2 °.',
    commonMistake: 'Ignoring the minus sign when comparing.',
    after: [1],
  },
  {
    n: 11, type: 'real-life', difficulty: 3,
    front: 'It was 3 °C in the morning and −2 °C at night. When was it colder?',
    back: 'At night. −2 °C is below zero, and 3 °C is above zero.',
    after: [5],
  },
  {
    n: 12, type: 'challenge', difficulty: 4,
    front: 'What is the opposite of the opposite of −6?',
    back: '−6',
    steps: ['The opposite of −6 is 6.', 'The opposite of 6 is −6.'],
    after: [6],
  },
  {
    n: 13, type: 'challenge', difficulty: 4,
    front: 'In a building, the ground floor is 0 and the parking levels are −1, −2 and −3. You start on floor 4 and go down 6 floors. Where are you?',
    back: 'Floor −2 (the second parking level)',
    steps: ['From 4, going down 4 floors reaches 0.', '2 more floors down reaches −2.'],
    answerVisual: { kind: 'integer-line', min: -4, max: 6, start: 4, jumps: [{ by: -6, label: 'down 6' }] },
    after: [7],
  },
]);
