import { defineCards } from '@/content/defineCards';

export const intMixedCards = defineCards('int-mixed', ['integers', 'order-of-operations'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'How do you solve problems that mix several integer operations?',
    back: 'Use the order of operations (parentheses, then × and ÷, then + and −) and apply the right sign rule at each step.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'How can you tell the sign when you multiply many negative numbers?',
    back: 'Count the negative factors. An even count gives a positive answer; an odd count gives a negative answer.',
    example: '(−1) × (−2) × (−3) → 3 negatives (odd) → −6',
    memoryHook: 'Count the negatives: even → positive, odd → negative.',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'What is a smart way to add and subtract a long chain of integers?',
    back: 'Rewrite every subtraction as adding the opposite, then add from left to right.',
    example: '5 − 8 + (−2) − (−6) = 5 + (−8) + (−2) + 6 = 1',
    after: [1],
  },
  {
    n: 4, type: 'visual', difficulty: 1,
    front: 'Follow the jumps for 5 − 8 + 6. Where do you land?',
    back: '3',
    explanation: 'From 5, jump 8 left to −3, then 6 right to 3.',
    visual: { kind: 'integer-line', min: -5, max: 8, start: 5, jumps: [{ by: -8, label: '− 8' }, { by: 6, label: '+ 6' }], showEnd: false },
    answerVisual: { kind: 'integer-line', min: -5, max: 8, start: 5, jumps: [{ by: -8, label: '− 8' }, { by: 6, label: '+ 6' }] },
    after: [3],
  },
  {
    n: 5, type: 'solve', difficulty: 1,
    front: '−3 + 4 × (−2) = ?',
    back: '−11',
    steps: ['Multiply first: 4 × (−2) = −8.', 'Then add: −3 + (−8) = −11.'],
    after: [1],
  },
  {
    n: 6, type: 'solve', difficulty: 2,
    front: '(−6 + 2) × 3 = ?',
    back: '−12',
    steps: ['Parentheses: −6 + 2 = −4.', '−4 × 3 = −12.'],
    after: [5],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: '−20 ÷ (−4) − 7 = ?',
    back: '−2',
    steps: ['Divide first: −20 ÷ (−4) = 5.', '5 − 7 = −2.'],
    after: [6],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: '(−2) × (−3) × (−1) × 4 = ?',
    back: '−24',
    steps: ['Three negative factors (odd) → the answer is negative.', '2 × 3 × 1 × 4 = 24.', 'So −24.'],
    after: [2],
  },
  {
    n: 9, type: 'solve', difficulty: 3,
    front: '12 − (−3) × 2 = ?',
    back: '18',
    steps: ['Multiply first: (−3) × 2 = −6.', '12 − (−6) = 12 + 6 = 18.'],
    after: [6],
  },
  {
    n: 10, type: 'solve', difficulty: 4,
    front: '[−8 + (−4)] ÷ (−3) + 5 = ?',
    back: '9',
    steps: ['Brackets: −8 + (−4) = −12.', 'Divide: −12 ÷ (−3) = 4.', 'Add: 4 + 5 = 9.'],
    after: [7],
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'Sam works out −3 + 4 × (−2) from left to right: (−3 + 4) × (−2) = −2. What is the correct answer?',
    back: '−11. Multiply first: 4 × (−2) = −8, then −3 + (−8) = −11.',
    commonMistake: 'Forgetting the order of operations when there are negatives.',
    after: [5],
  },
  {
    n: 12, type: 'misconception', difficulty: 5,
    front: 'True or False: (−1) × (−1) × (−1) = 1, because negatives cancel out in pairs.',
    back: 'False. Two of them make 1, but the third makes it −1. Three negative factors (odd) give a negative answer.',
    after: [2],
  },
  {
    n: 13, type: 'real-life', difficulty: 3,
    front: 'A stock price drops $3 a day for 4 days, then rises $5. What is the total change?',
    back: '−7 (it fell $7 overall)',
    steps: ['4 × (−3) = −12.', '−12 + 5 = −7.'],
    after: [6],
  },
  {
    n: 14, type: 'real-life', difficulty: 3,
    front: 'In a quiz, each wrong answer scores −2 and each right answer scores 4. Mo gets 3 wrong and 5 right. What is the score?',
    back: '14 points',
    steps: ['Wrong: 3 × (−2) = −6.', 'Right: 5 × 4 = 20.', 'Total: −6 + 20 = 14.'],
    after: [6],
  },
  {
    n: 15, type: 'challenge', difficulty: 4,
    front: 'Use −2, 3 and −4 once each, with one × and one +, to make the largest result you can.',
    back: '(−2) × (−4) + 3 = 11',
    steps: ['Multiplying the two negatives gives a positive: (−2) × (−4) = 8.', 'Then add the 3: 11.', 'Other choices are smaller, like 3 × (−4) + (−2) = −14.'],
    after: [8],
  },
  {
    n: 16, type: 'challenge', difficulty: 4,
    front: 'Find the missing number: −3 × ___ + 4 = −11',
    back: '5',
    steps: ['Undo + 4: −11 − 4 = −15.', 'Undo × (−3): −15 ÷ (−3) = 5.', 'CHECK: −3 × 5 + 4 = −15 + 4 = −11 ✓'],
    after: [10],
  },
]);
