import { defineCards } from '@/content/defineCards';

export const intMultiplyCards = defineCards('int-multiply', ['integers', 'multiplication', 'sign-rules'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What does 3 × (−2) mean?',
    back: '3 groups of −2: (−2) + (−2) + (−2) = −6.',
    memoryHook: 'Same signs → positive. Different signs → negative.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'What is the sign rule for multiplying two integers?',
    back: 'Same signs → positive answer.\nDifferent signs → negative answer.\nMultiply the sizes as usual.',
    example: '4 × 5 = 20    −4 × (−5) = 20    −4 × 5 = −20',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'Why is a negative times a negative positive?',
    back: 'Follow the pattern: 3 × (−2) = −6, 2 × (−2) = −4, 1 × (−2) = −2, 0 × (−2) = 0. Each answer goes up by 2, so −1 × (−2) = 2 and −2 × (−2) = 4.',
    explanation: 'Another way: −1 × (−2) means “the opposite of −2,” which is 2.',
    after: [2],
  },
  {
    n: 4, type: 'visual', difficulty: 2,
    front: 'Each output goes up by 2. Continue the pattern: what are −1 × (−2) and −2 × (−2)?',
    back: '2 and 4',
    explanation: 'The pattern keeps going past 0, so negative × negative comes out positive.',
    visual: {
      kind: 'math-machine',
      rule: '× (−2)',
      pairs: [
        { input: '3', output: '−6' },
        { input: '2', output: '−4' },
        { input: '1', output: '−2' },
        { input: '0', output: '0' },
        { input: '−1', output: '?' },
        { input: '−2', output: '?' },
      ],
    },
    answerVisual: {
      kind: 'math-machine',
      rule: '× (−2)',
      pairs: [
        { input: '3', output: '−6' },
        { input: '2', output: '−4' },
        { input: '1', output: '−2' },
        { input: '0', output: '0' },
        { input: '−1', output: '2' },
        { input: '−2', output: '4' },
      ],
    },
    after: [3],
  },
  {
    n: 5, type: 'visual', difficulty: 1,
    front: 'Make three jumps of −2, starting at 0. Where do you land? What is 3 × (−2)?',
    back: '−6, so 3 × (−2) = −6.',
    visual: { kind: 'integer-line', min: -8, max: 2, start: 0, jumps: [{ by: -2 }, { by: -2 }, { by: -2 }], showEnd: false },
    answerVisual: { kind: 'integer-line', min: -8, max: 2, start: 0, jumps: [{ by: -2 }, { by: -2 }, { by: -2 }] },
    after: [1],
  },
  {
    n: 6, type: 'solve', difficulty: 1,
    front: '4 × (−3) = ?',
    back: '−12',
    steps: ['4 × 3 = 12.', 'Different signs → negative: −12.'],
    after: [2],
  },
  {
    n: 7, type: 'solve', difficulty: 2,
    front: '−5 × 6 = ?',
    back: '−30',
    steps: ['5 × 6 = 30.', 'Different signs → negative: −30.'],
    after: [6],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: '−7 × (−8) = ?',
    back: '56',
    steps: ['7 × 8 = 56.', 'Same signs → positive: 56.'],
    after: [3],
  },
  {
    n: 9, type: 'solve', difficulty: 3,
    front: '−9 × 0 = ?',
    back: '0',
    explanation: 'Anything times 0 is 0. Zero has no sign.',
    after: [6],
  },
  {
    n: 10, type: 'solve', difficulty: 3,
    front: '−2 × (−3) × (−4) = ?',
    back: '−24',
    steps: ['−2 × (−3) = 6 (same signs).', '6 × (−4) = −24 (different signs).'],
    after: [8],
  },
  {
    n: 11, type: 'solve', difficulty: 4,
    front: '−12 × (−15) = ?',
    back: '180',
    steps: ['12 × 15 = 120 + 60 = 180.', 'Same signs → positive: 180.'],
    after: [8],
  },
  {
    n: 12, type: 'misconception', difficulty: 5,
    front: 'True or False: −3 × (−4) = −12, because both numbers are negative.',
    back: 'False. Same signs give a positive answer: −3 × (−4) = 12.',
    after: [3],
  },
  {
    n: 13, type: 'misconception', difficulty: 5,
    front: 'Ana says −2 × (−3) = −6, “because when you add two negatives, the answer is negative.” What is wrong?',
    back: 'She used the ADDING rule. For multiplying, two negatives make a positive: −2 × (−3) = 6.',
    commonMistake: 'Mixing up the addition and multiplication sign rules.',
    explanation: 'Adding: −2 + (−3) = −5. Multiplying: −2 × (−3) = 6.',
    after: [8],
  },
  {
    n: 14, type: 'real-life', difficulty: 3,
    front: 'A tank loses 4 liters of water every hour. Write the change after 5 hours as an integer.',
    back: '−20 liters',
    steps: ['Each hour: −4.', '5 × (−4) = −20.'],
    after: [7],
  },
  {
    n: 15, type: 'real-life', difficulty: 3,
    front: 'You owe $6 to each of 3 friends. What is your total balance as an integer?',
    back: '−18 (you owe $18).',
    steps: ['3 × (−6) = −18.'],
    after: [7],
  },
  {
    n: 16, type: 'challenge', difficulty: 4,
    front: 'Without multiplying, is (−1) × (−1) × (−1) × (−1) × (−1) positive or negative?',
    back: 'Negative. There are 5 negative factors, an odd number.',
    explanation: 'Each pair of negatives makes a positive. With an odd count, one negative is left over.',
    after: [10],
  },
  {
    n: 17, type: 'challenge', difficulty: 4,
    front: 'Find two integers whose product is −12 and whose sum is 1.',
    back: '4 and −3',
    steps: ['4 × (−3) = −12 ✓', '4 + (−3) = 1 ✓'],
    hint: 'The product is negative, so one number is negative and one is positive.',
    after: [10],
  },
]);
