import { defineCards } from '@/content/defineCards';

export const intSubtractCards = defineCards('int-subtract', ['integers', 'subtraction'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'How can you think about subtracting integers?',
    back: 'Subtracting a number is the same as adding its opposite.',
    example: '5 − 8 = 5 + (−8) = −3',
    memoryHook: 'Keep, change, change.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'What does “keep, change, change” mean?',
    back: 'Keep the first number. Change the minus to a plus. Change the second number to its opposite. Then use the adding rules.',
    example: '−4 − 6 → −4 + (−6) = −10',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'What happens when you subtract a negative number?',
    back: 'It becomes adding a positive, so the answer goes UP. Taking away a debt makes you richer.',
    example: '3 − (−4) = 3 + 4 = 7',
    after: [2],
  },
  {
    n: 4, type: 'visual', difficulty: 1,
    front: '2 − 5 is the same as 2 + (−5). Start at 2 and follow the jump. Where do you land?',
    back: '−3, so 2 − 5 = −3.',
    visual: { kind: 'integer-line', min: -5, max: 5, start: 2, jumps: [{ by: -5, label: '+ (−5)' }], showEnd: false },
    answerVisual: { kind: 'integer-line', min: -5, max: 5, start: 2, jumps: [{ by: -5, label: '+ (−5)' }] },
    after: [1],
  },
  {
    n: 5, type: 'visual', difficulty: 2,
    front: '3 − (−4) is the same as 3 + 4. Start at 3 and follow the jump. Where do you land?',
    back: '7, so 3 − (−4) = 7.',
    visual: { kind: 'integer-line', min: -2, max: 8, start: 3, jumps: [{ by: 4, label: '− (−4) = + 4' }], showEnd: false },
    answerVisual: { kind: 'integer-line', min: -2, max: 8, start: 3, jumps: [{ by: 4, label: '− (−4) = + 4' }] },
    after: [3],
  },
  {
    n: 6, type: 'solve', difficulty: 1,
    front: '3 − 7 = ?',
    back: '−4',
    steps: ['3 − 7 = 3 + (−7).', 'Sizes: 7 − 3 = 4, and 7 is bigger and negative → −4.'],
    after: [2],
  },
  {
    n: 7, type: 'solve', difficulty: 2,
    front: '−4 − 6 = ?',
    back: '−10',
    steps: ['−4 − 6 = −4 + (−6).', 'Same signs: 4 + 6 = 10 → −10.'],
    after: [6],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: '5 − (−3) = ?',
    back: '8',
    steps: ['Keep, change, change: 5 + 3.', '5 + 3 = 8.'],
    after: [3],
  },
  {
    n: 9, type: 'solve', difficulty: 3,
    front: '−2 − (−9) = ?',
    back: '7',
    steps: ['−2 − (−9) = −2 + 9.', 'Sizes: 9 − 2 = 7, and 9 is bigger and positive → 7.'],
    after: [8],
  },
  {
    n: 10, type: 'solve', difficulty: 3,
    front: '−10 − (−4) = ?',
    back: '−6',
    steps: ['−10 − (−4) = −10 + 4.', 'Sizes: 10 − 4 = 6, and 10 is bigger and negative → −6.'],
    after: [8],
  },
  {
    n: 11, type: 'solve', difficulty: 4,
    front: '14 − 30 − (−6) = ?',
    back: '−10',
    steps: ['14 − 30 = −16.', '−16 − (−6) = −16 + 6 = −10.'],
    after: [9],
  },
  {
    n: 12, type: 'misconception', difficulty: 5,
    front: 'Mia says 5 − (−3) = 2. What is wrong?',
    back: 'Subtracting a negative means adding: 5 − (−3) = 5 + 3 = 8.',
    commonMistake: 'Ignoring the negative sign on the number being subtracted.',
    after: [8],
  },
  {
    n: 13, type: 'misconception', difficulty: 5,
    front: 'True or False: 3 − 7 gives the same answer as 7 − 3.',
    back: 'False. 3 − 7 = −4 but 7 − 3 = 4. Order matters in subtraction.',
    after: [6],
  },
  {
    n: 14, type: 'real-life', difficulty: 3,
    front: 'The temperature went from −3 ° to 8 °. How many degrees warmer did it get?',
    back: '11 degrees',
    steps: ['Change = new − old = 8 − (−3).', '8 + 3 = 11.'],
    after: [8],
  },
  {
    n: 15, type: 'real-life', difficulty: 3,
    front: 'A mountain top is at 4,000 m and a valley floor is at −400 m (below sea level). How much higher is the mountain top?',
    back: '4,400 m',
    steps: ['4,000 − (−400) = 4,000 + 400.', '= 4,400.'],
    after: [8],
  },
  {
    n: 16, type: 'challenge', difficulty: 4,
    front: 'What number can you subtract from −5 to get 3? (−5 − ___ = 3)',
    back: '−8',
    steps: ['Try −8: −5 − (−8) = −5 + 8 = 3 ✓'],
    hint: 'Subtracting a negative makes the answer go up.',
    after: [9],
  },
  {
    n: 17, type: 'challenge', difficulty: 4,
    front: 'How far apart are −7 and 6 on a number line?',
    back: '13',
    steps: ['Distance = bigger − smaller = 6 − (−7).', '6 + 7 = 13.', 'Check by counting: 7 steps to 0, then 6 more.'],
    after: [10],
  },
]);
