import { defineCards } from '@/content/defineCards';

export const mrEstimateFirstCards = defineCards('mr-estimate-first', ['math-reasoning', 'estimation'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'Why should you estimate before you solve?',
    back: 'An estimate gives you a “ballpark” answer. Later you can compare your exact answer with it to catch mistakes.',
    memoryHook: 'Estimate = a safety net.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'How do you make an estimate?',
    back: 'Round the numbers to friendly numbers (tens, hundreds, or numbers that are easy to compute) and do the math in your head.',
    example: '38 × 52 → 40 × 50 = 2,000',
    after: [1],
  },
  {
    n: 3, type: 'visual', difficulty: 2,
    front: 'Round each number to the nearest ten and estimate 38 + 52 + 19.',
    back: '40 + 50 + 20 = 110 (the exact sum is 109)',
    explanation: 'On the number line, each number moves to its closest ten.',
    visual: { kind: 'rounding-line', min: 30, max: 40, step: 10, value: 38, roundsTo: 40, showMidpoint: true },
    after: [2],
  },
  {
    n: 4, type: 'solve', difficulty: 1,
    front: 'Estimate 49 + 31.',
    back: 'About 80',
    steps: ['49 ≈ 50 and 31 ≈ 30.', '50 + 30 = 80'],
    after: [2],
  },
  {
    n: 5, type: 'solve', difficulty: 2,
    front: 'Estimate 612 − 189.',
    back: 'About 400',
    steps: ['612 ≈ 600 and 189 ≈ 200.', '600 − 200 = 400'],
    after: [2],
  },
  {
    n: 6, type: 'solve', difficulty: 3,
    front: 'Estimate 28 × 41.',
    back: 'About 1,200',
    steps: ['28 ≈ 30 and 41 ≈ 40.', '30 × 40 = 1,200'],
    after: [2],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: 'Estimate 4,185 ÷ 9 using a nearby number that divides easily.',
    back: 'About 500',
    hint: 'Which number near 4,185 is easy to divide by 9?',
    steps: ['4,185 is close to 4,500.', '4,500 ÷ 9 = 500'],
    after: [2],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'Estimate 7.9 × 3.1.',
    back: 'About 24',
    steps: ['7.9 ≈ 8 and 3.1 ≈ 3.', '8 × 3 = 24'],
    after: [6],
  },
  {
    n: 9, type: 'misconception', difficulty: 5,
    front: 'True or False: An estimate must be exactly equal to the answer.',
    back: 'False. An estimate is close to the answer — good enough to check whether the exact answer is reasonable.',
    after: [2],
  },
  {
    n: 10, type: 'misconception', difficulty: 5,
    front: 'True or False: You should always round up when you estimate.',
    back: 'False. Round to the nearest friendly number. Only round up when you need to make sure you have ENOUGH (like buying supplies).',
    after: [2],
  },
  {
    n: 11, type: 'real-life', difficulty: 3,
    front: 'Gum costs $1.95 a pack. About how much do 4 packs cost?',
    back: 'About $8',
    steps: ['$1.95 ≈ $2.', '4 × 2 = 8'],
    after: [6],
  },
  {
    n: 12, type: 'challenge', difficulty: 4,
    front: 'Without calculating exactly, is 38 × 52 closer to 200, 2,000 or 20,000?',
    back: '2,000',
    steps: ['38 ≈ 40 and 52 ≈ 50.', '40 × 50 = 2,000', 'The exact answer is 1,976.'],
    after: [6],
  },
  {
    n: 13, type: 'challenge', difficulty: 4,
    front: 'Items cost $12.80, $19.95, $14.25 and $6.10. Is $50 enough? Estimate first, then check.',
    back: 'No. Estimate: 13 + 20 + 14 + 6 = 53. Exact: $53.10, so $50 is not enough.',
    steps: ['Round each to the nearest dollar: 13, 20, 14, 6.', 'Estimate: 53', 'Exact: 12.80 + 19.95 + 14.25 + 6.10 = 53.10'],
    after: [5, 11],
  },
]);
