import { defineCards } from '@/content/defineCards';

export const wpDecimalsCards = defineCards('wp-decimals', ['word-problems', 'decimals'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'How are decimal word problems like whole-number word problems?',
    back: 'The thinking and the operations are the same. The only extra care is lining up decimal points and checking the size of the answer.',
    memoryHook: 'Same story, smaller pieces.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'How do you add or subtract decimals in a story problem?',
    back: 'Line up the decimal points, add zeros as placeholders if needed, then add or subtract as with whole numbers.',
    example: '12.5 − 4.75 → 12.50 − 4.75 = 7.75',
    memoryHook: 'Line up the decimal points like buttons on a shirt.',
    after: [1],
  },
  {
    n: 3, type: 'visual', difficulty: 1,
    front: 'Two ribbons are 2.4 m and 1.5 m long. Together, how long are they? Read the model.',
    back: '3.9 meters',
    explanation: 'Two parts make a whole → add: 2.4 + 1.5 = 3.9.',
    visual: {
      kind: 'bar-model',
      total: '?',
      bars: [{ segments: [{ label: '2.4 m', size: 2.4 }, { label: '1.5 m', size: 1.5, tone: 'empty' }] }],
    },
    after: [2],
  },
  {
    n: 4, type: 'solve', difficulty: 1,
    front: 'A pencil is 7.5 cm long. An eraser is 2.3 cm long. What is their combined length?',
    back: '9.8 cm',
    steps: ['7.5 + 2.3 = 9.8'],
    after: [2],
  },
  {
    n: 5, type: 'solve', difficulty: 2,
    front: 'Jo has 12.5 liters of water. He pours out 4.75 liters. How much is left?',
    back: '7.75 liters',
    steps: ['Write 12.5 as 12.50 so the places match.', '12.50 − 4.75 = 7.75', 'CHECK: 7.75 + 4.75 = 12.50 ✓'],
    after: [2],
  },
  {
    n: 6, type: 'solve', difficulty: 3,
    front: 'A runner ran 3.45 km on Monday and 4.8 km on Tuesday. How far did the runner go in all?',
    back: '8.25 km',
    steps: ['Write 4.8 as 4.80.', '3.45 + 4.80 = 8.25'],
    after: [5],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: 'One notebook weighs 0.35 kg. How much do 6 notebooks weigh?',
    back: '2.1 kg',
    steps: ['6 equal groups → multiply.', '35 hundredths × 6 = 210 hundredths', '2.10 = 2.1 kg', 'CHECK: about 0.4 × 6 = 2.4 ✓'],
    after: [2],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'A 4.8 m ribbon is cut into 6 equal pieces. How long is each piece?',
    back: '0.8 m',
    steps: ['Equal sharing → divide.', '4.8 ÷ 6 = 0.8', 'CHECK: 6 × 0.8 = 4.8 ✓'],
    after: [7],
  },
  {
    n: 9, type: 'misconception', difficulty: 5,
    front: 'True or False: To add 6.4 + 2.35 you can line the numbers up on the right edge, like whole numbers.',
    back: 'False. Line up the decimal points: 6.40 + 2.35 = 8.75.',
    commonMistake: 'Aligning the last digits instead of the decimal points.',
    after: [2],
  },
  {
    n: 10, type: 'misconception', difficulty: 5,
    front: 'True or False: Multiplying always makes a number bigger, so 8 × 0.5 is more than 8.',
    back: 'False. 8 × 0.5 = 4. It means “half of 8.”',
    explanation: 'Multiplying by a number less than 1 takes only a part of the amount, so the answer gets smaller.',
    memoryHook: '× 0.5 is half of it.',
    after: [7],
  },
  {
    n: 11, type: 'real-life', difficulty: 3,
    front: 'Three friends share a $14.40 pizza bill equally. How much does each friend pay?',
    back: '$4.80',
    steps: ['Equal sharing → divide.', '14.40 ÷ 3 = 4.80', 'CHECK: 3 × 4.80 = 14.40 ✓'],
    after: [8],
  },
  {
    n: 12, type: 'challenge', difficulty: 4,
    front: 'A trip has three parts: 12.6 km to school, 8.45 km to the park, and 6.9 km home. How far is the whole trip? How much longer is the school part than the home part?',
    back: 'Whole trip: 27.95 km. School part is 5.7 km longer.',
    steps: ['12.60 + 8.45 + 6.90 = 27.95', '12.6 − 6.9 = 5.7'],
    after: [6],
  },
  {
    n: 13, type: 'challenge', difficulty: 4,
    front: 'Estimate first, then solve: 3.9 × 2.1. Is your exact answer close to your estimate?',
    back: 'Estimate: 4 × 2 = 8. Exact: 8.19. They are close, so the answer is reasonable.',
    steps: ['Round: 3.9 ≈ 4 and 2.1 ≈ 2', 'Estimate: 4 × 2 = 8', 'Exact: 39 × 21 = 819, then two decimal places → 8.19'],
    after: [7],
  },
]);
