import { defineCards } from '@/content/defineCards';

export const wpElapsedTimeCards = defineCards('wp-elapsed-time', ['word-problems', 'time'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What is elapsed time?',
    back: 'The amount of time that passes between a start time and an end time.',
    memoryHook: 'Hop along a clock number line: to the next hour, then on to the end.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'How can you find elapsed time?',
    back: 'Hop from the start to the next whole hour, then hop hours, then hop to the end. Add the hops.',
    explanation: 'There are 60 minutes in an hour and 24 hours in a day. Time is NOT decimal, so don’t subtract like 4.20 − 3.50.',
    after: [1],
  },
  {
    n: 3, type: 'visual', difficulty: 2,
    front: 'A show starts at 2:15 and ends at 4:40. The hops are 2:15 → 3:00, 3:00 → 4:00, 4:00 → 4:40. How long is the show?',
    back: '145 minutes = 2 hours 25 minutes',
    explanation: 'Add the hops: 45 + 60 + 40 = 145 minutes. 145 = 120 + 25.',
    visual: {
      kind: 'bar-model',
      total: '? minutes',
      bars: [{ segments: [{ label: '45', size: 45 }, { label: '60', size: 60, tone: 'empty' }, { label: '40', size: 40 }] }],
    },
    after: [2],
  },
  {
    n: 4, type: 'solve', difficulty: 1,
    front: 'Practice starts at 3:00 and ends at 4:30. How long is practice?',
    back: '1 hour 30 minutes',
    steps: ['3:00 → 4:00 is 1 hour.', '4:00 → 4:30 is 30 minutes.'],
    after: [2],
  },
  {
    n: 5, type: 'solve', difficulty: 2,
    front: 'A movie starts at 6:20 p.m. and ends at 8:05 p.m. How long is the movie?',
    back: '1 hour 45 minutes',
    steps: ['6:20 → 7:00 is 40 minutes.', '7:00 → 8:00 is 1 hour.', '8:00 → 8:05 is 5 minutes.', '40 + 5 = 45 minutes, plus 1 hour.'],
    after: [3],
  },
  {
    n: 6, type: 'solve', difficulty: 3,
    front: 'A flight leaves at 10:35 a.m. and lasts 2 hours 50 minutes. When does it land?',
    back: '1:25 p.m.',
    steps: ['10:35 a.m. + 2 hours = 12:35 p.m.', 'Add 50 minutes: the first 25 minutes reach 1:00 p.m.', 'The other 25 minutes land at 1:25 p.m.'],
    after: [5],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: 'A show starts at 4:50 p.m. and ends at 6:15 p.m. How long is it?',
    back: '1 hour 25 minutes',
    steps: ['4:50 → 5:00 is 10 minutes.', '5:00 → 6:00 is 1 hour.', '6:00 → 6:15 is 15 minutes.', '10 + 15 = 25 minutes, plus 1 hour.'],
    after: [5],
  },
  {
    n: 8, type: 'misconception', difficulty: 5,
    front: 'True or False: From 3:50 to 4:20 is 70 minutes, because 4.20 − 3.50 = 0.70.',
    back: 'False. It is 30 minutes.',
    explanation: '3:50 → 4:00 is 10 minutes, and 4:00 → 4:20 is 20 more.',
    commonMistake: 'Treating time like decimals.',
    after: [2],
  },
  {
    n: 9, type: 'misconception', difficulty: 5,
    front: 'True or False: 1.5 hours is 1 hour 50 minutes.',
    back: 'False. 0.5 hour is half an hour, which is 30 minutes. So 1.5 hours = 1 hour 30 minutes.',
    after: [2],
  },
  {
    n: 10, type: 'real-life', difficulty: 3,
    front: 'School starts at 8:15 a.m. and ends at 3:05 p.m. How long is the school day?',
    back: '6 hours 50 minutes',
    steps: ['8:15 → 9:00 is 45 minutes.', '9:00 a.m. → 3:00 p.m. is 6 hours.', '3:00 → 3:05 is 5 minutes.', '45 + 5 = 50 minutes, plus 6 hours.'],
    after: [5],
  },
  {
    n: 11, type: 'challenge', difficulty: 4,
    front: 'Maya starts homework at 4:45 p.m. Math takes 25 minutes, reading takes 40 minutes, and she takes a 10-minute break. What time does she finish?',
    back: '6:00 p.m.',
    steps: ['Total time: 25 + 40 + 10 = 75 minutes = 1 hour 15 minutes.', '4:45 + 1 hour = 5:45.', '5:45 + 15 min = 6:00 p.m.'],
    after: [6],
  },
  {
    n: 12, type: 'challenge', difficulty: 4,
    front: 'A recipe takes 1 hour 40 minutes and must be ready by 6:00 p.m. What is the latest start time?',
    back: '4:20 p.m.',
    hint: 'Work backwards from 6:00.',
    steps: ['6:00 − 1 hour = 5:00.', '5:00 − 40 minutes = 4:20.', 'CHECK: 4:20 + 1 h 40 min = 6:00 ✓'],
    after: [6],
  },
  {
    n: 13, type: 'challenge', difficulty: 4,
    front: 'A night train leaves at 11:50 p.m. and arrives at 2:25 a.m. the next day. How long is the trip?',
    back: '2 hours 35 minutes',
    steps: ['11:50 p.m. → 12:00 midnight is 10 minutes.', 'Midnight → 2:00 a.m. is 2 hours.', '2:00 → 2:25 is 25 minutes.', '10 + 25 = 35 minutes, plus 2 hours.'],
    after: [7],
  },
]);
