import { defineCards } from '@/content/defineCards';

export const wpFractionsCards = defineCards('wp-fractions', ['word-problems', 'fractions'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What kinds of fraction word problems will you see?',
    back: 'Adding or taking away parts of a whole, finding a fraction of an amount, and sharing into equal pieces.',
    memoryHook: 'Draw the whole first. Then shade the part.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'In a fraction problem, what does “of” usually mean?',
    back: 'Multiply.',
    example: '1/3 of 12 means 1/3 × 12 = 4',
    after: [1],
  },
  {
    n: 3, type: 'visual', difficulty: 1,
    front: 'A chocolate bar is cut into 5 equal parts. 3 parts are eaten. What fraction is eaten? What fraction is left?',
    back: '3/5 is eaten and 2/5 is left.',
    explanation: 'The whole is 5/5. Eaten + left = whole: 3/5 + 2/5 = 5/5.',
    visual: { kind: 'fraction-strip', numerator: 3, denominator: 5 },
    after: [1],
  },
  {
    n: 4, type: 'solve', difficulty: 1,
    front: 'Kai ate 1/4 of a pizza. Zoe ate 2/4 of the same pizza. How much did they eat altogether?',
    back: '3/4 of the pizza',
    steps: ['Same size slices, so add the numerators.', '1/4 + 2/4 = 3/4'],
    after: [1],
  },
  {
    n: 5, type: 'solve', difficulty: 2,
    front: 'A ribbon is 7/8 meter long. 3/8 meter is used. How much is left?',
    back: '1/2 meter',
    steps: ['Taking away → subtract.', '7/8 − 3/8 = 4/8', 'Simplify: 4/8 = 1/2'],
    after: [4],
  },
  {
    n: 6, type: 'solve', difficulty: 3,
    front: 'Maya has 24 stickers. She gives 3/8 of them to a friend. How many stickers does she give away?',
    back: '9 stickers',
    steps: ['“Of” means multiply, but first find 1/8 of 24.', '24 ÷ 8 = 3 stickers in each eighth', '3 eighths: 3 × 3 = 9'],
    after: [2],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: 'Dan walks 1/2 mile to school and 1/3 mile to the park. How far does he walk in all?',
    back: '5/6 mile',
    steps: ['Unlike denominators → find a common one: 6.', '1/2 = 3/6 and 1/3 = 2/6', '3/6 + 2/6 = 5/6'],
    after: [4],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'A recipe uses 2/3 cup of flour. Mia makes half of the recipe. How much flour does she use?',
    back: '1/3 cup',
    steps: ['Half of 2/3 → 1/2 × 2/3', '(1 × 2)/(2 × 3) = 2/6', 'Simplify: 2/6 = 1/3'],
    after: [2],
  },
  {
    n: 9, type: 'solve', difficulty: 4,
    front: 'A board is 5 1/4 feet long. A piece 2 3/4 feet long is cut off. How long is the rest?',
    back: '2 1/2 feet',
    hint: 'You can’t take 3/4 from 1/4. Regroup one whole.',
    steps: ['Regroup: 5 1/4 = 4 5/4', '4 5/4 − 2 3/4 = 2 2/4', 'Simplify: 2 2/4 = 2 1/2'],
    after: [5],
  },
  {
    n: 10, type: 'misconception', difficulty: 5,
    front: 'Tom says 1/2 + 1/3 = 2/5 of a pizza. How can you tell his answer is unreasonable?',
    back: '1/2 + 1/3 is MORE than 1/2, but 2/5 is less than 1/2. The correct sum is 5/6.',
    commonMistake: 'Adding numerators and denominators.',
    explanation: 'Adding to a number should never make it smaller.',
    after: [7],
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'True or False: “1/4 of 20” means 20 ÷ 1/4 = 80.',
    back: 'False. 1/4 of 20 = 5 — a fraction OF something is part of it, so the answer is smaller than 20.',
    memoryHook: 'A part is smaller than the whole.',
    after: [6],
  },
  {
    n: 12, type: 'real-life', difficulty: 3,
    front: 'A class has 28 students. 3/4 of them ride the bus. How many students ride the bus?',
    back: '21 students',
    steps: ['1/4 of 28 = 28 ÷ 4 = 7', '3/4 = 3 × 7 = 21', 'CHECK: 21 is less than 28 ✓'],
    after: [6],
  },
  {
    n: 13, type: 'challenge', difficulty: 4,
    front: 'Lena reads 2/5 of a book on Friday and 1/5 on Saturday. What fraction is left? The book has 150 pages. How many pages are left?',
    back: '2/5 is left, which is 60 pages.',
    steps: ['Read: 2/5 + 1/5 = 3/5', 'Left: 5/5 − 3/5 = 2/5', '150 ÷ 5 = 30 pages in each fifth', '2 × 30 = 60 pages'],
    after: [6, 7],
  },
  {
    n: 14, type: 'challenge', difficulty: 4,
    front: 'Of the cookies Ali baked, 1/2 were chocolate chip and 1/4 were oatmeal. The rest were peanut butter. He baked 48 cookies. How many were peanut butter?',
    back: '12 cookies',
    steps: ['Chip + oatmeal: 1/2 + 1/4 = 3/4', 'Peanut butter: 1 − 3/4 = 1/4', '1/4 of 48 = 12'],
    after: [12],
  },
]);
