import { defineCards } from '@/content/defineCards';

export const wpMeasurementCards = defineCards('wp-measurement', ['word-problems', 'measurement'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What do measurement word problems ask you to do?',
    back: 'Add, subtract, compare or share lengths, weights and amounts — often after changing everything to the same unit.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'What must be true before you add, subtract or compare measurements?',
    back: 'They must be in the same unit. Convert first.',
    example: '2 m + 35 cm → 200 cm + 35 cm = 235 cm',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'Which operation do you use to convert units?',
    back: 'Big unit → small unit: multiply (you need more of them).\nSmall unit → big unit: divide.',
    example: '3 ft = 3 × 12 = 36 in\n500 cm = 500 ÷ 100 = 5 m',
    memoryHook: 'Fewer big units, more small units.',
    after: [2],
  },
  {
    n: 4, type: 'solve', difficulty: 1,
    front: 'A rope is 3 yards long. How many feet is that?',
    back: '9 feet',
    steps: ['Yard is bigger than foot → multiply.', '1 yard = 3 feet, so 3 × 3 = 9.'],
    after: [3],
  },
  {
    n: 5, type: 'solve', difficulty: 2,
    front: 'A juice bottle holds 2 liters. How many milliliters is that?',
    back: '2,000 milliliters',
    steps: ['Liter is bigger than milliliter → multiply.', '1 L = 1,000 mL, so 2 × 1,000 = 2,000.'],
    after: [3],
  },
  {
    n: 6, type: 'solve', difficulty: 3,
    front: 'One board is 2 m 35 cm long and another is 1 m 80 cm long. How long are they together?',
    back: '4 m 15 cm',
    steps: ['Convert to centimeters: 235 cm + 180 cm = 415 cm.', '415 cm = 4 m 15 cm.'],
    after: [2],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: 'A pitcher holds 2 quarts of water. How many cups is that?',
    back: '8 cups',
    steps: ['Quart is bigger than cup → multiply.', '1 quart = 4 cups, so 2 × 4 = 8.'],
    after: [3],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'A package weighs 2 lb 6 oz. A 10 oz gift is added. How much does it weigh now?',
    back: '3 lb',
    steps: ['Add the ounces: 6 + 10 = 16 oz.', '16 oz = 1 lb (16 ounces make a pound).', '2 lb + 1 lb = 3 lb.'],
    after: [2],
  },
  {
    n: 9, type: 'misconception', difficulty: 5,
    front: 'True or False: 5 km + 300 m = 305 km.',
    back: 'False. The units differ. 5 km = 5,000 m, so the sum is 5,300 m (or 5.3 km).',
    commonMistake: 'Adding numbers with different units.',
    after: [2],
  },
  {
    n: 10, type: 'misconception', difficulty: 5,
    front: 'True or False: To change 4 feet to inches you divide by 12, because inches are smaller.',
    back: 'False. Multiply: 4 × 12 = 48 inches.',
    explanation: 'Smaller units fit more times, so you need MORE of them.',
    after: [3],
  },
  {
    n: 11, type: 'real-life', difficulty: 3,
    front: 'Ava is 4 ft 8 in tall. Her sister is 52 inches tall. Who is taller, and by how much?',
    back: 'Ava, by 4 inches.',
    steps: ['4 ft 8 in = 4 × 12 + 8 = 56 inches.', '56 − 52 = 4 inches.'],
    after: [3],
  },
  {
    n: 12, type: 'challenge', difficulty: 4,
    front: 'A water cooler holds 5 gallons. How many 1-quart bottles can be filled from it?',
    back: '20 bottles',
    steps: ['1 gallon = 4 quarts.', '5 × 4 = 20 quarts.', 'One bottle per quart → 20 bottles.'],
    after: [7],
  },
  {
    n: 13, type: 'challenge', difficulty: 4,
    front: 'A ribbon is 3.5 m long. It is cut into pieces that are 25 cm long. How many pieces are there?',
    back: '14 pieces',
    steps: ['Same unit first: 3.5 m = 350 cm.', '350 ÷ 25 = 14.', 'CHECK: 14 × 25 = 350 ✓'],
    after: [6],
  },
]);
