import { defineCards } from '@/content/defineCards';

export const wpMoneyCards = defineCards('wp-money', ['word-problems', 'money', 'decimals'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'Why are money problems really decimal problems?',
    back: 'Dollars and cents are tenths and hundredths of a dollar: $3.25 is 3 dollars and 25 hundredths of a dollar.',
    memoryHook: 'A dollar is the whole; cents are the hundredths.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'How should you write money amounts when you calculate?',
    back: 'Always use two decimal places ($4.50, not $4.5) and line up the decimal points.',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'How do you find change?',
    back: 'Change = amount paid − total cost.',
    example: 'Paid $20 for a $13.65 toy → 20.00 − 13.65 = $6.35',
    memoryHook: 'Or count up from the cost to the amount you paid.',
    after: [2],
  },
  {
    n: 4, type: 'solve', difficulty: 1,
    front: 'A pen costs $1.25. How much do 4 pens cost?',
    back: '$5.00',
    steps: ['4 equal prices → multiply.', '4 × 1.25 = 5.00'],
    after: [2],
  },
  {
    n: 5, type: 'solve', difficulty: 2,
    front: 'Sara buys a book for $8.75 and a card for $3.50. What is the total?',
    back: '$12.25',
    steps: ['8.75 + 3.50 = 12.25'],
    after: [2],
  },
  {
    n: 6, type: 'solve', difficulty: 2,
    front: 'Ben pays with a $20 bill for a $13.65 toy. How much change does he get?',
    back: '$6.35',
    steps: ['20.00 − 13.65 = 6.35', 'CHECK: 13.65 + 6.35 = 20.00 ✓'],
    after: [3],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: '6 tickets cost $52.50 in all. How much does one ticket cost?',
    back: '$8.75',
    steps: ['Equal sharing → divide.', '52.50 ÷ 6 = 8.75', 'CHECK: 6 × 8.75 = 52.50 ✓'],
    after: [4],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'Apples cost $1.80 per pound. How much do 2.5 pounds cost?',
    back: '$4.50',
    steps: ['Price per pound × pounds', '1.80 × 2.5 = 4.50', 'CHECK: about 2 × 2 = 4, a little more ✓'],
    after: [4],
  },
  {
    n: 9, type: 'misconception', difficulty: 5,
    front: 'True or False: $3.5 means 3 dollars and 5 cents.',
    back: 'False. $3.5 is $3.50 — 3 dollars and 50 cents.',
    commonMistake: 'Reading the single digit after the point as cents.',
    memoryHook: 'Money always has two places after the point.',
    after: [2],
  },
  {
    n: 10, type: 'misconception', difficulty: 5,
    front: 'Ana multiplies 3 × $0.60 and writes $18. How can you tell this is unreasonable?',
    back: '3 × $0.60 is about 3 × $0.50 to $1, so near $2. The right answer is $1.80.',
    explanation: 'Three items under a dollar each can’t cost $18.',
    after: [4],
  },
  {
    n: 11, type: 'real-life', difficulty: 3,
    front: 'A class trip has 24 students. Each ticket costs $6.50. What is the total cost?',
    back: '$156.00',
    steps: ['24 × 6.50', '24 × 6 = 144 and 24 × 0.50 = 12', '144 + 12 = 156'],
    after: [4],
  },
  {
    n: 12, type: 'challenge', difficulty: 4,
    front: 'Mia has $50. She buys 3 shirts at $12.99 each. Does she have enough left for a $10.50 hat?',
    back: 'Yes. She spends $49.47 in all and has $0.53 left.',
    steps: ['Shirts: 3 × 12.99 = 38.97', 'Add the hat: 38.97 + 10.50 = 49.47', '50.00 − 49.47 = 0.53'],
    after: [5, 6],
  },
  {
    n: 13, type: 'challenge', difficulty: 4,
    front: 'Which is the better buy: 4 notebooks for $3.80 or 6 notebooks for $5.40?',
    back: '6 for $5.40, because each notebook costs $0.90 instead of $0.95.',
    steps: ['4 for $3.80 → 3.80 ÷ 4 = $0.95 each', '6 for $5.40 → 5.40 ÷ 6 = $0.90 each', 'The lower price per notebook is the better buy.'],
    after: [7],
  },
]);
