import { defineCards } from '@/content/defineCards';

export const wpMultiplyDivideCards = defineCards('wp-multiply-divide', ['word-problems', 'multiplication', 'division'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What kinds of stories use multiplication and division?',
    back: 'Equal groups, arrays (rows and columns), and “times as many” comparisons.',
    memoryHook: 'Division asks: how many groups? or how many in each group?',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'In an equal-groups story, how are groups, group size and total connected?',
    back: 'Groups × size = total.\nTotal ÷ groups = size of each group.\nTotal ÷ size = number of groups.',
    example: '5 boxes × 8 muffins = 40 muffins; 40 ÷ 5 = 8; 40 ÷ 8 = 5',
    after: [1],
  },
  {
    n: 3, type: 'visual', difficulty: 1,
    front: '5 boxes hold 8 muffins each. What is the total? Read the model.',
    back: '40 muffins (5 × 8)',
    explanation: 'Five equal pieces, each worth 8.',
    visual: {
      kind: 'bar-model',
      total: '?',
      bars: [{ segments: Array.from({ length: 5 }, () => ({ label: '8', size: 8 })) }],
    },
    after: [2],
  },
  {
    n: 4, type: 'solve', difficulty: 1,
    front: 'There are 6 rows of 9 chairs. How many chairs are there?',
    back: '54 chairs',
    steps: ['Equal rows → multiply.', '6 × 9 = 54'],
    after: [2],
  },
  {
    n: 5, type: 'solve', difficulty: 2,
    front: '72 stickers are shared equally among 8 children. How many does each child get?',
    back: '9 stickers',
    steps: ['Sharing equally → divide.', '72 ÷ 8 = 9', 'CHECK: 8 × 9 = 72 ✓'],
    after: [2],
  },
  {
    n: 6, type: 'solve', difficulty: 3,
    front: 'A farmer packs 288 eggs in cartons of 12. How many cartons does the farmer fill?',
    back: '24 cartons',
    steps: ['Total 288, group size 12, find the number of groups.', '288 ÷ 12 = 24', 'CHECK: 12 × 24 = 288 ✓'],
    after: [5],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: 'A school orders 36 boxes with 24 markers in each box. How many markers is that?',
    back: '864 markers',
    steps: ['36 groups of 24 → multiply.', '36 × 24 = 720 + 144 = 864', 'CHECK: about 40 × 20 = 800 ✓'],
    after: [4],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'A rope is 175 cm long. It is cut into pieces 25 cm long. How many pieces are there?',
    back: '7 pieces',
    steps: ['How many 25s fit in 175? → divide.', '175 ÷ 25 = 7', 'CHECK: 25 × 7 = 175 ✓'],
    after: [5],
  },
  {
    n: 9, type: 'misconception', difficulty: 5,
    front: 'Ray has 6 marbles. Kim has 4 times as many. Ray adds 6 + 4 = 10. What is wrong?',
    back: '“4 times as many” means multiply: 6 × 4 = 24 marbles.',
    commonMistake: 'Adding for “times as many.”',
    after: [2],
  },
  {
    n: 10, type: 'misconception', difficulty: 5,
    front: 'True or False: You always divide the bigger number by the smaller one, so sharing 5 cookies among 20 kids is 20 ÷ 5.',
    back: 'False. Each kid gets 5 ÷ 20 = 1/4 of a cookie.',
    explanation: 'Start with what is being shared (the total). A small total shared among many people gives each person a fraction.',
    after: [5],
  },
  {
    n: 11, type: 'real-life', difficulty: 3,
    front: 'A theater has 28 rows with 32 seats in each row. How many seats are there in all?',
    back: '896 seats',
    steps: ['28 equal rows → multiply.', '28 × 32 = 28 × 30 + 28 × 2 = 840 + 56 = 896'],
    after: [7],
  },
  {
    n: 12, type: 'challenge', difficulty: 4,
    front: 'A baker makes 9 trays of 24 rolls. She packs the rolls into bags of 6. How many bags does she fill?',
    back: '36 bags',
    steps: ['Total rolls: 9 × 24 = 216', 'Bags: 216 ÷ 6 = 36', 'CHECK: 36 × 6 = 216 ✓'],
    after: [6, 7],
  },
  {
    n: 13, type: 'challenge', difficulty: 4,
    front: '85 students are going on a trip. Each bus holds 30 students. How many buses are needed?',
    back: '3 buses',
    hint: 'What happens to the leftover students?',
    steps: ['85 ÷ 30 = 2 with 25 left over.', 'The 25 leftover students still need a bus.', 'Round UP: 3 buses.'],
    explanation: 'Always think about what the remainder means in the story.',
    after: [8],
  },
]);
