import { defineCards } from '@/content/defineCards';

export const wpVolumeCards = defineCards('wp-volume', ['word-problems', 'volume'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What do volume word problems ask?',
    back: 'How much space a solid takes up — how many unit cubes fill it — or a missing length when the volume is known.',
    memoryHook: 'Area = the floor. Volume = the whole room.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'What formula finds the volume of a rectangular prism?',
    back: 'V = length × width × height (or base area × height). The answer is in cubic units.',
    example: '4 × 3 × 2 = 24 cubic cm',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'How do you find a missing dimension when you know the volume?',
    back: 'Divide the volume by the other dimensions (or by the base area).',
    example: '60 = 5 × 4 × h → h = 60 ÷ 20 = 3',
    after: [2],
  },
  {
    n: 4, type: 'solve', difficulty: 1,
    front: 'A box is 4 cm long, 3 cm wide and 2 cm tall. What is its volume?',
    back: '24 cubic cm',
    steps: ['V = l × w × h', '4 × 3 × 2 = 24'],
    after: [2],
  },
  {
    n: 5, type: 'solve', difficulty: 2,
    front: 'A fish tank is 10 in long, 6 in wide and 8 in high. What is its volume?',
    back: '480 cubic in',
    steps: ['Base area: 10 × 6 = 60', 'Volume: 60 × 8 = 480'],
    after: [2],
  },
  {
    n: 6, type: 'solve', difficulty: 3,
    front: 'A sandbox is 6 ft long, 4 ft wide and 2 ft deep. How many cubic feet of sand fill it?',
    back: '48 cubic ft',
    steps: ['6 × 4 = 24 (the base)', '24 × 2 = 48'],
    after: [5],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: 'A prism has a volume of 90 cubic cm. Its base is 6 cm by 5 cm. How tall is it?',
    back: '3 cm',
    steps: ['Base area: 6 × 5 = 30', '90 ÷ 30 = 3', 'CHECK: 30 × 3 = 90 ✓'],
    after: [3],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'A cube has sides of 5 inches. What is its volume?',
    back: '125 cubic in',
    steps: ['All sides are equal: 5 × 5 × 5', '25 × 5 = 125'],
    after: [4],
  },
  {
    n: 9, type: 'misconception', difficulty: 5,
    front: 'True or False: A box that is 3 by 4 by 5 has a volume of 3 + 4 + 5 = 12.',
    back: 'False. Volume multiplies: 3 × 4 × 5 = 60.',
    commonMistake: 'Adding the dimensions.',
    after: [2],
  },
  {
    n: 10, type: 'misconception', difficulty: 5,
    front: 'Ben says a box that is 2 m by 3 m by 4 m has a volume of 24 square meters. What is wrong?',
    back: 'Volume is measured in CUBIC units: 24 cubic meters.',
    explanation: 'Square units measure flat area. Cubic units measure the space inside.',
    after: [4],
  },
  {
    n: 11, type: 'real-life', difficulty: 3,
    front: 'A moving box is 2 ft by 2 ft by 3 ft. How many 1-cubic-foot packages fit inside?',
    back: '12 packages',
    steps: ['Volume: 2 × 2 × 3 = 12 cubic ft.', 'Each package takes 1 cubic ft → 12.'],
    after: [4],
  },
  {
    n: 12, type: 'challenge', difficulty: 4,
    front: 'A box is 8 in long, 6 in wide and 4 in tall. How many 2-inch cubes fit inside?',
    back: '24 cubes',
    steps: ['Along the length: 8 ÷ 2 = 4 cubes.', 'Along the width: 6 ÷ 2 = 3 cubes.', 'Along the height: 4 ÷ 2 = 2 cubes.', '4 × 3 × 2 = 24'],
    after: [6],
  },
  {
    n: 13, type: 'challenge', difficulty: 4,
    front: 'A tank is 20 cm long, 10 cm wide and 15 cm tall. It is filled 3/4 full of water. What is the volume of the water?',
    back: '2,250 cubic cm',
    steps: ['Full tank: 20 × 10 × 15 = 3,000 cubic cm.', '3/4 of 3,000: 3,000 ÷ 4 = 750, and 3 × 750 = 2,250.'],
    after: [6, 8],
  },
]);
