import { defineCards } from '@/content/defineCards';

export const div4Digit1DigitCards = defineCards('div-4digit-1digit', ['division', 'long-division'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What changes when you divide a 4-digit number by a 1-digit number?',
    back: 'Nothing about the steps — you just repeat Divide → Multiply → Subtract → Bring Down more times.',
    memoryHook: 'Divide → Multiply → Subtract → Bring Down → Repeat',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'How can you tell how many digits the quotient will have?',
    back: 'If the first digit of the dividend is at least as big as the divisor, the quotient has as many digits as the dividend. If it’s smaller, the quotient has one fewer.',
    example: '8,424 ÷ 4 has 4 digits (8 ≥ 4). 3,150 ÷ 6 has 3 digits (3 < 6).',
    after: [1],
  },
  {
    n: 3, type: 'visual', difficulty: 2,
    front: 'Follow the work for 8,424 ÷ 4. Where does the 0 in the quotient come from?',
    back: 'After bringing down the 2, 2 ÷ 4 = 0 (4 doesn’t fit), so we write 0 and bring down the next digit. The quotient is 2,106.',
    visual: {
      kind: 'long-division',
      divisor: '4',
      dividend: '8424',
      quotient: '2106',
      steps: [
        { text: '8', endCol: 0, rule: true },
        { text: '4', endCol: 1 },
        { text: '4', endCol: 1, rule: true },
        { text: '2', endCol: 2 },
        { text: '0', endCol: 2, rule: true },
        { text: '24', endCol: 3 },
        { text: '24', endCol: 3, rule: true },
        { text: '0', endCol: 3 },
      ],
    },
    after: [2],
  },
  {
    n: 4, type: 'solve', difficulty: 2,
    front: '2,436 ÷ 3 = ?',
    back: '812',
    steps: ['24 ÷ 3 = 8 → 24 → 0.', 'Bring down 3: 3 ÷ 3 = 1 → 3 → 0.', 'Bring down 6: 6 ÷ 3 = 2 → 6 → 0.', 'Quotient: 812.'],
    after: [2],
  },
  {
    n: 5, type: 'solve', difficulty: 3,
    front: '5,432 ÷ 8 = ?',
    back: '679',
    steps: ['54 ÷ 8 = 6 → 48 → 6.', 'Bring down 3: 63 ÷ 8 = 7 → 56 → 7.', 'Bring down 2: 72 ÷ 8 = 9 → 72 → 0.', 'Quotient: 679.'],
    after: [4],
  },
  {
    n: 6, type: 'solve', difficulty: 3,
    front: '6,309 ÷ 3 = ?',
    back: '2,103',
    hint: 'Watch for places where 3 doesn’t fit. Write a 0.',
    steps: ['6 ÷ 3 = 2 → 6 → 0.', 'Bring down 3: 3 ÷ 3 = 1 → 0.', 'Bring down 0: 0 ÷ 3 = 0 → write 0.', 'Bring down 9: 9 ÷ 3 = 3.', 'Quotient: 2,103.'],
    after: [4],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: '9,000 ÷ 5 = ?',
    back: '1,800',
    steps: ['9 ÷ 5 = 1 → 5 → 4.', 'Bring down 0: 40 ÷ 5 = 8 → 0.', 'Two more zeros bring two more 0s in the quotient.', 'Quotient: 1,800.'],
    after: [4],
  },
  {
    n: 8, type: 'solve', difficulty: 4,
    front: '7,325 ÷ 6 = ?',
    back: '1,220 R 5',
    steps: ['7 ÷ 6 = 1 → 6 → 1.', 'Bring down 3: 13 ÷ 6 = 2 → 12 → 1.', 'Bring down 2: 12 ÷ 6 = 2 → 12 → 0.', 'Bring down 5: 5 ÷ 6 = 0 → remainder 5.', 'CHECK: 1,220 × 6 + 5 = 7,325 ✓'],
    after: [5],
  },
  {
    n: 9, type: 'misconception', difficulty: 5,
    front: 'True or False: 3,150 ÷ 6 has a 4-digit quotient.',
    back: 'False. 3 is less than 6, so start with 31. The quotient, 525, has 3 digits.',
    after: [2],
  },
  {
    n: 10, type: 'misconception', difficulty: 5,
    front: 'Ben says 4,024 ÷ 4 = 16. What did he leave out?',
    back: 'The zeros in the quotient. 4 ÷ 4 = 1, then 0 ÷ 4 = 0, 2 ÷ 4 = 0, and 24 ÷ 4 = 6. The quotient is 1,006.',
    commonMistake: 'Skipping placeholder zeros in the quotient.',
    after: [6],
  },
  {
    n: 11, type: 'real-life', difficulty: 3,
    front: 'A library has 4,872 books on 8 shelves, with the same number on each shelf. How many books are on each shelf?',
    back: '609 books',
    steps: ['48 ÷ 8 = 6 → 48 → 0.', 'Bring down 7: 7 ÷ 8 = 0 → write 0.', 'Bring down 2: 72 ÷ 8 = 9.', 'Quotient: 609.'],
    after: [6],
  },
  {
    n: 12, type: 'challenge', difficulty: 4,
    front: 'A school raises $5,640 and splits it equally among 6 grades. Each grade splits its share equally among 4 classes. How much does each class get?',
    back: '$235',
    steps: ['Each grade: 5,640 ÷ 6 = 940.', 'Each class: 940 ÷ 4 = 235.'],
    after: [5],
  },
  {
    n: 13, type: 'challenge', difficulty: 4,
    front: 'Estimate first, then solve: 3,872 ÷ 8.',
    back: 'Estimate: 4,000 ÷ 8 = 500. Exact: 484.',
    steps: ['38 ÷ 8 = 4 → 32 → 6.', 'Bring down 7: 67 ÷ 8 = 8 → 64 → 3.', 'Bring down 2: 32 ÷ 8 = 4.', 'Quotient: 484, close to the estimate.'],
    after: [5],
  },
]);
