import { defineCards } from '@/content/defineCards';

export const divCheckMultiplicationCards = defineCards('div-check-multiplication', ['division', 'multiplication', 'inverse-operations'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'How can you check a division answer with multiplication?',
    back: 'Multiply the quotient by the divisor and add any remainder. You should get the dividend.',
    memoryHook: 'Do and undo.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'What is the check formula for division?',
    back: 'quotient × divisor + remainder = dividend.',
    example: '47 ÷ 6 = 7 R 5 → 7 × 6 + 5 = 47 ✓',
    after: [1],
  },
  {
    n: 3, type: 'visual', difficulty: 2,
    front: 'Check 156 ÷ 12 = 13 using the picture.',
    back: '12 × 13 = 120 + 36 = 156 ✓ The rectangle with sides 12 and 13 has area 156.',
    visual: {
      kind: 'area-model',
      cols: [{ label: '10', size: 10 }, { label: '3', size: 3 }],
      rows: [{ label: '12', size: 12 }],
      cells: [['120', '36']],
      total: '156',
    },
    after: [2],
  },
  {
    n: 4, type: 'solve', difficulty: 1,
    front: 'Check 24 ÷ 6 = 4.',
    back: '4 × 6 = 24 ✓ It is correct.',
    after: [2],
    explanation: 'If 24 split into groups of 6 gives 4 groups, then 4 groups of 6 must make 24.',
  },
  {
    n: 5, type: 'solve', difficulty: 2,
    front: 'Check 91 ÷ 7 = 13.',
    back: '13 × 7 = 70 + 21 = 91 ✓ It is correct.',
    after: [2],
    steps: ['Multiply the quotient by the divisor: 13 × 7.', '10 × 7 = 70 and 3 × 7 = 21.', '70 + 21 = 91, which is the dividend.'],
  },
  {
    n: 6, type: 'solve', difficulty: 3,
    front: 'Check 487 ÷ 6 = 81 R 1.',
    back: '81 × 6 + 1 = 486 + 1 = 487 ✓ It is correct.',
    steps: ['Multiply: 81 × 6 = 486.', 'Add the remainder: 486 + 1 = 487.', 'It matches the dividend.'],
    after: [5],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: 'Is 1,872 ÷ 9 = 208 correct? Check by multiplying.',
    back: 'Yes. 208 × 9 = 1,800 + 72 = 1,872 ✓',
    after: [5],
    steps: ['208 × 9 = 200 × 9 + 8 × 9.', '1,800 + 72 = 1,872, which is the dividend.'],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'Pia says 725 ÷ 25 = 39. Check her answer. What is the correct quotient?',
    back: '39 × 25 = 975, not 725, so she is wrong. The correct answer is 29, because 29 × 25 = 725.',
    steps: ['39 × 25 = 975 (too big).', '725 ÷ 25: 25 × 29 = 725 ✓'],
    after: [6],
  },
  {
    n: 9, type: 'misconception', difficulty: 5,
    front: 'Lee checks 47 ÷ 6 = 7 R 5 by computing 7 × 6 = 42 and says it doesn’t equal 47, so it must be wrong. What did he forget?',
    back: 'To add the remainder: 42 + 5 = 47 ✓. The answer is correct.',
    commonMistake: 'Leaving the remainder out of the check.',
    after: [6],
  },
  {
    n: 10, type: 'misconception', difficulty: 5,
    front: 'True or False: Dividing again is the best way to check a division answer.',
    back: 'False. You could repeat the same mistake. Multiplying uses a different operation.',
    after: [2],
  },
  {
    n: 11, type: 'real-life', difficulty: 3,
    front: 'A store packs 372 pens into boxes of 12 and says it needs 31 boxes. Check this.',
    back: '31 × 12 = 372 ✓ It is correct.',
    steps: ['31 × 12 = 310 + 62 = 372.'],
    after: [5],
  },
  {
    n: 12, type: 'challenge', difficulty: 4,
    front: 'A number divided by 14 gives 23 with remainder 5. What is the number? Check by dividing.',
    back: '327. CHECK: 327 ÷ 14 = 23 R 5 ✓',
    steps: ['Use quotient × divisor + remainder.', '23 × 14 = 322.', '322 + 5 = 327.'],
    after: [6],
  },
  {
    n: 13, type: 'challenge', difficulty: 4,
    front: 'A calculator shows 1,001 ÷ 7 = 143. Use multiplication to check it.',
    back: '143 × 7 = 1,001 ✓ It is correct.',
    steps: ['100 × 7 = 700', '43 × 7 = 301', '700 + 301 = 1,001'],
    after: [7],
  },
]);
