import { defineCards } from '@/content/defineCards';

export const divEstimateCards = defineCards('div-estimate', ['division', 'estimation'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'Why estimate a quotient?',
    back: 'To find the size and first digit of the answer, and later to check that your exact answer is reasonable.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'How do you estimate a quotient?',
    back: 'Change the numbers to compatible numbers — close numbers that divide easily — then divide.',
    example: '412 ÷ 6 → 420 ÷ 6 = 70',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'What are compatible numbers?',
    back: 'Numbers close to the real ones that make an easy division fact.',
    example: '2,350 ÷ 8 → 2,400 ÷ 8 = 300',
    memoryHook: 'Choose numbers that are friends with the divisor.',
    after: [2],
  },
  {
    n: 4, type: 'visual', difficulty: 2,
    front: 'To estimate 412 ÷ 6, find a multiple of 6 tens (60) near 412. Which is closest on the line?',
    back: '420, because 420 ÷ 6 = 70.',
    explanation: '412 is past the halfway mark (390), so it is closest to 420.',
    visual: { kind: 'rounding-line', min: 360, max: 480, step: 60, value: 412, roundsTo: 420, showMidpoint: true },
    after: [2],
  },
  {
    n: 5, type: 'solve', difficulty: 1,
    front: 'Estimate 29 ÷ 5.',
    back: 'About 6',
    steps: ['29 ≈ 30.', '30 ÷ 5 = 6.'],
    after: [2],
  },
  {
    n: 6, type: 'solve', difficulty: 2,
    front: 'Estimate 412 ÷ 6.',
    back: 'About 70',
    steps: ['412 ≈ 420 (a multiple of 6).', '420 ÷ 6 = 70.'],
    after: [3],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: 'Estimate 2,350 ÷ 8.',
    back: 'About 300',
    steps: ['2,350 ≈ 2,400.', '24 ÷ 8 = 3, so 2,400 ÷ 8 = 300.'],
    after: [3],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'Estimate 5,127 ÷ 9.',
    back: 'About 600',
    hint: 'Which number near 5,127 is easy to divide by 9?',
    steps: ['5,127 is closest to 5,400, which is 54 hundreds.', '54 ÷ 9 = 6, so 5,400 ÷ 9 = 600.'],
    after: [7],
  },
  {
    n: 9, type: 'solve', difficulty: 4,
    front: 'Estimate 83 ÷ 21.',
    back: 'About 4',
    steps: ['Round the divisor: 21 ≈ 20.', 'Round the dividend to match: 83 ≈ 80.', '80 ÷ 20 = 4.'],
    after: [6],
  },
  {
    n: 10, type: 'misconception', difficulty: 5,
    front: 'True or False: Rounding to the nearest thousand always gives the best estimate for a division.',
    back: 'False. Choose compatible numbers that divide easily, even if that isn’t the nearest thousand.',
    example: '7,982 ÷ 4 → 8,000 ÷ 4 = 2,000. (Rounding to 7,000 gives 1,750 — harder, and farther off.)',
    after: [3],
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'A student estimates 345 ÷ 5 as about 600. How can you tell this is wrong?',
    back: '5 × 600 = 3,000, which is far more than 345. The answer should be about 70.',
    explanation: 'Use multiplication to test an estimate: 5 × 70 = 350.',
    after: [6],
  },
  {
    n: 12, type: 'real-life', difficulty: 3,
    front: 'A school has 612 students. Each bus holds 48. About how many buses are needed?',
    back: 'About 12 buses (a little more than 12, so plan for 13).',
    steps: ['612 ≈ 600 and 48 ≈ 50.', '600 ÷ 50 = 12.', 'The exact answer is 12.75, so you need 13 buses.'],
    after: [6],
  },
  {
    n: 13, type: 'challenge', difficulty: 4,
    front: 'Is 3,456 ÷ 6 closest to 50, 500 or 5,000? Use an estimate.',
    back: '500',
    steps: ['3,456 ≈ 3,600.', '36 ÷ 6 = 6, so 3,600 ÷ 6 = 600.', '600 is closest to 500 of these choices (the exact answer is 576).'],
    after: [7],
  },
  {
    n: 14, type: 'challenge', difficulty: 4,
    front: 'Without dividing exactly, tell where the first digit of 7,248 ÷ 8 goes (thousands, hundreds, …).',
    back: 'The hundreds place. 7 is less than 8, so start with 72 ÷ 8 = 9 hundreds. The quotient is 906.',
    after: [7],
    steps: ['The first digit, 7, is smaller than the divisor 8.', 'So use the first two digits: 72 ÷ 8 = 9.', 'Those 9 are hundreds (72 hundreds ÷ 8), so the quotient is about 900.'],
  },
]);
