import { defineCards } from '@/content/defineCards';

export const divMeaningCards = defineCards('div-meaning', ['division', 'meaning'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What does division mean?',
    back: 'Splitting a total into equal groups. It answers: “How many groups?” or “How many in each group?”',
    memoryHook: 'Division = how many groups?',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'What are the names of the parts of a division problem?',
    back: 'Dividend ÷ divisor = quotient.\nThe dividend is what gets split, the divisor is what you split by, and the quotient is the answer.',
    example: '24 ÷ 6 = 4  (24 is the dividend, 6 the divisor, 4 the quotient)',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'How are multiplication and division connected?',
    back: 'They are inverse operations. If 6 × 4 = 24, then 24 ÷ 4 = 6 and 24 ÷ 6 = 4.',
    memoryHook: 'A fact family has three numbers and four facts.',
    after: [1],
  },
  {
    n: 4, type: 'visual', difficulty: 1,
    front: '12 squares are arranged in 3 equal rows. How many squares are in each row?',
    back: '4 squares (12 ÷ 3 = 4)',
    explanation: 'Each row holds 4 squares, so 3 rows hold 12.',
    visual: { kind: 'shaded-grid', rows: 3, cols: 4, shaded: 12, label: '12 squares in 3 rows' },
    after: [1],
  },
  {
    n: 5, type: 'solve', difficulty: 1,
    front: '18 ÷ 3 = ?',
    back: '6',
    steps: ['Think: 3 times what is 18?', '3 × 6 = 18, so 18 ÷ 3 = 6.'],
    after: [3],
  },
  {
    n: 6, type: 'solve', difficulty: 2,
    front: '56 ÷ 7 = ?',
    back: '8',
    steps: ['7 × 8 = 56, so 56 ÷ 7 = 8.'],
    after: [3],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: '144 ÷ 12 = ?',
    back: '12',
    steps: ['Think: 12 times what is 144?', '12 × 12 = 144, so 144 ÷ 12 = 12.'],
    after: [6],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'Stickers: (a) 20 stickers shared equally among 4 children. How many each? (b) 20 stickers put into bags of 4. How many bags?',
    back: 'Both are 20 ÷ 4 = 5: (a) 5 stickers each, (b) 5 bags.',
    explanation: 'Division has two meanings: sharing (find the size of each group) and grouping (find the number of groups).',
    after: [5],
  },
  {
    n: 9, type: 'misconception', difficulty: 5,
    front: 'True or False: Division always makes a number smaller.',
    back: 'False. Dividing by a number less than 1 makes it bigger: 6 ÷ 1/2 = 12, because 12 halves fit in 6.',
    explanation: 'Dividing by 1 keeps the number the same, too.',
    after: [3],
  },
  {
    n: 10, type: 'misconception', difficulty: 5,
    front: 'True or False: 12 ÷ 3 gives the same answer as 3 ÷ 12.',
    back: 'False. 12 ÷ 3 = 4, but 3 ÷ 12 = 1/4. Order matters in division.',
    after: [2],
  },
  {
    n: 11, type: 'real-life', difficulty: 3,
    front: '28 students are split into teams of 4. How many teams are there?',
    back: '7 teams',
    steps: ['Grouping problem: how many groups of 4 fit in 28?', '28 ÷ 4 = 7', 'CHECK: 7 × 4 = 28 ✓'],
    after: [6],
  },
  {
    n: 12, type: 'challenge', difficulty: 4,
    front: 'A baker packs 96 cookies into boxes of 8. She sells 5 boxes. How many boxes are left?',
    back: '7 boxes',
    steps: ['Boxes: 96 ÷ 8 = 12.', 'Left: 12 − 5 = 7.'],
    after: [7],
  },
  {
    n: 13, type: 'challenge', difficulty: 4,
    front: 'Write two division facts that go with 7 × 9 = 63.',
    back: '63 ÷ 7 = 9 and 63 ÷ 9 = 7',
    after: [6],
    explanation: 'A fact family uses the same three numbers: 7, 9 and 63. Two multiplication and two division facts.',
  },
]);
