import { defineCards } from '@/content/defineCards';

export const divRemaindersCards = defineCards('div-remainders', ['division', 'remainders'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What is a remainder?',
    back: 'The amount left over when a number can’t be split into equal groups exactly. The remainder is always less than the divisor.',
    example: '17 ÷ 5 = 3 R 2',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'How do you write a quotient with a remainder?',
    back: 'Write the whole-number quotient, then R and the remainder.',
    example: '17 ÷ 5 = 3 R 2',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'How do you check a division that has a remainder?',
    back: 'quotient × divisor + remainder = dividend.',
    example: '3 × 5 + 2 = 17 ✓',
    after: [2],
  },
  {
    n: 4, type: 'rule', difficulty: 3,
    front: 'What can you do with a remainder in a story problem?',
    back: 'It depends on the story: ignore it (round down), round the quotient up, or share it as a fraction or decimal.',
    example: 'Full bags → ignore. Vans needed → round up. Sharing money → decimal.',
    memoryHook: 'Ask: what does the leftover mean here?',
    after: [3],
  },
  {
    n: 5, type: 'visual', difficulty: 1,
    front: '17 tiles are placed in rows of 5. How many full rows and how many tiles are left over?',
    back: '3 full rows and 2 tiles left over: 17 ÷ 5 = 3 R 2.',
    visual: { kind: 'shaded-grid', rows: 4, cols: 5, shaded: 17, label: '17 tiles in rows of 5' },
    after: [2],
  },
  {
    n: 6, type: 'solve', difficulty: 1,
    front: '14 ÷ 4 = ?',
    back: '3 R 2',
    steps: ['4 × 3 = 12, and 14 − 12 = 2.', 'CHECK: 3 × 4 + 2 = 14 ✓'],
    after: [2],
  },
  {
    n: 7, type: 'solve', difficulty: 2,
    front: '47 ÷ 6 = ?',
    back: '7 R 5',
    steps: ['6 × 7 = 42, and 47 − 42 = 5.', 'CHECK: 7 × 6 + 5 = 47 ✓'],
    after: [3],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: '253 ÷ 4 = ?',
    back: '63 R 1',
    steps: ['25 ÷ 4 = 6 → 24 → 1.', 'Bring down 3: 13 ÷ 4 = 3 → 12 → 1.', 'CHECK: 63 × 4 + 1 = 253 ✓'],
    after: [7],
  },
  {
    n: 9, type: 'solve', difficulty: 3,
    front: '1,000 ÷ 7 = ?',
    back: '142 R 6',
    steps: ['10 ÷ 7 = 1 → 7 → 3.', 'Bring down 0: 30 ÷ 7 = 4 → 28 → 2.', 'Bring down 0: 20 ÷ 7 = 2 → 14 → 6.', 'CHECK: 142 × 7 + 6 = 994 + 6 = 1,000 ✓'],
    after: [8],
  },
  {
    n: 10, type: 'misconception', difficulty: 5,
    front: 'True or False: 23 ÷ 5 = 4 R 8 is a correct way to write the answer.',
    back: 'False. The remainder must be less than the divisor. 23 ÷ 5 = 4 R 3.',
    explanation: 'A remainder of 8 means another group of 5 still fits.',
    after: [3],
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'True or False: 25 ÷ 4 = 6 R 1 means the answer is 6.1.',
    back: 'False. The 1 left over is 1/4 of a group, so the answer is 6 1/4, or 6.25.',
    after: [4],
  },
  {
    n: 12, type: 'real-life', difficulty: 3,
    front: '52 students are going on a trip. Each van holds 8 students. How many vans are needed?',
    back: '7 vans',
    steps: ['52 ÷ 8 = 6 R 4.', '4 students are left, and they still need a ride.', 'Round UP: 7 vans.'],
    after: [4],
  },
  {
    n: 13, type: 'real-life', difficulty: 3,
    front: 'A baker puts 6 cookies in each bag. She has 83 cookies. How many FULL bags can she make?',
    back: '13 full bags',
    steps: ['83 ÷ 6 = 13 R 5.', 'Only full bags count, so ignore the 5 extra cookies.'],
    after: [8],
  },
  {
    n: 14, type: 'challenge', difficulty: 4,
    front: '$50 is shared equally among 8 friends. How much does each friend get?',
    back: '$6.25',
    steps: ['50 ÷ 8 = 6 R 2.', 'The 2 left dollars are split too: 2 ÷ 8 = 0.25.', '6 + 0.25 = $6.25.'],
    after: [8],
  },
  {
    n: 15, type: 'challenge', difficulty: 4,
    front: 'A number is divided by 7. The quotient is 12 and the remainder is 5. What is the number?',
    back: '89',
    steps: ['Use quotient × divisor + remainder.', '12 × 7 + 5 = 84 + 5 = 89.', 'CHECK: 89 ÷ 7 = 12 R 5 ✓'],
    after: [9],
  },
]);
