import { defineCards } from '@/content/defineCards';

export const fmCommonMultiplesCards = defineCards('fm-common-multiples', ['multiples', 'common-multiples'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What are common multiples?',
    back: 'Multiples that two or more numbers share.',
    example: 'Multiples of 2: 2, 4, 6, 8, 10, 12. Multiples of 3: 3, 6, 9, 12. Common: 6, 12, …',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'How do you find common multiples?',
    back: 'List the multiples of each number and look for numbers that appear in both lists.',
    after: [1],
  },
  {
    n: 3, type: 'visual', difficulty: 2,
    front: 'Multiples of 3 are yellow and multiples of 5 are blue. Which numbers are green?',
    back: '15 and 30 — the common multiples of 3 and 5.',
    visual: {
      kind: 'number-grid',
      from: 1,
      to: 30,
      cols: 10,
      a: [3, 6, 9, 12, 15, 18, 21, 24, 27, 30],
      b: [5, 10, 15, 20, 25, 30],
      labelA: 'multiples of 3',
      labelB: 'multiples of 5',
    },
    after: [2],
  },
  {
    n: 4, type: 'solve', difficulty: 1,
    front: 'List the common multiples of 2 and 3 up to 12.',
    back: '6 and 12',
    steps: ['Multiples of 2: 2, 4, 6, 8, 10, 12.', 'Multiples of 3: 3, 6, 9, 12.'],
    after: [2],
  },
  {
    n: 5, type: 'solve', difficulty: 2,
    front: 'What is the first common multiple of 4 and 6?',
    back: '12',
    steps: ['Multiples of 4: 4, 8, 12.', 'Multiples of 6: 6, 12.'],
    after: [4],
  },
  {
    n: 6, type: 'solve', difficulty: 3,
    front: 'List the first three common multiples of 4 and 10.',
    back: '20, 40, 60',
    steps: ['Multiples of 4: 4, 8, 12, 16, 20, 24, … 40 … 60.', 'Multiples of 10: 10, 20, 30, 40, 50, 60.', 'The common multiples are 20, 40 and 60.'],
    after: [5],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: 'List the first three common multiples of 6 and 8.',
    back: '24, 48, 72',
    steps: ['Multiples of 6: 6, 12, 18, 24, 30, 36, 42, 48 …', 'Multiples of 8: 8, 16, 24, 32, 40, 48 …', 'They first meet at 24, then every 24.'],
    after: [5],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'Is 60 a common multiple of 12 and 15?',
    back: 'Yes. 12 × 5 = 60 and 15 × 4 = 60.',
    after: [5],
    explanation: 'Count by 12s: 12, 24, 36, 48, 60. Count by 15s: 15, 30, 45, 60. Both reach 60.',
  },
  {
    n: 9, type: 'misconception', difficulty: 5,
    front: 'True or False: The smallest common multiple of two numbers is always their product.',
    back: 'False. 4 × 6 = 24, but 12 is a smaller common multiple of 4 and 6.',
    after: [5],
  },
  {
    n: 10, type: 'misconception', difficulty: 5,
    front: 'True or False: Two numbers have a greatest common multiple.',
    back: 'False. Multiples go on forever, so there is always a bigger one. There is a LEAST common multiple, though.',
    after: [2],
  },
  {
    n: 11, type: 'real-life', difficulty: 3,
    front: 'One bus leaves a stop every 6 minutes and another every 8 minutes. Both leave at 7:00. When do they next leave at the same time?',
    back: '7:24',
    steps: ['The times are multiples of 6 and multiples of 8 minutes after 7:00.', 'First shared multiple: 24.'],
    after: [7],
  },
  {
    n: 12, type: 'challenge', difficulty: 4,
    front: 'Find a number between 50 and 70 that is a common multiple of 4 and 6.',
    back: '60',
    steps: ['Common multiples of 4 and 6 are the multiples of 12: 12, 24, 36, 48, 60, 72.', 'The one between 50 and 70 is 60.'],
    after: [7],
  },
  {
    n: 13, type: 'challenge', difficulty: 4,
    front: 'How many common multiples of 3 and 4 are less than 100?',
    back: '8 (12, 24, 36, 48, 60, 72, 84, 96)',
    steps: ['The common multiples of 3 and 4 are the multiples of 12.', '100 ÷ 12 = 8 with 4 left over → 8 multiples.'],
    after: [7],
  },
]);
