import { defineCards } from '@/content/defineCards';

export const fmCommonFactorsCards = defineCards('fm-common-factors', ['factors', 'common-factors'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What are common factors?',
    back: 'Factors that two or more numbers share.',
    example: '6 and 9 share the factors 1 and 3.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'How do you find the common factors of two numbers?',
    back: 'List all the factors of each number, then pick the ones that are on both lists.',
    after: [1],
  },
  {
    n: 3, type: 'visual', difficulty: 2,
    front: 'Factors of 12 are yellow and factors of 18 are blue. Which numbers are green (common factors)?',
    back: '1, 2, 3 and 6',
    visual: {
      kind: 'number-grid',
      from: 1,
      to: 18,
      cols: 9,
      a: [1, 2, 3, 4, 6, 12],
      b: [1, 2, 3, 6, 9, 18],
      labelA: 'factors of 12',
      labelB: 'factors of 18',
    },
    after: [2],
  },
  {
    n: 4, type: 'solve', difficulty: 1,
    front: 'Find the common factors of 6 and 9.',
    back: '1 and 3',
    steps: ['Factors of 6: 1, 2, 3, 6.', 'Factors of 9: 1, 3, 9.', 'Shared: 1 and 3.'],
    after: [2],
  },
  {
    n: 5, type: 'solve', difficulty: 2,
    front: 'Find the common factors of 8 and 12.',
    back: '1, 2 and 4',
    steps: ['Factors of 8: 1, 2, 4, 8.', 'Factors of 12: 1, 2, 3, 4, 6, 12.', 'Shared: 1, 2 and 4.'],
    after: [4],
  },
  {
    n: 6, type: 'solve', difficulty: 3,
    front: 'Find the common factors of 24 and 36.',
    back: '1, 2, 3, 4, 6 and 12',
    steps: ['Factors of 24: 1, 2, 3, 4, 6, 8, 12, 24.', 'Factors of 36: 1, 2, 3, 4, 6, 9, 12, 18, 36.', 'Shared: 1, 2, 3, 4, 6, 12.'],
    after: [5],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: 'Find the common factors of 15 and 28.',
    back: 'Only 1',
    steps: ['Factors of 15: 1, 3, 5, 15.', 'Factors of 28: 1, 2, 4, 7, 14, 28.', 'Only 1 is on both lists.'],
    after: [5],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'Find the common factors of 20, 30 and 50.',
    back: '1, 2, 5 and 10',
    steps: ['Factors of 20: 1, 2, 4, 5, 10, 20.', 'Factors of 30: 1, 2, 3, 5, 6, 10, 15, 30.', 'Factors of 50: 1, 2, 5, 10, 25, 50.', 'Shared by all three: 1, 2, 5, 10.'],
    after: [6],
  },
  {
    n: 9, type: 'misconception', difficulty: 5,
    front: 'True or False: Two whole numbers can have no common factors at all.',
    back: 'False. 1 is a factor of every whole number, so they always share at least 1.',
    after: [2],
  },
  {
    n: 10, type: 'misconception', difficulty: 5,
    front: 'Dina says 36 is a common factor of 12 and 18 because it is divisible by both. What did she mix up?',
    back: 'She described a common MULTIPLE. A common factor divides both numbers. 36 is too big to be a factor of 12.',
    memoryHook: 'Factors are small, multiples are big.',
    after: [3],
  },
  {
    n: 11, type: 'real-life', difficulty: 3,
    front: '18 apples and 24 oranges are put into identical baskets with no fruit left over. How many baskets could you make?',
    back: '1, 2, 3 or 6 baskets.',
    steps: ['The number of baskets must divide both 18 and 24.', 'Common factors of 18 and 24: 1, 2, 3, 6.'],
    after: [6],
  },
  {
    n: 12, type: 'challenge', difficulty: 4,
    front: 'Find all the common factors of 16 and 40.',
    back: '1, 2, 4 and 8',
    steps: ['Factors of 16: 1, 2, 4, 8, 16.', 'Factors of 40: 1, 2, 4, 5, 8, 10, 20, 40.', 'Shared: 1, 2, 4, 8.'],
    after: [6],
  },
  {
    n: 13, type: 'challenge', difficulty: 4,
    front: 'Which common factor of 42 and 63 is greater than 5 but less than 10?',
    back: '7',
    steps: ['Factors of 42: 1, 2, 3, 6, 7, 14, 21, 42.', 'Factors of 63: 1, 3, 7, 9, 21, 63.', 'Common: 1, 3, 7, 21. Between 5 and 10: 7.'],
    after: [6],
  },
]);
