import { defineCards } from '@/content/defineCards';

export const fmDivisibilityCards = defineCards('fm-divisibility', ['factors', 'divisibility'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What is a divisibility rule?',
    back: 'A quick test that tells you whether a number divides evenly by another number, without doing the division.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'What are the divisibility rules for 2, 5 and 10?',
    back: 'By 2: the number ends in 0, 2, 4, 6 or 8.\nBy 5: it ends in 0 or 5.\nBy 10: it ends in 0.',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'What are the divisibility rules for 3 and 9?',
    back: 'Add the digits. If the sum is divisible by 3, the number is divisible by 3. If the sum is divisible by 9, the number is divisible by 9.',
    example: '261 → 2 + 6 + 1 = 9 → divisible by 3 and by 9',
    after: [1],
  },
  {
    n: 4, type: 'rule', difficulty: 2,
    front: 'What are the divisibility rules for 4 and 6?',
    back: 'By 4: the last two digits make a number divisible by 4.\nBy 6: the number is divisible by both 2 and 3.',
    example: '1,716: last two digits 16 ÷ 4 = 4 → divisible by 4',
    after: [2, 3],
  },
  {
    n: 5, type: 'visual', difficulty: 2,
    front: 'Multiples of 3 are yellow and multiples of 2 are blue. Which numbers are green, and what does that tell you?',
    back: '6, 12, 18, 24, 30. Numbers divisible by both 2 and 3 are divisible by 6.',
    visual: {
      kind: 'number-grid',
      from: 1,
      to: 30,
      cols: 10,
      a: [3, 6, 9, 12, 15, 18, 21, 24, 27, 30],
      b: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30],
      labelA: 'by 3',
      labelB: 'by 2',
    },
    after: [4],
  },
  {
    n: 6, type: 'solve', difficulty: 1,
    front: 'Is 135 divisible by 5?',
    back: 'Yes, because it ends in 5.',
    after: [2],
    explanation: 'Every multiple of 5 ends in 0 or 5: 5, 10, 15, 20, 25, …',
  },
  {
    n: 7, type: 'solve', difficulty: 2,
    front: 'Is 462 divisible by 3?',
    back: 'Yes.',
    steps: ['4 + 6 + 2 = 12.', '12 is divisible by 3, so 462 is too (462 ÷ 3 = 154).'],
    after: [3],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'Is 2,358 divisible by 9?',
    back: 'Yes.',
    steps: ['2 + 3 + 5 + 8 = 18.', '18 is divisible by 9, so 2,358 is too (2,358 ÷ 9 = 262).'],
    after: [7],
  },
  {
    n: 9, type: 'solve', difficulty: 3,
    front: 'Is 1,716 divisible by 4?',
    back: 'Yes.',
    steps: ['Look at the last two digits: 16.', '16 ÷ 4 = 4, so 1,716 is divisible by 4 (1,716 ÷ 4 = 429).'],
    after: [4],
  },
  {
    n: 10, type: 'solve', difficulty: 3,
    front: 'Which of 2, 3, 5, 9 and 10 divide 540 evenly?',
    back: 'All of them.',
    steps: ['Ends in 0 → divisible by 2, 5 and 10.', 'Digits: 5 + 4 + 0 = 9 → divisible by 3 and 9.'],
    after: [7],
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'True or False: 123 is divisible by 9 because it is divisible by 3.',
    back: 'False. 1 + 2 + 3 = 6, which is divisible by 3 but not 9. So 123 is divisible by 3 only.',
    after: [3],
  },
  {
    n: 12, type: 'misconception', difficulty: 5,
    front: 'True or False: A number ending in 5 is divisible by 10.',
    back: 'False. Ending in 5 means divisible by 5. Divisible by 10 requires ending in 0.',
    after: [2],
  },
  {
    n: 13, type: 'real-life', difficulty: 3,
    front: 'Can 144 stickers be shared equally among 9 children with none left over? Use a rule.',
    back: 'Yes. 1 + 4 + 4 = 9, so 144 is divisible by 9. Each child gets 16.',
    after: [8],
  },
  {
    n: 14, type: 'challenge', difficulty: 4,
    front: 'Which digits can replace ■ so that 4■2 is divisible by 3?',
    back: '0, 3, 6 or 9',
    steps: ['4 + ■ + 2 = 6 + ■.', '6 + ■ must be divisible by 3, so ■ is 0, 3, 6 or 9.'],
    after: [8],
  },
  {
    n: 15, type: 'challenge', difficulty: 4,
    front: 'What is the smallest number greater than 0 that is divisible by 2, 3 and 5?',
    back: '30',
    steps: ['Divisible by 2 and 5 → ends in 0.', 'Divisible by 3 → digit sum divisible by 3.', 'The smallest such number is 30.'],
    after: [10],
  },
]);
