import { defineCards } from '@/content/defineCards';

export const fmEvenOddCards = defineCards('fm-even-odd', ['factors', 'even-odd', 'patterns'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What makes a number even or odd?',
    back: 'Even numbers split into 2 equal groups with none left over (they end in 0, 2, 4, 6 or 8). Odd numbers always leave 1 left over (they end in 1, 3, 5, 7 or 9).',
    memoryHook: 'Even numbers pair up perfectly. Odd numbers have a leftover.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'What happens when you ADD even and odd numbers?',
    back: 'even + even = even\nodd + odd = even\neven + odd = odd',
    example: '3 + 5 = 8 (odd + odd = even)',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'What happens when you MULTIPLY even and odd numbers?',
    back: 'even × anything = even\nodd × odd = odd',
    example: '7 × 9 = 63 (odd × odd = odd)',
    after: [1],
  },
  {
    n: 4, type: 'visual', difficulty: 1,
    front: 'The even numbers from 1 to 20 are highlighted. What pattern do you see?',
    back: 'Even and odd numbers alternate: odd, even, odd, even…',
    explanation: 'Every second number is even, so the evens line up in columns on this grid.',
    visual: { kind: 'number-grid', from: 1, to: 20, cols: 10, a: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20], labelA: 'even' },
    after: [1],
  },
  {
    n: 5, type: 'solve', difficulty: 1,
    front: 'Is 47 even or odd?',
    back: 'Odd, because it ends in 7.',
    after: [1],
    explanation: 'Only the ones digit matters: 0, 2, 4, 6, 8 mean even; 1, 3, 5, 7, 9 mean odd.',
  },
  {
    n: 6, type: 'solve', difficulty: 2,
    front: 'Is 38 + 25 even or odd? Answer without adding.',
    back: 'Odd',
    steps: ['38 is even and 25 is odd.', 'even + odd = odd.'],
    after: [2],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: 'Is 17 × 23 even or odd? Answer without multiplying.',
    back: 'Odd',
    steps: ['17 is odd and 23 is odd.', 'odd × odd = odd. (It is 391.)'],
    after: [3],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'Is 1,001 + 999 even or odd?',
    back: 'Even',
    steps: ['Both numbers are odd.', 'odd + odd = even. (The sum is 2,000.)'],
    after: [2],
  },
  {
    n: 9, type: 'solve', difficulty: 3,
    front: 'Is the sum of three odd numbers even or odd?',
    back: 'Odd',
    steps: ['The first two odds add to an even.', 'even + odd = odd.', 'Example: 3 + 5 + 7 = 15.'],
    after: [8],
  },
  {
    n: 10, type: 'misconception', difficulty: 5,
    front: 'True or False: 0 is neither even nor odd.',
    back: 'False. 0 is even. It splits into two equal groups of 0 and ends in 0.',
    after: [1],
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'True or False: The sum of two odd numbers is odd.',
    back: 'False. odd + odd = even. For example 3 + 5 = 8.',
    explanation: 'Each odd number has one left over; the two leftovers pair up.',
    after: [2],
  },
  {
    n: 12, type: 'real-life', difficulty: 3,
    front: '23 students line up in pairs for a field trip. Will anyone be without a partner?',
    back: 'Yes. 23 is odd, so one student is left without a partner.',
    after: [5],
  },
  {
    n: 13, type: 'challenge', difficulty: 4,
    front: 'Can two numbers have an odd sum AND an odd product?',
    back: 'No. An odd sum needs one even and one odd number, but then the product is even.',
    after: [9],
    hint: 'Think about which kinds of numbers (even or odd) make an odd sum, then multiply them.',
  },
  {
    n: 14, type: 'challenge', difficulty: 4,
    front: 'I am an even number between 40 and 50. My digits add to 10. What number am I?',
    back: '46',
    steps: ['Even numbers from 40 to 50: 42, 44, 46, 48.', 'Digit sums: 6, 8, 10, 12.', 'Only 46 has a digit sum of 10.'],
    after: [6],
  },
]);
