import { defineCards } from '@/content/defineCards';

export const fmFactorPairsCards = defineCards('fm-factor-pairs', ['factors', 'factor-pairs'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What is a factor?',
    back: 'A whole number that divides another number evenly, with nothing left over.',
    example: 'The factors of 12 are 1, 2, 3, 4, 6 and 12.',
    memoryHook: 'Factors are the numbers that multiply together to make it.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'How do you find all the factors of a number?',
    back: 'Test 1, 2, 3, … in order. Each time one divides evenly, write the pair. Stop when the pairs meet or cross.',
    example: '18: 1 × 18, 2 × 9, 3 × 6. Next is 4 (doesn’t divide), 5 (no), and 6 is already used. Done!',
    after: [1],
  },
  {
    n: 3, type: 'visual', difficulty: 1,
    front: 'This array shows 12 squares in 3 rows of 4. Which multiplication and factor pair does it show?',
    back: '3 × 4 = 12, so 3 and 4 are a factor pair of 12.',
    explanation: 'Turn it on its side and you get 4 rows of 3. Same pair.',
    visual: { kind: 'shaded-grid', rows: 3, cols: 4, shaded: 12 },
    answerVisual: { kind: 'shaded-grid', rows: 3, cols: 4, shaded: 12, label: '3 × 4 = 12' },
    after: [1],
  },
  {
    n: 4, type: 'solve', difficulty: 1,
    front: 'List all the factors of 10.',
    back: '1, 2, 5, 10',
    steps: ['1 × 10 = 10', '2 × 5 = 10', 'The factors are 1, 2, 5 and 10.'],
    after: [2],
  },
  {
    n: 5, type: 'solve', difficulty: 2,
    front: 'List the factor pairs of 18.',
    back: '1 × 18, 2 × 9, 3 × 6',
    steps: ['1 × 18 = 18', '2 × 9 = 18', '3 × 6 = 18', '4 and 5 don’t divide 18, and the next is 6, which we already have.'],
    after: [4],
  },
  {
    n: 6, type: 'solve', difficulty: 3,
    front: 'List all the factors of 36.',
    back: '1, 2, 3, 4, 6, 9, 12, 18, 36',
    steps: ['1 × 36, 2 × 18, 3 × 12, 4 × 9, 6 × 6', 'A pair with the same number (6 × 6) only counts 6 once.'],
    after: [5],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: 'List all the factors of 48. How many are there?',
    back: '1, 2, 3, 4, 6, 8, 12, 16, 24, 48 — that is 10 factors.',
    steps: ['1 × 48, 2 × 24, 3 × 16, 4 × 12, 6 × 8', '5 and 7 don’t divide 48.'],
    after: [6],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'Is 7 a factor of 91?',
    back: 'Yes. 91 ÷ 7 = 13 with nothing left over.',
    steps: ['7 × 13 = 70 + 21 = 91 ✓'],
    after: [5],
  },
  {
    n: 9, type: 'misconception', difficulty: 5,
    front: 'True or False: 24 is a factor of 12.',
    back: 'False. 24 is a multiple of 12. A factor is never larger than the number.',
    memoryHook: 'Factors are smaller (or equal). Multiples are bigger (or equal).',
    after: [1],
  },
  {
    n: 10, type: 'misconception', difficulty: 5,
    front: 'Leo lists the factors of 20 as 1, 2, 4, 5, 10. What is missing?',
    back: '20 itself. Every number is a factor of itself: 1, 2, 4, 5, 10, 20.',
    commonMistake: 'Leaving out the number itself.',
    after: [5],
  },
  {
    n: 11, type: 'real-life', difficulty: 3,
    front: 'A teacher has 24 chairs and wants equal rows. Which row arrangements are possible?',
    back: '1 row of 24, 2 rows of 12, 3 rows of 8, 4 rows of 6 (and the same pairs turned around).',
    steps: ['The factor pairs of 24 are 1 × 24, 2 × 12, 3 × 8 and 4 × 6.'],
    after: [6],
  },
  {
    n: 12, type: 'challenge', difficulty: 4,
    front: 'Which number between 20 and 30 has exactly three factors?',
    back: '25 (its factors are 1, 5 and 25)',
    hint: 'A number with an odd count of factors has a pair of equal factors.',
    steps: ['A perfect square has an odd number of factors.', '25 = 5 × 5, so its factors are 1, 5 and 25.'],
    after: [7],
  },
  {
    n: 13, type: 'challenge', difficulty: 4,
    front: 'I am a factor of 30, a multiple of 5, even, and less than 30. What number am I?',
    back: '10',
    steps: ['Factors of 30: 1, 2, 3, 5, 6, 10, 15, 30.', 'Multiples of 5 among them: 5, 10, 15, 30.', 'Even and less than 30: 10.'],
    after: [6],
  },
]);
