import { defineCards } from '@/content/defineCards';

export const fmGcfCards = defineCards('fm-gcf', ['factors', 'gcf'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What is the GCF (greatest common factor)?',
    back: 'The biggest number that divides both numbers evenly.',
    memoryHook: 'GCF = the biggest shared building block.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'What are two ways to find the GCF?',
    back: '1) List the factors of each number and pick the biggest one they share.\n2) Write the prime factorizations and multiply the primes they have in common.',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'How does the GCF help you simplify a fraction?',
    back: 'Divide the numerator and the denominator by their GCF. The fraction is then in simplest form in one step.',
    example: '12/18 ÷ 6/6 = 2/3',
    after: [2],
  },
  {
    n: 4, type: 'visual', difficulty: 2,
    front: 'Factors of 24 are yellow and factors of 36 are blue. Which green (shared) number is the greatest?',
    back: '12, so the GCF of 24 and 36 is 12.',
    visual: {
      kind: 'number-grid',
      from: 1,
      to: 36,
      cols: 12,
      a: [1, 2, 3, 4, 6, 8, 12, 24],
      b: [1, 2, 3, 4, 6, 9, 12, 18, 36],
      labelA: 'factors of 24',
      labelB: 'factors of 36',
    },
    after: [2],
  },
  {
    n: 5, type: 'solve', difficulty: 1,
    front: 'Find the GCF of 6 and 9.',
    back: '3',
    steps: ['Factors of 6: 1, 2, 3, 6.', 'Factors of 9: 1, 3, 9.', 'The greatest shared factor is 3.'],
    after: [2],
  },
  {
    n: 6, type: 'solve', difficulty: 2,
    front: 'Find the GCF of 12 and 18.',
    back: '6',
    steps: ['Factors of 12: 1, 2, 3, 4, 6, 12.', 'Factors of 18: 1, 2, 3, 6, 9, 18.', 'The greatest shared factor is 6.'],
    after: [5],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: 'Find the GCF of 24 and 40.',
    back: '8',
    steps: ['Factors of 24: 1, 2, 3, 4, 6, 8, 12, 24.', 'Factors of 40: 1, 2, 4, 5, 8, 10, 20, 40.', 'The greatest shared factor is 8.'],
    after: [6],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'Find the GCF of 45 and 60.',
    back: '15',
    steps: ['45 = 3 × 3 × 5 and 60 = 2 × 2 × 3 × 5.', 'Shared primes: 3 and 5.', '3 × 5 = 15.'],
    after: [6],
  },
  {
    n: 9, type: 'solve', difficulty: 3,
    front: 'Use prime factorization to find the GCF of 84 and 126.',
    back: '42',
    steps: ['84 = 2 × 2 × 3 × 7 and 126 = 2 × 3 × 3 × 7.', 'Shared primes: 2, 3 and 7.', '2 × 3 × 7 = 42.'],
    after: [8],
  },
  {
    n: 10, type: 'solve', difficulty: 3,
    front: 'Find the GCF of 17 and 34.',
    back: '17',
    explanation: 'When one number is a factor of the other, the smaller number is the GCF.',
    steps: ['34 = 2 × 17, so 17 divides both.', 'No bigger number can divide 17.'],
    after: [6],
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'True or False: The GCF of 8 and 12 is 24.',
    back: 'False. The GCF is 4. 24 is their least common multiple. The GCF can never be larger than the smaller number.',
    memoryHook: 'GCF is small (a factor). LCM is big (a multiple).',
    after: [6],
  },
  {
    n: 12, type: 'misconception', difficulty: 5,
    front: 'Ana says 10 and 21 have a GCF of 0 because they share no factors. Is she right?',
    back: 'No. They share the factor 1, so their GCF is 1.',
    after: [6],
  },
  {
    n: 13, type: 'real-life', difficulty: 3,
    front: 'A teacher has 36 pencils and 48 erasers. She makes identical kits with nothing left over. What is the greatest number of kits? What is in each kit?',
    back: '12 kits, each with 3 pencils and 4 erasers.',
    steps: ['GCF of 36 and 48 = 12.', '36 ÷ 12 = 3 pencils.', '48 ÷ 12 = 4 erasers.'],
    after: [8],
  },
  {
    n: 14, type: 'challenge', difficulty: 4,
    front: 'Simplify 42/56 using the GCF.',
    back: '3/4',
    steps: ['GCF of 42 and 56 is 14.', '42 ÷ 14 = 3 and 56 ÷ 14 = 4.', '42/56 = 3/4'],
    after: [9],
  },
  {
    n: 15, type: 'challenge', difficulty: 4,
    front: 'The GCF of two numbers is 9. One number is 27. What could the other number be if it is between 30 and 50?',
    back: '36 or 45',
    steps: ['The other number must be a multiple of 9: 36 or 45.', 'GCF of 27 and 36 = 9 ✓', 'GCF of 27 and 45 = 9 ✓'],
    after: [9],
  },
]);
