import { defineCards } from '@/content/defineCards';

export const fmLcmCards = defineCards('fm-lcm', ['multiples', 'lcm'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What is the LCM (least common multiple)?',
    back: 'The smallest number that is a multiple of both numbers.',
    memoryHook: 'LCM = the first place two skip-counters meet.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'What are two ways to find the LCM?',
    back: '1) List multiples of each number until one appears on both lists.\n2) Use prime factorization: take each prime the greatest number of times it appears in either number, and multiply.',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'Why does the LCM matter for fractions?',
    back: 'The LCM of the denominators is the least common denominator. It lets you add and subtract fractions with unlike denominators using the smallest numbers.',
    example: '1/4 + 1/6: LCM(4, 6) = 12 → 3/12 + 2/12 = 5/12',
    after: [2],
  },
  {
    n: 4, type: 'visual', difficulty: 2,
    front: 'Multiples of 4 are yellow and multiples of 6 are blue. What is the first green number, and what does it mean?',
    back: '12. It is the first number on both lists, so LCM(4, 6) = 12.',
    visual: {
      kind: 'number-grid',
      from: 1,
      to: 24,
      cols: 12,
      a: [4, 8, 12, 16, 20, 24],
      b: [6, 12, 18, 24],
      labelA: 'multiples of 4',
      labelB: 'multiples of 6',
    },
    after: [2],
  },
  {
    n: 5, type: 'solve', difficulty: 1,
    front: 'Find the LCM of 2 and 3.',
    back: '6',
    steps: ['Multiples of 2: 2, 4, 6.', 'Multiples of 3: 3, 6.'],
    after: [2],
  },
  {
    n: 6, type: 'solve', difficulty: 2,
    front: 'Find the LCM of 4 and 6.',
    back: '12',
    steps: ['Multiples of 4: 4, 8, 12.', 'Multiples of 6: 6, 12.'],
    after: [5],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: 'Find the LCM of 8 and 12.',
    back: '24',
    steps: ['Multiples of 8: 8, 16, 24.', 'Multiples of 12: 12, 24.'],
    after: [6],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'Find the LCM of 9 and 15.',
    back: '45',
    steps: ['9 = 3 × 3 and 15 = 3 × 5.', 'Take 3 twice and 5 once: 3 × 3 × 5 = 45.'],
    after: [6],
  },
  {
    n: 9, type: 'solve', difficulty: 3,
    front: 'Find the LCM of 5 and 7.',
    back: '35',
    explanation: 'When two numbers share no factor except 1, the LCM is their product.',
    steps: ['5 and 7 are both prime.', '5 × 7 = 35.'],
    after: [6],
  },
  {
    n: 10, type: 'solve', difficulty: 4,
    front: 'Find the LCM of 4, 6 and 10.',
    back: '60',
    steps: ['4 = 2 × 2, 6 = 2 × 3, 10 = 2 × 5.', 'Take 2 twice, 3 once and 5 once: 2 × 2 × 3 × 5 = 60.'],
    after: [8],
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'Max says the LCM of 6 and 9 is 54 because 6 × 9 = 54. Is he right?',
    back: 'No. 18 is a common multiple that is smaller. LCM(6, 9) = 18.',
    explanation: 'Multiplying the numbers always gives a common multiple, but not always the least.',
    after: [8],
  },
  {
    n: 12, type: 'misconception', difficulty: 5,
    front: 'True or False: The LCM of 3 and 12 is 36.',
    back: 'False. 12 is a multiple of 3, so LCM(3, 12) = 12.',
    after: [7],
  },
  {
    n: 13, type: 'real-life', difficulty: 3,
    front: 'Hot dogs come 10 to a pack and buns come 8 to a pack. What is the smallest number of each to buy so none are left over?',
    back: '40 hot dogs and 40 buns (4 packs of hot dogs and 5 packs of buns).',
    steps: ['LCM of 10 and 8 is 40.', '40 ÷ 10 = 4 packs.', '40 ÷ 8 = 5 packs.'],
    after: [7],
  },
  {
    n: 14, type: 'challenge', difficulty: 4,
    front: 'Two lights blink, one every 4 seconds and one every 6 seconds. They have just blinked together. How many more times will they blink together in the next 60 seconds?',
    back: '5 times',
    steps: ['LCM(4, 6) = 12 seconds.', 'They blink together at 12, 24, 36, 48 and 60 seconds.'],
    after: [7],
  },
  {
    n: 15, type: 'challenge', difficulty: 4,
    front: 'Add 1/4 + 1/6 using the LCM of the denominators.',
    back: '5/12',
    steps: ['LCM(4, 6) = 12.', '1/4 = 3/12 and 1/6 = 2/12.', '3/12 + 2/12 = 5/12'],
    after: [7],
  },
]);
