import { defineCards } from '@/content/defineCards';

export const fmMultiplesCards = defineCards('fm-multiples', ['multiples'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What is a multiple?',
    back: 'The product of a number and any whole number 1, 2, 3, … In other words, what you get when you skip count.',
    example: 'Multiples of 4: 4, 8, 12, 16, 20, …',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'How do you list the multiples of a number?',
    back: 'Skip count by that number, or multiply it by 1, 2, 3, 4, …',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'How are factors and multiples different?',
    back: 'Factors divide into a number and are smaller than or equal to it. Multiples are what you get by multiplying the number, and are greater than or equal to it.',
    example: '3 is a factor of 12. 24 is a multiple of 12.',
    memoryHook: 'The list of multiples goes on forever; the list of factors ends.',
    after: [1],
  },
  {
    n: 4, type: 'visual', difficulty: 1,
    front: 'The multiples of 4 up to 40 are highlighted. What do you notice?',
    back: 'They are exactly 4 apart, and every one is even.',
    visual: { kind: 'number-grid', from: 1, to: 40, cols: 10, a: [4, 8, 12, 16, 20, 24, 28, 32, 36, 40], labelA: 'multiples of 4' },
    after: [2],
  },
  {
    n: 5, type: 'solve', difficulty: 1,
    front: 'List the first five multiples of 3.',
    back: '3, 6, 9, 12, 15',
    after: [2],
    explanation: 'Skip count by 3: add 3 each time.',
  },
  {
    n: 6, type: 'solve', difficulty: 2,
    front: 'Is 56 a multiple of 7?',
    back: 'Yes, because 7 × 8 = 56.',
    after: [2],
    explanation: '7, 14, 21, 28, 35, 42, 49, 56 — it appears when you skip count by 7.',
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: 'List the multiples of 9 between 50 and 100.',
    back: '54, 63, 72, 81, 90, 99',
    steps: ['9 × 6 = 54, 9 × 7 = 63, 9 × 8 = 72, 9 × 9 = 81, 9 × 10 = 90, 9 × 11 = 99.'],
    after: [5],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'Is 1,236 a multiple of 6?',
    back: 'Yes.',
    steps: ['A multiple of 6 must be even and divisible by 3.', '1,236 is even, and 1 + 2 + 3 + 6 = 12 is divisible by 3.', '1,236 ÷ 6 = 206.'],
    after: [6],
  },
  {
    n: 9, type: 'solve', difficulty: 3,
    front: 'What is the 12th multiple of 8?',
    back: '96',
    steps: ['The 12th multiple of 8 is 8 × 12.', '8 × 12 = 96.'],
    after: [5],
  },
  {
    n: 10, type: 'misconception', difficulty: 5,
    front: 'True or False: 5 is a multiple of 20.',
    back: 'False. 20 is a multiple of 5 (5 × 4 = 20). A multiple can’t be smaller than the number.',
    after: [3],
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'True or False: The list of multiples of a number eventually ends.',
    back: 'False. You can always multiply by a bigger number, so the multiples go on forever.',
    after: [3],
  },
  {
    n: 12, type: 'real-life', difficulty: 3,
    front: 'A bus leaves every 15 minutes starting at 8:00. Which of these times has a bus: 8:45, 9:10, 9:30?',
    back: '8:45 and 9:30',
    steps: ['The bus leaves at multiples of 15 minutes after 8:00.', '8:45 is 45 min later (3 × 15) ✓.', '9:10 is 70 min later (not a multiple of 15).', '9:30 is 90 min later (6 × 15) ✓.'],
    after: [7],
  },
  {
    n: 13, type: 'challenge', difficulty: 4,
    front: 'How many multiples of 7 are there from 1 to 100?',
    back: '14 (7, 14, …, 98)',
    steps: ['100 ÷ 7 = 14 with 2 left over.', 'So 7 × 14 = 98 is the last one.'],
    after: [7],
  },
  {
    n: 14, type: 'challenge', difficulty: 4,
    front: 'I am a multiple of 9, even, between 40 and 60, and my digits add to 9. What number am I?',
    back: '54',
    steps: ['Multiples of 9 between 40 and 60: 45, 54.', 'Even: 54.', 'Digit sum: 5 + 4 = 9 ✓'],
    after: [7],
  },
]);
