import { defineCards } from '@/content/defineCards';

export const fmPrimeFactorizationCards = defineCards('fm-prime-factorization', ['factors', 'prime-factorization'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What is prime factorization?',
    back: 'Writing a number as a product of prime numbers only.',
    example: '12 = 2 × 2 × 3',
    memoryHook: 'Every number can be broken down into prime building blocks.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'How do you make a factor tree?',
    back: 'Split the number into any two factors. Keep splitting every composite number you get until all the ends are prime. Multiply the primes at the ends.',
    example: '36 → 4 × 9 → (2 × 2) × (3 × 3), so 36 = 2 × 2 × 3 × 3',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'Does it matter how you start the factor tree?',
    back: 'No. Every number has exactly one prime factorization (the primes may appear in a different order).',
    example: '36 = 6 × 6 or 4 × 9 or 2 × 18 — they all end at 2 × 2 × 3 × 3.',
    after: [2],
  },
  {
    n: 4, type: 'visual', difficulty: 2,
    front: 'Read the prime factors from the ends of this tree. What is the prime factorization of 36?',
    back: '2 × 2 × 3 × 3',
    explanation: 'The yellow circles are primes. You can also write 36 = 2² × 3².',
    visual: {
      kind: 'factor-tree',
      root: { value: 36, children: [{ value: 4, children: [{ value: 2 }, { value: 2 }] }, { value: 9, children: [{ value: 3 }, { value: 3 }] }] },
    },
    after: [2],
  },
  {
    n: 5, type: 'solve', difficulty: 1,
    front: 'Write the prime factorization of 12.',
    back: '2 × 2 × 3',
    steps: ['12 = 3 × 4.', '3 is prime. 4 = 2 × 2.', '12 = 2 × 2 × 3.'],
    after: [2],
  },
  {
    n: 6, type: 'solve', difficulty: 2,
    front: 'Write the prime factorization of 30.',
    back: '2 × 3 × 5',
    steps: ['30 = 5 × 6.', '5 is prime. 6 = 2 × 3.'],
    after: [5],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: 'Write the prime factorization of 72.',
    back: '2 × 2 × 2 × 3 × 3 (or 2³ × 3²)',
    steps: ['72 = 8 × 9.', '8 = 2 × 2 × 2 and 9 = 3 × 3.', 'CHECK: 8 × 9 = 72 ✓'],
    after: [6],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'Write the prime factorization of 100.',
    back: '2 × 2 × 5 × 5',
    steps: ['100 = 10 × 10.', '10 = 2 × 5 each time.', '2 × 5 × 2 × 5 = 2 × 2 × 5 × 5.'],
    after: [6],
  },
  {
    n: 9, type: 'solve', difficulty: 4,
    front: 'Write the prime factorization of 210.',
    back: '2 × 3 × 5 × 7',
    steps: ['210 = 21 × 10.', '21 = 3 × 7 and 10 = 2 × 5.', 'All four are prime.'],
    after: [7],
  },
  {
    n: 10, type: 'misconception', difficulty: 5,
    front: 'True or False: 2 × 3 × 4 is the prime factorization of 24.',
    back: 'False. 4 is not prime. Keep splitting: 4 = 2 × 2, so 24 = 2 × 2 × 2 × 3.',
    commonMistake: 'Stopping before every factor is prime.',
    after: [3],
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'Two students factor 48 differently: one starts with 6 × 8 and the other with 4 × 12. Can both be right?',
    back: 'Yes. Both trees end at 2 × 2 × 2 × 2 × 3.',
    explanation: 'The prime factorization of a number is always the same, however you start.',
    after: [3],
  },
  {
    n: 12, type: 'real-life', difficulty: 3,
    front: 'A package has 45 granola bars. Write 45 as a product of primes, then list the equal-row arrangements possible.',
    back: '45 = 3 × 3 × 5. Arrangements: 1 × 45, 3 × 15 and 5 × 9.',
    steps: ['45 = 5 × 9 and 9 = 3 × 3.', 'Combine the primes to make factors: 3, 5, 3 × 3 = 9, 3 × 5 = 15.'],
    after: [7],
  },
  {
    n: 13, type: 'challenge', difficulty: 4,
    front: 'A number’s prime factorization is 2 × 2 × 3 × 7. What is the number?',
    back: '84',
    steps: ['2 × 2 = 4.', '4 × 3 = 12.', '12 × 7 = 84.'],
    after: [7],
  },
  {
    n: 14, type: 'challenge', difficulty: 4,
    front: 'What is the smallest number whose prime factorization has three different primes?',
    back: '30 (2 × 3 × 5)',
    hint: 'Use the three smallest primes.',
    after: [6],
  },
]);
