import { defineCards } from '@/content/defineCards';

export const mulEstimationCards = defineCards('mul-estimation', ['multiplication', 'estimation'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What does it mean to estimate a product?',
    back: 'Round the factors to friendly numbers, then multiply to get an answer that is close to the exact product.',
    memoryHook: 'Estimate first — it is your safety net for the exact answer.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'How do you estimate 48 × 31?',
    back: 'Round each factor to its greatest place: 48 ≈ 50 and 31 ≈ 30. Then 50 × 30 = 1,500.',
    rule: 'Round each factor to the nearest ten, hundred, … then multiply.',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'How do you quickly multiply friendly numbers like 40 × 300?',
    back: 'Multiply the non-zero digits (4 × 3 = 12), then write all the zeros from both factors after it: 12,000.',
    example: '40 has 1 zero and 300 has 2 zeros → 3 zeros in all.',
    after: [1],
  },
  {
    n: 4, type: 'visual', difficulty: 2,
    front: 'This rectangle estimates 48 × 31 by rounding to friendly numbers. What is the estimate?',
    back: '1,500',
    explanation: '50 × 30 = 1,500. The exact product, 1,488, is very close.',
    visual: { kind: 'area-model', cols: [{ label: '50', size: 50 }], rows: [{ label: '30', size: 30 }] },
    answerVisual: { kind: 'area-model', cols: [{ label: '50', size: 50 }], rows: [{ label: '30', size: 30 }], cells: [['1,500']] },
    after: [2],
  },
  {
    n: 5, type: 'solve', difficulty: 1,
    front: 'Estimate 19 × 4.',
    back: 'About 80',
    steps: ['19 ≈ 20.', '20 × 4 = 80.'],
    after: [2],
  },
  {
    n: 6, type: 'solve', difficulty: 2,
    front: 'Estimate 62 × 38.',
    back: 'About 2,400',
    steps: ['62 ≈ 60 and 38 ≈ 40.', '6 × 4 = 24, then add two zeros: 2,400.'],
    after: [3],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: 'Estimate 418 × 29.',
    back: 'About 12,000',
    steps: ['418 ≈ 400 and 29 ≈ 30.', '4 × 3 = 12, then add three zeros: 12,000.'],
    after: [3],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'Estimate 87 × 612.',
    back: 'About 54,000',
    steps: ['87 ≈ 90 and 612 ≈ 600.', '9 × 6 = 54, then add three zeros: 54,000.'],
    after: [7],
  },
  {
    n: 9, type: 'misconception', difficulty: 5,
    front: 'True or False: To estimate 18 × 22 you must round both numbers up.',
    back: 'False. Round each to the NEAREST friendly number: 18 ≈ 20 and 22 ≈ 20, so 20 × 20 = 400.',
    explanation: 'The exact product is 396, very close to 400.',
    after: [2],
  },
  {
    n: 10, type: 'misconception', difficulty: 5,
    front: 'Max says 40 × 300 = 1,200. How can you tell this is unreasonable?',
    back: 'He lost two zeros. 4 × 3 = 12, and there are 3 zeros in 40 × 300, so the answer is 12,000.',
    commonMistake: 'Forgetting to count the zeros in both factors.',
    after: [3],
  },
  {
    n: 11, type: 'real-life', difficulty: 3,
    front: 'A bakery sells 28 boxes a day with 12 cookies in each box. About how many cookies is that per day?',
    back: 'About 300 cookies',
    steps: ['28 ≈ 30 and 12 ≈ 10.', '30 × 10 = 300.'],
    explanation: 'The exact answer is 336, so 300 is a good estimate.',
    after: [6],
  },
  {
    n: 12, type: 'challenge', difficulty: 4,
    front: 'Without finding the exact answer, is 52 × 39 closer to 1,500, 2,000 or 2,500?',
    back: '2,000',
    steps: ['52 ≈ 50 and 39 ≈ 40.', '50 × 40 = 2,000.'],
    after: [6],
  },
  {
    n: 13, type: 'challenge', difficulty: 4,
    front: 'Pia estimated 61 × 39 as about 2,400, but she calculated 24,000 with the standard method. What probably went wrong?',
    back: 'She likely added an extra zero or misplaced a partial product. The exact answer is 2,379, close to 2,400.',
    hint: 'Compare the size of the two answers. How many times bigger is one?',
    after: [6],
  },
]);
