import { defineCards } from '@/content/defineCards';

export const mulStandardAlgorithmCards = defineCards('mul-standard-algorithm', ['multiplication', 'standard-algorithm'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What is the standard algorithm for multiplication?',
    back: 'A shortened vertical method: multiply by each digit of the bottom number from right to left, carrying when needed, and add the lines.',
    memoryHook: 'It is partial products in a compact outfit.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'What is carrying (regrouping) in multiplication?',
    back: 'When a digit product is 10 or more, write the ones digit and carry the tens to the next place. Add the carried amount after you multiply the next digit.',
    example: '46 × 7: 6 × 7 = 42 → write 2, carry 4. 4 × 7 = 28, plus 4 = 32.',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'In the standard algorithm, why do you write a 0 at the end of the second line?',
    back: 'The second line multiplies by the TENS digit, so every number in it is worth tens. The 0 holds the ones place.',
    after: [2],
  },
  {
    n: 4, type: 'visual', difficulty: 2,
    front: 'The model shows 46 × 7 as 280 + 42. How does this match carrying in the algorithm?',
    back: '6 × 7 = 42 → write 2 and carry 4 (4 tens). 4 tens × 7 = 28 tens, plus 4 = 32 tens. Together: 322.',
    explanation: 'The carried 4 is the tens in 42. The algorithm adds the two pieces as it goes.',
    visual: {
      kind: 'area-model',
      cols: [{ label: '40', size: 40 }, { label: '6', size: 6 }],
      rows: [{ label: '7', size: 7 }],
      cells: [['280', '42']],
      total: '280 + 42 = 322',
    },
    after: [2],
  },
  {
    n: 5, type: 'solve', difficulty: 1,
    front: '34 × 2 = ?',
    back: '68',
    steps: ['4 × 2 = 8 (no carry).', '3 × 2 = 6.', '68'],
    after: [1],
  },
  {
    n: 6, type: 'solve', difficulty: 2,
    front: '46 × 7 = ?',
    back: '322',
    steps: ['6 × 7 = 42 → write 2, carry 4.', '4 × 7 = 28, plus 4 = 32.', '322'],
    after: [2],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: '237 × 6 = ?',
    back: '1,422',
    steps: ['7 × 6 = 42 → write 2, carry 4.', '3 × 6 = 18, plus 4 = 22 → write 2, carry 2.', '2 × 6 = 12, plus 2 = 14.', '1,422'],
    after: [6],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: '58 × 36 = ?',
    back: '2,088',
    steps: ['58 × 6 = 348.', '58 × 30 = 1,740 (placeholder 0, then 58 × 3 = 174).', '348 + 1,740 = 2,088.'],
    after: [6, 3],
  },
  {
    n: 9, type: 'solve', difficulty: 4,
    front: '1,204 × 7 = ?',
    back: '8,428',
    steps: ['4 × 7 = 28 → write 8, carry 2.', '0 × 7 = 0, plus 2 = 2.', '2 × 7 = 14 → write 4, carry 1.', '1 × 7 = 7, plus 1 = 8.', '8,428'],
    after: [7],
  },
  {
    n: 10, type: 'misconception', difficulty: 5,
    front: 'Sam does 46 × 7 and writes 282: 6 × 7 = 42 (write 2, carry 4), then 4 × 7 = 28 and writes 28. What did he forget?',
    back: 'He forgot to add the carried 4. 28 + 4 = 32, so the answer is 322.',
    commonMistake: 'Forgetting to add the carry.',
    after: [6],
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'Tia finds 35 × 12 by writing 70 and 35 under each other in the ones column, then adding to get 105. What is wrong?',
    back: 'The second line is worth tens: 35 × 10 = 350. 70 + 350 = 420.',
    explanation: 'Always use the placeholder 0 for the tens-digit line.',
    after: [3],
  },
  {
    n: 12, type: 'real-life', difficulty: 3,
    front: 'A bus company drives 47 buses. Each bus travels 29 miles a day. How many miles in all?',
    back: '1,363 miles',
    steps: ['47 × 9 = 423', '47 × 20 = 940', '423 + 940 = 1,363', 'CHECK: 50 × 30 = 1,500 ✓'],
    after: [8],
  },
  {
    n: 13, type: 'challenge', difficulty: 4,
    front: 'Find the missing digit: 3■ × 4 = 148.',
    back: '7 (so 37 × 4 = 148)',
    hint: 'Divide 148 by 4, or think about what ends in 8 when multiplied by 4.',
    steps: ['148 ÷ 4 = 37.', 'CHECK: 7 × 4 = 28 (write 8, carry 2), 3 × 4 = 12 + 2 = 14 ✓'],
    after: [7],
  },
]);
