import { defineCards } from '@/content/defineCards';

export const algEquationsCards = defineCards('alg-equations', ['algebra', 'equations', 'solving'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What does it mean to solve an equation?',
    back: 'Find the value of the variable that makes the equation true. An equation is like a balanced scale: both sides must stay equal.',
    memoryHook: 'Whatever you do to one side, do to the other.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'How do you solve a one-step equation like x + 3 = 10?',
    back: 'Use the inverse operation on BOTH sides to get x alone: x + 3 − 3 = 10 − 3, so x = 7.',
    example: 'x + 3 = 10 → x = 7',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'What are the inverse operations?',
    back: 'Add ↔ subtract.   Multiply ↔ divide.',
    example: '3x = 12 → divide both sides by 3 → x = 4',
    after: [2],
  },
  {
    n: 4, type: 'rule', difficulty: 2,
    front: 'How do you check a solution?',
    back: 'Substitute the value for the variable. If both sides are equal, the solution is correct.',
    example: 'x = 7: 7 + 3 = 10 ✓',
    after: [3],
  },
  {
    n: 5, type: 'visual', difficulty: 1,
    front: 'The scale is balanced. The left side has a mystery block x and a 3. The right side has a 10. What is x?',
    back: '7',
    explanation: 'Take 3 away from both sides to keep it balanced: x = 10 − 3 = 7.',
    visual: { kind: 'balance', left: ['x', '3'], right: ['10'] },
    after: [2],
  },
  {
    n: 6, type: 'solve', difficulty: 1,
    front: 'x + 4 = 9. What is x?',
    back: '5',
    steps: ['Subtract 4 from both sides.', 'x = 9 − 4 = 5.', 'CHECK: 5 + 4 = 9 ✓'],
    after: [2],
  },
  {
    n: 7, type: 'solve', difficulty: 2,
    front: 'x − 6 = 11. What is x?',
    back: '17',
    steps: ['Add 6 to both sides.', 'x = 11 + 6 = 17.', 'CHECK: 17 − 6 = 11 ✓'],
    after: [3],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: '3x = 24. What is x?',
    back: '8',
    steps: ['Divide both sides by 3.', 'x = 24 ÷ 3 = 8.', 'CHECK: 3 × 8 = 24 ✓'],
    after: [7],
  },
  {
    n: 9, type: 'solve', difficulty: 3,
    front: 'x ÷ 5 = 7. What is x?',
    back: '35',
    steps: ['Multiply both sides by 5.', 'x = 7 × 5 = 35.', 'CHECK: 35 ÷ 5 = 7 ✓'],
    after: [7],
  },
  {
    n: 10, type: 'solve', difficulty: 3,
    front: '2x + 3 = 13. What is x?',
    back: '5',
    steps: ['Subtract 3 from both sides: 2x = 10.', 'Divide both sides by 2: x = 5.', 'CHECK: 2 × 5 + 3 = 13 ✓'],
    after: [8],
  },
  {
    n: 11, type: 'solve', difficulty: 4,
    front: '4x − 5 = 23. What is x?',
    back: '7',
    steps: ['Add 5 to both sides: 4x = 28.', 'Divide both sides by 4: x = 7.', 'CHECK: 4 × 7 − 5 = 23 ✓'],
    after: [10],
  },
  {
    n: 12, type: 'misconception', difficulty: 5,
    front: 'Ana solves x + 6 = 15 by adding 6 and gets x = 21. What went wrong?',
    back: 'She used the same operation instead of the inverse. Subtract 6 from both sides: x = 9.',
    commonMistake: 'Adding when she should have subtracted.',
    after: [6],
  },
  {
    n: 13, type: 'misconception', difficulty: 5,
    front: 'Ben solves 3x = 12 by multiplying by 3 and gets x = 36. What went wrong?',
    back: 'He should divide both sides by 3: x = 4.',
    after: [8],
  },
  {
    n: 14, type: 'real-life', difficulty: 3,
    front: 'Ana had x stickers, gave away 5, and has 12 left. Write an equation and solve it.',
    back: 'x − 5 = 12, so x = 17 stickers.',
    steps: ['Add 5 to both sides: x = 12 + 5 = 17.', 'CHECK: 17 − 5 = 12 ✓'],
    after: [7],
  },
  {
    n: 15, type: 'real-life', difficulty: 3,
    front: '4 friends share a bill equally and each pays $6. Write an equation for the total bill x and solve it.',
    back: 'x ÷ 4 = 6, so x = $24.',
    after: [9],
  },
  {
    n: 16, type: 'challenge', difficulty: 4,
    front: 'Ben has 3 bags with x marbles each, plus 4 loose marbles. He has 25 in all. Write an equation and find x.',
    back: '3x + 4 = 25, so x = 7 marbles per bag.',
    steps: ['Subtract 4 from both sides: 3x = 21.', 'Divide by 3: x = 7.'],
    after: [10],
  },
  {
    n: 17, type: 'challenge', difficulty: 4,
    front: 'Is x = 6 the solution of 2x + 5 = 17? Show how you know.',
    back: 'Yes. 2 × 6 + 5 = 12 + 5 = 17, so both sides are equal.',
    after: [10],
    steps: ['Replace x with 6: 2 × 6 + 5.', '12 + 5 = 17, which equals the right side.'],
  },
]);
