import { defineCards } from '@/content/defineCards';

export const algInputOutputCards = defineCards('alg-input-output', ['algebra', 'patterns', 'input-output'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What is a Math Machine (input/output table)?',
    back: 'A machine that follows a rule: you put a number IN, the rule changes it, and a new number comes OUT. A table lists the pairs.',
    example: '4 → × 3 → 12',
    memoryHook: 'Input → Rule → Output',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'How do you find the rule of a Math Machine?',
    back: 'Look at how each input becomes its output. Find a rule that works for EVERY row.',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'How do you use a rule to find a new output?',
    back: 'Put the new input through the rule.',
    example: 'Rule “+ 4”: input 10 → 10 + 4 = 14',
    after: [2],
  },
  {
    n: 4, type: 'visual', difficulty: 2,
    front: 'What is the rule of this machine?',
    back: '× 3',
    explanation: '2 → 6, 4 → 12 and 5 → 15. Each output is 3 times the input.',
    visual: { kind: 'math-machine', rule: '× 3', ruleHidden: true, pairs: [{ input: '2', output: '6' }, { input: '4', output: '12' }, { input: '5', output: '15' }] },
    answerVisual: { kind: 'math-machine', rule: '× 3', pairs: [{ input: '2', output: '6' }, { input: '4', output: '12' }, { input: '5', output: '15' }] },
    after: [2],
  },
  {
    n: 5, type: 'visual', difficulty: 2,
    front: 'Find the rule, then fill in the missing output for input 10.',
    back: 'Rule: + 5. Input 10 gives 15.',
    visual: { kind: 'math-machine', rule: '+ 5', ruleHidden: true, pairs: [{ input: '3', output: '8' }, { input: '7', output: '12' }, { input: '10', output: '?' }] },
    answerVisual: { kind: 'math-machine', rule: '+ 5', pairs: [{ input: '3', output: '8' }, { input: '7', output: '12' }, { input: '10', output: '15' }] },
    after: [4],
  },
  {
    n: 6, type: 'solve', difficulty: 1,
    front: 'The rule is × 2. What is the output for input 6?',
    back: '12',
    after: [3],
    explanation: 'Put 6 into the machine: 6 × 2 = 12.',
  },
  {
    n: 7, type: 'solve', difficulty: 2,
    front: 'Inputs 1, 2, 3, 4 give outputs 5, 6, 7, 8. What is the rule? What is the output for input 10?',
    back: 'The rule is + 4. Input 10 gives 14.',
    after: [2],
    steps: ['Each output is 4 more than its input.', '10 + 4 = 14.'],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'Inputs 2, 4, 6, 8 give outputs 1, 2, 3, 4. What is the rule? What is the output for input 20?',
    back: 'The rule is ÷ 2. Input 20 gives 10.',
    after: [7],
    steps: ['Each output is half of its input.', '20 ÷ 2 = 10.'],
  },
  {
    n: 9, type: 'solve', difficulty: 3,
    front: 'The rule is − 7. Find the outputs for inputs 12, 20 and 35.',
    back: '5, 13 and 28',
    steps: ['12 − 7 = 5.', '20 − 7 = 13.', '35 − 7 = 28.'],
    after: [6],
  },
  {
    n: 10, type: 'solve', difficulty: 4,
    front: 'Inputs 3, 5, 8 give outputs 7, 11, 17. Find the rule and the output for input 10.',
    back: 'The rule is × 2, then + 1. Input 10 gives 21.',
    steps: ['3 × 2 + 1 = 7 ✓', '5 × 2 + 1 = 11 ✓', '8 × 2 + 1 = 17 ✓', '10 × 2 + 1 = 21.'],
    after: [8],
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'Inputs 2, 3, 4 give outputs 6, 9, 12. Max says the rule is + 4 because 2 + 4 = 6. Is he right?',
    back: 'No. 3 + 4 = 7, not 9. The rule is × 3, which works for every row.',
    commonMistake: 'Only testing a rule on the first row.',
    after: [2],
  },
  {
    n: 12, type: 'misconception', difficulty: 5,
    front: 'True or False: A rule is correct if it works for the first row of the table.',
    back: 'False. A rule must work for every row.',
    after: [2],
  },
  {
    n: 13, type: 'real-life', difficulty: 3,
    front: 'Each tray holds 12 cookies. Use the rule × 12 to find how many cookies there are in 3 trays.',
    back: '36 cookies',
    after: [6],
  },
  {
    n: 14, type: 'challenge', difficulty: 4,
    front: 'Inputs 1, 2, 3 give outputs 4, 7, 10. Find the rule, then find the output for input 8.',
    back: 'The rule is × 3, then + 1. Input 8 gives 25.',
    steps: ['The outputs go up by 3, so the rule starts with × 3.', '1 × 3 = 3, and 4 is 1 more → + 1.', '8 × 3 + 1 = 25.'],
    after: [10],
  },
  {
    n: 15, type: 'challenge', difficulty: 4,
    front: 'A machine uses the rule × 5, then + 5. The output is 30. What was the input?',
    back: '5',
    hint: 'Work backwards: undo the last step first.',
    steps: ['Undo + 5: 30 − 5 = 25.', 'Undo × 5: 25 ÷ 5 = 5.', 'CHECK: 5 × 5 + 5 = 30 ✓'],
    after: [10],
  },
]);
