import { defineCards } from '@/content/defineCards';

export const algMissingNumbersCards = defineCards('alg-missing-numbers', ['algebra', 'missing-numbers'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What is a missing-number problem?',
    back: 'An equation with a box or a ? standing for a number you have to find.',
    example: '7 + ? = 12',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'How do you find a missing number?',
    back: 'Use the inverse operation. Missing part of an addition → subtract. Missing part of a multiplication → divide.',
    example: '7 + ? = 12 → ? = 12 − 7 = 5',
    memoryHook: 'Do and undo.',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'How do you check your answer?',
    back: 'Put it back in place of the box and see if the equation is true.',
    after: [2],
  },
  {
    n: 4, type: 'visual', difficulty: 1,
    front: 'The whole bar is 15 and one part is 9. Which equation matches, and what is the missing part?',
    back: '9 + ? = 15, so ? = 6.',
    visual: {
      kind: 'bar-model',
      total: '15',
      bars: [{ segments: [{ label: '9', size: 9 }, { label: '?', size: 6, tone: 'unknown' }] }],
    },
    after: [2],
  },
  {
    n: 5, type: 'solve', difficulty: 1,
    front: '7 + ? = 12',
    back: '5',
    steps: ['12 − 7 = 5.'],
    after: [2],
  },
  {
    n: 6, type: 'solve', difficulty: 2,
    front: '? − 8 = 9',
    back: '17',
    steps: ['Undo the subtraction by adding: 9 + 8 = 17.', 'CHECK: 17 − 8 = 9 ✓'],
    after: [3],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: '6 × ? = 54',
    back: '9',
    steps: ['Undo the multiplication by dividing: 54 ÷ 6 = 9.'],
    after: [3],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: '? ÷ 7 = 8',
    back: '56',
    steps: ['Undo the division by multiplying: 8 × 7 = 56.', 'CHECK: 56 ÷ 7 = 8 ✓'],
    after: [3],
  },
  {
    n: 9, type: 'solve', difficulty: 3,
    front: '100 − ? = 37',
    back: '63',
    steps: ['100 − 37 = 63.', 'CHECK: 100 − 63 = 37 ✓'],
    after: [6],
  },
  {
    n: 10, type: 'solve', difficulty: 4,
    front: '4 × ? + 3 = 27',
    back: '6',
    steps: ['Undo + 3: 27 − 3 = 24.', 'Undo × 4: 24 ÷ 4 = 6.', 'CHECK: 4 × 6 + 3 = 27 ✓'],
    after: [7],
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'Ben solves ? − 8 = 9 by doing 9 − 8 = 1. What is wrong?',
    back: 'The missing number is the starting amount, so undo the subtraction by ADDING: 9 + 8 = 17.',
    commonMistake: 'Using the same operation that is in the equation.',
    after: [6],
  },
  {
    n: 12, type: 'misconception', difficulty: 5,
    front: 'For 12 ÷ ? = 3, Mia answers 36 (12 × 3). What went wrong?',
    back: 'The missing number is the divisor. 12 ÷ 3 = 4, so ? = 4. CHECK: 12 ÷ 4 = 3 ✓',
    after: [8],
  },
  {
    n: 13, type: 'real-life', difficulty: 3,
    front: 'Mia had some marbles, got 8 more, and now has 21. Write an equation with a missing number and solve it.',
    back: '? + 8 = 21, so she had 13 marbles.',
    steps: ['Undo the addition: 21 − 8 = 13.'],
    after: [6],
  },
  {
    n: 14, type: 'challenge', difficulty: 4,
    front: 'Find the missing number: 5 × (? + 2) = 35.',
    back: '5',
    steps: ['Undo × 5: 35 ÷ 5 = 7.', '? + 2 = 7, so ? = 5.', 'CHECK: 5 × (5 + 2) = 35 ✓'],
    after: [10],
  },
  {
    n: 15, type: 'challenge', difficulty: 4,
    front: 'Both boxes hold the same number: ■ + ■ + 4 = 20. What is ■?',
    back: '8',
    steps: ['Undo + 4: 20 − 4 = 16.', 'Two equal boxes: 16 ÷ 2 = 8.', 'CHECK: 8 + 8 + 4 = 20 ✓'],
    after: [10],
  },
]);
