import { defineCards } from '@/content/defineCards';

export const algNumberPatternsCards = defineCards('alg-number-patterns', ['algebra', 'patterns'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What is a number pattern?',
    back: 'A list of numbers (called terms) that follow a rule.',
    example: '4, 8, 12, 16, … (the rule is “add 4”)',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'How do you find the rule of a number pattern?',
    back: 'Look at how each term changes from the one before it. Check whether you add, subtract or multiply by the same amount every time.',
    memoryHook: 'Test your rule on every term, not just the first two.',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'How do you describe a pattern completely?',
    back: 'Give the starting number and the rule.',
    example: 'Start at 3 and add 4: 3, 7, 11, 15, …',
    after: [2],
  },
  {
    n: 4, type: 'visual', difficulty: 2,
    front: 'The yellow numbers are a pattern. What is the rule, and what comes next after 27?',
    back: 'Start at 3 and add 4. The next term would be 31.',
    visual: { kind: 'number-grid', from: 1, to: 30, cols: 10, a: [3, 7, 11, 15, 19, 23, 27], labelA: 'pattern' },
    after: [2],
  },
  {
    n: 5, type: 'solve', difficulty: 1,
    front: 'What number comes next? 4, 8, 12, 16, ?',
    back: '20',
    steps: ['Each term is 4 more than the one before.', '16 + 4 = 20.'],
    after: [2],
  },
  {
    n: 6, type: 'solve', difficulty: 2,
    front: 'What comes next? 100, 90, 80, ?',
    back: '70',
    steps: ['The rule is subtract 10.'],
    after: [2],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: 'What comes next? 2, 6, 18, 54, ?',
    back: '162',
    steps: ['6 ÷ 2 = 3, 18 ÷ 6 = 3, 54 ÷ 18 = 3. The rule is multiply by 3.', '54 × 3 = 162.'],
    after: [6],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'A pattern starts at 5 and adds 4 each time: 5, 9, 13, 17, … What is the 10th term?',
    back: '41',
    steps: ['The 10th term takes 9 jumps from the 1st.', '5 + 9 × 4 = 5 + 36 = 41.'],
    after: [3],
  },
  {
    n: 9, type: 'solve', difficulty: 3,
    front: 'A pattern starts at 10 and subtracts 3: 10, 7, 4, … What is the first term that is less than 5?',
    back: '4',
    steps: ['10, 7, 4.', '7 is not less than 5, but 4 is.'],
    after: [6],
  },
  {
    n: 10, type: 'solve', difficulty: 4,
    front: 'Pattern A starts at 0 and adds 3. Pattern B starts at 0 and adds 6. List the first five terms of each. What do you notice?',
    back: 'A: 0, 3, 6, 9, 12. B: 0, 6, 12, 18, 24. Each B term is twice the matching A term.',
    after: [8],
    explanation: 'Pattern B jumps twice as far each time, so every B term is twice the matching A term.',
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'True or False: The pattern 2, 4, 7, 11 follows the rule “add 2 each time.”',
    back: 'False. The jumps are 2, 3, 4, … — they grow by 1 each time. The next term would be 16.',
    after: [2],
  },
  {
    n: 12, type: 'misconception', difficulty: 5,
    front: 'True or False: The pattern 5, 10, 20, 40 adds 5 each time.',
    back: 'False. Each term doubles: the rule is multiply by 2.',
    after: [2],
  },
  {
    n: 13, type: 'real-life', difficulty: 3,
    front: 'A plant is 12 cm tall and grows 3 cm every week. How tall will it be after 5 weeks?',
    back: '27 cm',
    steps: ['12, 15, 18, 21, 24, 27.', 'Or: 12 + 5 × 3 = 27.'],
    after: [8],
  },
  {
    n: 14, type: 'challenge', difficulty: 4,
    front: 'Look at the pattern 1, 4, 9, 16, … What is the 8th term?',
    back: '64',
    hint: 'These are square numbers: 1 × 1, 2 × 2, 3 × 3, …',
    steps: ['The 8th term is 8 × 8 = 64.'],
    after: [7],
  },
  {
    n: 15, type: 'challenge', difficulty: 4,
    front: 'Find the rule and the missing term: 3, ___, 27, 81, 243.',
    back: 'Multiply by 3. The missing term is 9.',
    steps: ['81 ÷ 27 = 3, 243 ÷ 81 = 3.', '3 × 3 = 9 and 9 × 3 = 27 ✓'],
    after: [7],
  },
]);
