import { defineCards } from '@/content/defineCards';

export const algTwoRulePatternsCards = defineCards('alg-two-rule-patterns', ['algebra', 'patterns', 'two-rules'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What is a two-rule pattern?',
    back: 'Two number patterns, each with its own rule, that you compare term by term.',
    example: 'Pattern A: start 0, add 2.   Pattern B: start 0, add 4.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'How do you compare two patterns?',
    back: 'List the terms of each pattern, pair up the matching terms, and look for a relationship (like “always twice as much” or “always 5 more”).',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'How can you write the matching terms as ordered pairs?',
    back: 'Write each pair as (term from A, term from B). These pairs can be plotted on a coordinate plane.',
    example: 'A: 0, 2, 4 and B: 0, 4, 8 → (0, 0), (2, 4), (4, 8)',
    after: [2],
  },
  {
    n: 4, type: 'visual', difficulty: 2,
    front: 'Rule A: start at 0, add 2. Rule B: start at 0, add 4. What does the table show about B compared with A?',
    back: 'Each B term is twice the matching A term.',
    visual: {
      kind: 'math-machine',
      rule: 'A → B',
      ruleHidden: true,
      pairs: [{ input: '0', output: '0' }, { input: '2', output: '4' }, { input: '4', output: '8' }, { input: '6', output: '12' }],
    },
    answerVisual: {
      kind: 'math-machine',
      rule: '× 2',
      pairs: [{ input: '0', output: '0' }, { input: '2', output: '4' }, { input: '4', output: '8' }, { input: '6', output: '12' }],
    },
    after: [2],
  },
  {
    n: 5, type: 'solve', difficulty: 1,
    front: 'Rule A: start at 0, add 2. Rule B: start at 0, add 4. List the first four terms of each.',
    back: 'A: 0, 2, 4, 6. B: 0, 4, 8, 12.',
    after: [2],
    explanation: 'Add 2 each time for A, and add 4 each time for B.',
  },
  {
    n: 6, type: 'solve', difficulty: 2,
    front: 'In the patterns above, how do the B terms compare with the A terms?',
    back: 'B is always twice A (4 is 2 × 2, 8 is 2 × 4, 12 is 2 × 6).',
    after: [5],
    explanation: 'B grows by 4 each step while A grows by 2, so B is always twice A.',
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: 'A: start at 0, add 3. B: start at 0, add 9. How many times as large is each B term as the matching A term?',
    back: '3 times as large.',
    steps: ['A: 0, 3, 6, 9. B: 0, 9, 18, 27.', '9 ÷ 3 = 3, 18 ÷ 6 = 3, 27 ÷ 9 = 3.'],
    after: [6],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'A: start at 0, add 5. B: start at 10, add 5. How do B terms compare with A terms?',
    back: 'Each B term is always 10 more than the matching A term.',
    steps: ['A: 0, 5, 10, 15. B: 10, 15, 20, 25.', 'B − A = 10 every time.'],
    after: [6],
  },
  {
    n: 9, type: 'solve', difficulty: 3,
    front: 'A: 0, 5, 10, 15 and B: 10, 15, 20, 25. Write the first three ordered pairs (A term, B term).',
    back: '(0, 10), (5, 15), (10, 20)',
    after: [3],
    explanation: 'Match the first term of A with the first term of B, and so on.',
  },
  {
    n: 10, type: 'solve', difficulty: 4,
    front: 'A: start at 0, add 4. B: start at 0, add 12. After 5 jumps, what are the two terms?',
    back: 'A is 20 and B is 60.',
    steps: ['A: 5 × 4 = 20.', 'B: 5 × 12 = 60.', 'B is 3 times A.'],
    after: [7],
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'A: start at 0, add 3. B: start at 0, add 6. Sam says B is always 3 more than A. Is he right?',
    back: 'No. The first jump differs by 3, but the third terms are 9 and 18 (9 more). B is always TWICE A.',
    commonMistake: 'Looking at only one pair of terms.',
    after: [6],
  },
  {
    n: 12, type: 'misconception', difficulty: 5,
    front: 'True or False: A relationship between two patterns only holds for the first few terms.',
    back: 'False. If the rules are consistent, the relationship holds for every pair of terms.',
    after: [6],
  },
  {
    n: 13, type: 'real-life', difficulty: 3,
    front: 'Ava saves $5 each week and Ben saves $10 each week. Both start with $0. How much does each have after 4 weeks, and how do they compare?',
    back: 'Ava $20, Ben $40. Ben has twice as much as Ava.',
    after: [7],
  },
  {
    n: 14, type: 'challenge', difficulty: 4,
    front: 'A: start at 0, add 6. B: start at 0, add 2. B is what fraction of A?',
    back: '1/3 of A',
    steps: ['A: 0, 6, 12, 18. B: 0, 2, 4, 6.', '2 is 1/3 of 6, 4 is 1/3 of 12, 6 is 1/3 of 18.'],
    after: [7],
  },
  {
    n: 15, type: 'challenge', difficulty: 4,
    front: 'A: start at 4, add 3. B: start at 8, add 6. Compare the first four terms.',
    back: 'A: 4, 7, 10, 13. B: 8, 14, 20, 26. Each B term is twice the matching A term.',
    after: [8],
    steps: ['A: 4, 7, 10, 13.', 'B: 8, 14, 20, 26.', '8 = 2 × 4, 14 = 2 × 7, 20 = 2 × 10, 26 = 2 × 13.'],
  },
]);
