import { defineCards } from '@/content/defineCards';

export const algVariablesCards = defineCards('alg-variables', ['algebra', 'variables'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What is a variable?',
    back: 'A letter that stands for a number that can change or that we don’t know yet.',
    example: 'In n + 5, the letter n could be 1, 2, 10, or any number.',
    memoryHook: 'A variable is a mystery number with a name.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'How do you write an expression with a variable?',
    back: 'Use a letter for the unknown number. Multiplication is written by putting the number next to the letter: 3n means 3 × n.',
    example: '“a number plus 5” → n + 5     “3 times a number” → 3n',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'How do you evaluate an expression with a variable?',
    back: 'Replace the letter with the number you are given, then follow the order of operations.',
    example: 'n + 5 when n = 4 → 4 + 5 = 9',
    after: [2],
  },
  {
    n: 4, type: 'visual', difficulty: 2,
    front: 'The bar has a mystery part n and a part of 5. Write an expression for the whole bar.',
    back: 'n + 5',
    visual: {
      kind: 'bar-model',
      total: '?',
      bars: [{ segments: [{ label: 'n', size: 4, tone: 'unknown' }, { label: '5', size: 5 }] }],
    },
    after: [2],
  },
  {
    n: 5, type: 'solve', difficulty: 1,
    front: 'Write an expression: a number n plus 7.',
    back: 'n + 7',
    after: [2],
    explanation: 'The letter n stands for the unknown number, and “plus 7” means + 7.',
  },
  {
    n: 6, type: 'solve', difficulty: 2,
    front: 'Evaluate 3n when n = 5.',
    back: '15',
    steps: ['3n means 3 × n.', '3 × 5 = 15.'],
    after: [3],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: 'Evaluate 2n + 4 when n = 6.',
    back: '16',
    steps: ['2 × 6 = 12.', '12 + 4 = 16.'],
    after: [6],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'Write an expression: 6 less than a number y.',
    back: 'y − 6',
    explanation: '“Less than” reverses the order: take 6 away from y.',
    after: [5],
  },
  {
    n: 9, type: 'solve', difficulty: 3,
    front: 'Evaluate (n + 3) × 2 when n = 4.',
    back: '14',
    steps: ['Parentheses: 4 + 3 = 7.', '7 × 2 = 14.'],
    after: [6],
  },
  {
    n: 10, type: 'solve', difficulty: 4,
    front: 'Evaluate 20 − 3n when n = 4. Then when n = 6.',
    back: '8 when n = 4, and 2 when n = 6.',
    steps: ['n = 4: 3 × 4 = 12 and 20 − 12 = 8.', 'n = 6: 3 × 6 = 18 and 20 − 18 = 2.'],
    after: [7],
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'Zoe says 3n means “3 and n side by side,” so when n = 5 it equals 35. Is she right?',
    back: 'No. 3n means 3 × n, so when n = 5 it is 15.',
    commonMistake: 'Writing digits next to each other instead of multiplying.',
    after: [3],
  },
  {
    n: 12, type: 'misconception', difficulty: 5,
    front: 'True or False: A variable has to be the letter x.',
    back: 'False. Any letter can be a variable: n, y, a, p …',
    after: [1],
  },
  {
    n: 13, type: 'real-life', difficulty: 3,
    front: 'Movie tickets cost $8 each. Write an expression for the cost of t tickets, then find the cost of 5 tickets.',
    back: '8t, and 8 × 5 = $40.',
    after: [6],
  },
  {
    n: 14, type: 'challenge', difficulty: 4,
    front: 'A pizza costs $12 plus $2 for each topping t. Write an expression for the cost and find the price with 3 toppings.',
    back: '12 + 2t. With 3 toppings: 12 + 2 × 3 = $18.',
    after: [7],
    steps: ['Each topping costs $2, so t toppings cost 2t.', 'Add the $12 base price: 12 + 2t.', 'With 3 toppings: 12 + 6 = 18.'],
  },
  {
    n: 15, type: 'challenge', difficulty: 4,
    front: 'Which of n = 2, 3 or 4 makes n + 3 equal to 2n?',
    back: 'n = 3. (3 + 3 = 6 and 2 × 3 = 6.)',
    steps: ['n = 2: 5 vs 4. No.', 'n = 3: 6 vs 6. Yes.', 'n = 4: 7 vs 8. No.'],
    after: [9],
  },
]);
