import { defineCards } from '@/content/defineCards';

export const exprEvaluateCards = defineCards('expr-evaluate', ['algebra', 'expressions', 'evaluating'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What does it mean to evaluate an expression?',
    back: 'To find its value by doing all the operations in the correct order.',
    memoryHook: 'Evaluate = turn the expression into one number.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'What is a good way to evaluate a long expression?',
    back: 'Rewrite the expression after each step, doing one operation at a time in the correct order. Never skip steps in your head when it is long.',
    example: '3 × (14 − 5) + 12 ÷ 4 → 3 × 9 + 12 ÷ 4 → 27 + 3 → 30',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'How can you check that your answer is reasonable?',
    back: 'Round the numbers and estimate the expression. Your exact answer should be close.',
    after: [2],
  },
  {
    n: 4, type: 'solve', difficulty: 1,
    front: '3 × (2 + 5) = ?',
    back: '21',
    steps: ['2 + 5 = 7.', '3 × 7 = 21.'],
    after: [2],
  },
  {
    n: 5, type: 'solve', difficulty: 2,
    front: '40 − 5 × 6 = ?',
    back: '10',
    steps: ['Multiply: 5 × 6 = 30.', 'Subtract: 40 − 30 = 10.'],
    after: [4],
  },
  {
    n: 6, type: 'solve', difficulty: 3,
    front: '3 × (14 − 5) + 12 ÷ 4 = ?',
    back: '30',
    steps: ['Parentheses: 14 − 5 = 9.', 'Multiply and divide: 3 × 9 = 27 and 12 ÷ 4 = 3.', 'Add: 27 + 3 = 30.'],
    after: [5],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: '[18 − (3 + 5)] × 2 = ?',
    back: '20',
    steps: ['Innermost: 3 + 5 = 8.', 'Brackets: 18 − 8 = 10.', 'Multiply: 10 × 2 = 20.'],
    after: [5],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: '2 × (3 + 4) × 5 = ?',
    back: '70',
    steps: ['3 + 4 = 7.', 'Left to right: 2 × 7 = 14, then 14 × 5 = 70.'],
    after: [5],
  },
  {
    n: 9, type: 'solve', difficulty: 4,
    front: '48 ÷ (2 × 4) + 7 × 2 = ?',
    back: '20',
    steps: ['Parentheses: 2 × 4 = 8.', 'Divide and multiply: 48 ÷ 8 = 6 and 7 × 2 = 14.', 'Add: 6 + 14 = 20.'],
    after: [6],
  },
  {
    n: 10, type: 'misconception', difficulty: 5,
    front: 'Zoe evaluates 3 + 4 × 2 + 1 as 15 (3 + 4 = 7, 7 × 2 = 14, 14 + 1). What is the correct value?',
    back: '12. Multiply first: 4 × 2 = 8. Then 3 + 8 + 1 = 12.',
    commonMistake: 'Working strictly left to right.',
    after: [5],
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'True or False: (4 + 5) × 2 has the same value as 4 + 5 × 2.',
    back: 'False. (4 + 5) × 2 = 18, but 4 + 5 × 2 = 14.',
    after: [4],
  },
  {
    n: 12, type: 'real-life', difficulty: 3,
    front: 'Movie tickets cost $9 for adults and $6 for children. Write and evaluate an expression for 3 adults and 2 children.',
    back: '3 × 9 + 2 × 6 = $39',
    steps: ['3 × 9 = 27 and 2 × 6 = 12.', '27 + 12 = 39.'],
    after: [6],
  },
  {
    n: 13, type: 'challenge', difficulty: 4,
    front: 'Evaluate 2 × (15 − 3 × 4) + 7.',
    back: '13',
    steps: ['Inside the parentheses, multiply first: 3 × 4 = 12.', '15 − 12 = 3.', '2 × 3 = 6, then 6 + 7 = 13.'],
    after: [7],
  },
  {
    n: 14, type: 'challenge', difficulty: 4,
    front: 'Estimate, then evaluate: 49 × 2 + 51 ÷ 3.',
    back: 'Estimate: 50 × 2 + 50 ÷ 3 ≈ 100 + 17 = 117. Exact: 98 + 17 = 115.',
    steps: ['49 × 2 = 98.', '51 ÷ 3 = 17.', '98 + 17 = 115.'],
    after: [6],
  },
]);
