import { defineCards } from '@/content/defineCards';

export const exprWordsToMathCards = defineCards('expr-words-to-math', ['algebra', 'expressions', 'translating'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'How do you turn words into a math expression?',
    back: 'Find the numbers and the operations in the words, and write them in the same order as the story. Use parentheses when a step has to happen first.',
    example: '“Add 7 and 5, then multiply by 3” → (7 + 5) × 3',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'Which words usually mean which operations?',
    back: 'Add, sum, plus, more than → +\nSubtract, difference, less than → −\nTimes, product, groups of → ×\nDivide, quotient, shared equally → ÷',
    memoryHook: 'Words are clues — check that the story makes sense.',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'When do you need parentheses in a translation?',
    back: 'When a phrase says to do something FIRST and then use the result: “the sum of”, “the difference of”, “… then multiply …”.',
    example: '“3 times the sum of 4 and 6” → 3 × (4 + 6)',
    after: [2],
  },
  {
    n: 4, type: 'solve', difficulty: 1,
    front: 'Write an expression: 5 more than 8.',
    back: '8 + 5',
    after: [2],
    explanation: '“More than” means add, so 5 more than 8 is 8 + 5.',
  },
  {
    n: 5, type: 'solve', difficulty: 2,
    front: 'Write an expression: 3 times the sum of 4 and 6.',
    back: '3 × (4 + 6)',
    steps: ['The sum of 4 and 6 is 4 + 6, which goes in parentheses.', 'Times 3: 3 × (4 + 6) = 30.'],
    after: [3],
  },
  {
    n: 6, type: 'solve', difficulty: 3,
    front: 'Write an expression: add 7 and 5, then multiply by 3. Then find its value.',
    back: '(7 + 5) × 3 = 36',
    steps: ['Add first: 7 + 5 = 12.', 'Multiply by 3: 12 × 3 = 36.'],
    after: [5],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: 'Write an expression: 20 divided by the difference of 9 and 5. Then find its value.',
    back: '20 ÷ (9 − 5) = 5',
    steps: ['The difference of 9 and 5 is 9 − 5 = 4.', '20 ÷ 4 = 5.'],
    after: [5],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'Say 2 × (8 + 3) in words.',
    back: 'Twice the sum of 8 and 3 (or: 2 times the sum of 8 and 3).',
    after: [5],
    explanation: '“Twice” means 2 times, and “the sum of 8 and 3” is the part in parentheses.',
  },
  {
    n: 9, type: 'solve', difficulty: 4,
    front: 'Write an expression: subtract 6 from 20, then divide by 7. Then find its value.',
    back: '(20 − 6) ÷ 7 = 2',
    steps: ['“Subtract 6 from 20” is 20 − 6 = 14.', '14 ÷ 7 = 2.'],
    after: [6],
  },
  {
    n: 10, type: 'misconception', difficulty: 5,
    front: 'True or False: “6 less than 15” is written 6 − 15.',
    back: 'False. “Less than” flips the order: 15 − 6.',
    commonMistake: 'Writing numbers in the order they are spoken.',
    after: [2],
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'True or False: “Add 7 and 5, then multiply by 3” can be written 7 + 5 × 3.',
    back: 'False. 7 + 5 × 3 = 22 because multiplication comes first. You need (7 + 5) × 3 = 36.',
    after: [6],
  },
  {
    n: 12, type: 'real-life', difficulty: 3,
    front: 'Sam buys 4 packs of 6 cards and then 3 single cards. Write an expression for the total number of cards and find its value.',
    back: '4 × 6 + 3 = 27',
    steps: ['4 packs of 6: 4 × 6 = 24.', 'Plus 3 more: 24 + 3 = 27.'],
    after: [4],
  },
  {
    n: 13, type: 'real-life', difficulty: 3,
    front: 'Mia has $20. She spends $4 on each of 3 snacks. Write an expression for what she has left and find its value.',
    back: '20 − 3 × 4 = $8',
    steps: ['3 snacks at $4: 3 × 4 = 12.', '20 − 12 = 8.'],
    after: [6],
  },
  {
    n: 14, type: 'challenge', difficulty: 4,
    front: 'Write an expression: double the sum of 5 and 8, then subtract 6. Find its value.',
    back: '2 × (5 + 8) − 6 = 20',
    steps: ['The sum of 5 and 8 is 13.', 'Double it: 2 × 13 = 26.', 'Subtract 6: 20.'],
    after: [9],
  },
]);
