import { defineCards } from '@/content/defineCards';

export const exprOrderOfOperationsCards = defineCards('expr-order-of-operations', ['algebra', 'expressions', 'order-of-operations'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What is the order of operations?',
    back: 'The rules that decide which operation to do first, so everyone gets the same answer: 1) Parentheses, 2) Multiply and divide (left to right), 3) Add and subtract (left to right).',
    memoryHook: 'Group first, then × ÷, then + −.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'What does “left to right” mean for operations at the same level?',
    back: 'When multiplication and division both appear, do whichever comes first from the left. The same goes for addition and subtraction.',
    example: '12 ÷ 3 × 2 = 4 × 2 = 8   (not 12 ÷ 6)',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'Why does multiplication come before addition?',
    back: 'Multiplication is a shortcut for repeated addition, so it groups numbers into one amount first.',
    example: '2 + 3 × 4 means 2 plus four 3s.',
    after: [1],
  },
  {
    n: 4, type: 'visual', difficulty: 2,
    front: 'The bar shows 2 plus four groups of 3. Write the expression and find its value.',
    back: '2 + 3 × 4 = 14',
    explanation: 'The four 3s make 12 first. Then 2 + 12 = 14.',
    visual: {
      kind: 'bar-model',
      total: '?',
      bars: [{ segments: [{ label: '2', size: 2, tone: 'empty' }, ...Array.from({ length: 4 }, () => ({ label: '3', size: 3 }))] }],
    },
    after: [3],
  },
  {
    n: 5, type: 'solve', difficulty: 1,
    front: '2 + 3 × 4 = ?',
    back: '14',
    steps: ['Multiply first: 3 × 4 = 12.', 'Then add: 2 + 12 = 14.'],
    after: [3],
  },
  {
    n: 6, type: 'solve', difficulty: 2,
    front: '20 − 6 ÷ 2 = ?',
    back: '17',
    steps: ['Divide first: 6 ÷ 2 = 3.', 'Then subtract: 20 − 3 = 17.'],
    after: [5],
  },
  {
    n: 7, type: 'solve', difficulty: 2,
    front: '12 ÷ 3 × 2 = ?',
    back: '8',
    steps: ['Left to right: 12 ÷ 3 = 4.', 'Then 4 × 2 = 8.'],
    after: [2],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: '8 + 4 × (6 − 2) = ?',
    back: '24',
    steps: ['Parentheses: 6 − 2 = 4.', 'Multiply: 4 × 4 = 16.', 'Add: 8 + 16 = 24.'],
    after: [6],
  },
  {
    n: 9, type: 'solve', difficulty: 3,
    front: '30 − 12 ÷ 4 + 5 = ?',
    back: '32',
    steps: ['Divide: 12 ÷ 4 = 3.', 'Left to right: 30 − 3 = 27, then 27 + 5 = 32.'],
    after: [7],
  },
  {
    n: 10, type: 'solve', difficulty: 3,
    front: '(5 + 7) × 2 − 10 ÷ 5 = ?',
    back: '22',
    steps: ['Parentheses: 5 + 7 = 12.', 'Multiply and divide: 12 × 2 = 24 and 10 ÷ 5 = 2.', 'Subtract: 24 − 2 = 22.'],
    after: [8],
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'True or False: 2 + 3 × 4 = 20 because you work left to right.',
    back: 'False. Multiply first: 3 × 4 = 12, then 2 + 12 = 14.',
    commonMistake: 'Doing addition before multiplication.',
    after: [3],
  },
  {
    n: 12, type: 'misconception', difficulty: 5,
    front: 'True or False: Multiplication always comes before division, so 12 ÷ 3 × 2 = 12 ÷ 6 = 2.',
    back: 'False. Multiplication and division are done left to right: 12 ÷ 3 = 4, then 4 × 2 = 8.',
    after: [7],
  },
  {
    n: 13, type: 'misconception', difficulty: 5,
    front: 'True or False: Addition always comes before subtraction, so 10 − 4 + 3 = 10 − 7 = 3.',
    back: 'False. Addition and subtraction go left to right: 10 − 4 = 6, then 6 + 3 = 9.',
    after: [9],
  },
  {
    n: 14, type: 'real-life', difficulty: 3,
    front: 'Pens cost $2 each. You buy 4 pens and a $5 notebook. Write an expression for the total and solve it.',
    back: '4 × 2 + 5 = $13',
    steps: ['Multiply first: 4 × 2 = 8.', 'Then add: 8 + 5 = 13.'],
    after: [8],
  },
  {
    n: 15, type: 'challenge', difficulty: 4,
    front: 'Which has the greater value: 6 + 3 × 5 or (6 + 3) × 5?',
    back: '(6 + 3) × 5 = 45 is greater than 6 + 3 × 5 = 21.',
    after: [8],
    steps: ['6 + 3 × 5: multiply first, 3 × 5 = 15, then 6 + 15 = 21.', '(6 + 3) × 5: parentheses first, 9 × 5 = 45.'],
  },
  {
    n: 16, type: 'challenge', difficulty: 4,
    front: 'Fill in the blanks with + − × or ÷ so that 6 ○ 2 ○ 3 = 9.',
    back: '6 × 2 − 3 = 9',
    steps: ['Multiply first: 6 × 2 = 12.', '12 − 3 = 9.'],
    after: [9],
  },
]);
