import { defineCards } from '@/content/defineCards';

export const exprParenthesesCards = defineCards('expr-parentheses', ['algebra', 'expressions', 'parentheses'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What do parentheses do in a math expression?',
    back: 'They group part of the expression together. Do the work inside the parentheses first.',
    example: '(3 + 4) × 2 = 7 × 2 = 14',
    memoryHook: 'Parentheses are a hug: whatever is inside goes together first.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'Do parentheses change the answer?',
    back: 'Yes. They change which operation happens first.',
    example: '3 + 4 × 2 = 11 but (3 + 4) × 2 = 14',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'What if there are parentheses inside brackets, like [4 + (8 − 2)] × 3?',
    back: 'Work from the innermost grouping outward: (8 − 2) first, then the brackets, then the rest.',
    after: [2],
  },
  {
    n: 4, type: 'visual', difficulty: 2,
    front: 'The bars show three groups, each made of 7 and 5. Write an expression for the total and find its value.',
    back: '(7 + 5) × 3 = 36',
    explanation: 'Each group is 7 + 5 = 12. Three groups of 12 make 36.',
    visual: {
      kind: 'bar-model',
      total: '?',
      bars: [{ segments: Array.from({ length: 3 }, () => ({ label: '7 + 5', size: 12 })) }],
    },
    after: [2],
  },
  {
    n: 5, type: 'solve', difficulty: 1,
    front: '(2 + 3) × 4 = ?',
    back: '20',
    steps: ['Parentheses first: 2 + 3 = 5.', '5 × 4 = 20.'],
    after: [2],
  },
  {
    n: 6, type: 'solve', difficulty: 2,
    front: '18 − (6 + 4) = ?',
    back: '8',
    steps: ['Parentheses first: 6 + 4 = 10.', '18 − 10 = 8.'],
    after: [2],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: '3 × (12 − 7) + 2 = ?',
    back: '17',
    steps: ['Parentheses: 12 − 7 = 5.', 'Multiply: 3 × 5 = 15.', 'Add: 15 + 2 = 17.'],
    after: [6],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: '[4 + (8 − 2)] × 3 = ?',
    back: '30',
    steps: ['Innermost: 8 − 2 = 6.', 'Brackets: 4 + 6 = 10.', '10 × 3 = 30.'],
    after: [3],
  },
  {
    n: 9, type: 'solve', difficulty: 3,
    front: '50 ÷ (3 + 2) = ?',
    back: '10',
    steps: ['3 + 2 = 5.', '50 ÷ 5 = 10.'],
    after: [6],
  },
  {
    n: 10, type: 'misconception', difficulty: 5,
    front: 'True or False: (2 + 3) × 4 has the same value as 2 + 3 × 4.',
    back: 'False. (2 + 3) × 4 = 20, but 2 + 3 × 4 = 2 + 12 = 14.',
    after: [2],
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'Ana calculates 18 − (6 + 4) as 18 − 6 + 4 = 16. What is wrong?',
    back: 'She ignored the parentheses. 6 + 4 = 10 first, so 18 − 10 = 8.',
    commonMistake: 'Dropping parentheses and working left to right.',
    after: [6],
  },
  {
    n: 12, type: 'real-life', difficulty: 3,
    front: '3 friends each buy a $4 sandwich and a $2 drink. Write an expression for the total cost and find its value.',
    back: '3 × (4 + 2) = $18',
    steps: ['One friend pays 4 + 2 = 6.', 'Three friends: 3 × 6 = 18.'],
    after: [7],
  },
  {
    n: 13, type: 'challenge', difficulty: 4,
    front: 'Add parentheses so that 2 + 3 × 4 equals 20.',
    back: '(2 + 3) × 4 = 20',
    after: [7],
    steps: ['Without parentheses: 3 × 4 = 12, so 2 + 12 = 14.', 'Group the 2 + 3 first: (2 + 3) × 4 = 5 × 4 = 20.'],
  },
  {
    n: 14, type: 'challenge', difficulty: 4,
    front: 'Add parentheses so that 24 ÷ 4 + 2 equals 4.',
    back: '24 ÷ (4 + 2) = 4',
    steps: ['Without parentheses: 24 ÷ 4 + 2 = 6 + 2 = 8.', 'With them: 4 + 2 = 6 first, then 24 ÷ 6 = 4.'],
    after: [9],
  },
]);
