import { defineCards } from '@/content/defineCards';

export const timesTableStrategyCards = defineCards('tt-strategies', ['times-tables', 'strategies'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What does 7 × 8 mean?',
    back: '7 groups of 8 — or 8 groups of 7. Both make 56.',
    memoryHook: 'Times means “groups of.”',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'What is the turnaround rule, and why does it help?',
    back: 'a × b = b × a. If you know 7 × 8, you also know 8 × 7 — so there are only about half as many facts to learn.',
    example: '8 × 13 = 13 × 8 = 104',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'How do you multiply by a big number like 13, 14 or 15?',
    back: 'Split it into 10 and a small number. Multiply each part, then add.',
    example: '13 × 6 = (10 × 6) + (3 × 6) = 60 + 18 = 78',
    memoryHook: 'Break big facts into friendly ones.',
    after: [2],
  },
  {
    n: 4, type: 'rule', difficulty: 2,
    front: 'Which tables can you build from doubling and halving?',
    back: '× 2 is double. × 4 is double, double. × 8 is double, double, double. × 5 is half of × 10.',
    example: '8 × 7 → 14 → 28 → 56',
    after: [1],
  },
  {
    n: 5, type: 'visual', difficulty: 1,
    front: 'Use the area model to find 13 × 6.',
    back: '78',
    explanation: 'The 10 part gives 60 and the 3 part gives 18. 60 + 18 = 78.',
    visual: {
      kind: 'area-model',
      cols: [{ label: '10', size: 10 }, { label: '3', size: 3 }],
      rows: [{ label: '6', size: 6 }],
    },
    answerVisual: {
      kind: 'area-model',
      cols: [{ label: '10', size: 10 }, { label: '3', size: 3 }],
      rows: [{ label: '6', size: 6 }],
      cells: [['60', '18']],
      total: '60 + 18 = 78',
    },
    after: [3],
  },
  {
    n: 6, type: 'visual', difficulty: 2,
    front: 'This array has 3 rows of 8. Which two multiplication facts does it show?',
    back: '3 × 8 = 24 and 8 × 3 = 24',
    explanation: 'Turn the array on its side and it becomes 8 rows of 3 — the same 24 squares.',
    visual: { kind: 'shaded-grid', rows: 3, cols: 8, shaded: 24 },
    after: [2],
  },
  {
    n: 7, type: 'visual', difficulty: 2,
    front: 'These highlighted numbers are special. What do they have in common?',
    back: 'They are square numbers: 1 × 1, 2 × 2, 3 × 3, … 10 × 10.',
    explanation: 'A square number of dots can be arranged into a perfect square.',
    visual: { kind: 'number-grid', from: 1, to: 100, cols: 10, a: [1, 4, 9, 16, 25, 36, 49, 64, 81, 100] },
    after: [1],
  },
  {
    n: 8, type: 'solve', difficulty: 2,
    front: 'Use the split strategy: 12 × 7 = ?',
    back: '84',
    steps: ['12 = 10 + 2.', '10 × 7 = 70 and 2 × 7 = 14.', '70 + 14 = 84.'],
    after: [3],
  },
  {
    n: 9, type: 'solve', difficulty: 3,
    front: 'Use doubling: 8 × 14 = ?',
    back: '112',
    steps: ['14 × 2 = 28.', '28 × 2 = 56.', '56 × 2 = 112.'],
    after: [4],
  },
  {
    n: 10, type: 'solve', difficulty: 3,
    front: 'Use “× 10 take away one group”: 9 × 13 = ?',
    back: '117',
    steps: ['13 × 10 = 130.', '130 − 13 = 117.'],
    after: [8],
  },
  {
    n: 11, type: 'solve', difficulty: 3,
    front: 'Use “× 10 plus half”: 15 × 6 = ?',
    back: '90',
    steps: ['6 × 10 = 60.', 'Half of 60 is 30.', '60 + 30 = 90.'],
    after: [8],
  },
  {
    n: 12, type: 'misconception', difficulty: 5,
    front: 'Ali says 13 × 4 = 10 × 4 + 3 = 43. What did he forget?',
    back: 'He split 13 into 10 + 3 but only multiplied the 10. Both parts must be multiplied: 40 + 12 = 52.',
    commonMistake: 'Multiplying only one part of a split number.',
    after: [3],
  },
  {
    n: 13, type: 'misconception', difficulty: 5,
    front: 'True or False: 11 × 12 = 1212, because the 11s trick repeats the digits.',
    back: 'False. The repeat trick only works for 11 × 2 up to 11 × 9. 11 × 12 = 120 + 12 = 132.',
    after: [3],
  },
  {
    n: 14, type: 'real-life', difficulty: 3,
    front: 'A carton holds 12 eggs. How many eggs are in 14 cartons?',
    back: '168 eggs',
    steps: ['12 × 14: split 14 into 10 + 4.', '12 × 10 = 120 and 12 × 4 = 48.', '120 + 48 = 168.'],
    after: [8],
  },
  {
    n: 15, type: 'challenge', difficulty: 4,
    front: 'Find 15 × 15 in two different ways.',
    back: '225',
    steps: ['Split: 15 × 10 = 150 and 15 × 5 = 75, so 150 + 75 = 225.', 'Or: 15 × 15 = 15 × 10 plus half of that again: 150 + 75 = 225.'],
    after: [11],
  },
  {
    n: 16, type: 'challenge', difficulty: 4,
    front: 'Which facts in the tables up to 15 × 15 have the answer 36?',
    back: '3 × 12, 4 × 9 and 6 × 6 (plus the turnarounds 12 × 3 and 9 × 4).',
    hint: 'List the factor pairs of 36 and keep the ones where both factors are between 2 and 15.',
    after: [8],
  },
]);
