import { defineCards } from '@/content/defineCards';

export const decAddCards = defineCards('dec-add', ['decimals', 'addition'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What is the main idea when adding decimals?',
    back: 'Add tenths to tenths, hundredths to hundredths, and so on. Line up the places so only like places are added.',
    memoryHook: 'Line up the decimal points like buttons on a shirt.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'What are the steps for adding decimals?',
    back: '1) Line up the decimal points.\n2) Fill empty places with zeros.\n3) Add as with whole numbers, right to left, regrouping when needed.\n4) Bring the decimal point straight down.',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'How do you add a whole number and a decimal?',
    back: 'Write the whole number with a decimal point and zeros: 7 = 7.00. Then line up the points and add.',
    after: [2],
  },
  {
    n: 4, type: 'visual', difficulty: 2,
    front: 'Add the two parts of the bar. What is 3.45 + 2.3?',
    back: '5.75',
    steps: ['3.45 + 2.30 = 5.75'],
    visual: {
      kind: 'bar-model',
      total: '?',
      bars: [{ segments: [{ label: '3.45', size: 3.45 }, { label: '2.3', size: 2.3, tone: 'empty' }] }],
    },
    after: [2],
  },
  {
    n: 5, type: 'solve', difficulty: 1,
    front: '0.3 + 0.4 = ?',
    back: '0.7',
    after: [1],
    explanation: '3 tenths + 4 tenths = 7 tenths.',
  },
  {
    n: 6, type: 'solve', difficulty: 2,
    front: '2.5 + 3.75 = ?',
    back: '6.25',
    steps: ['2.50 + 3.75 = 6.25.'],
    after: [2],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: '12.4 + 8.67 = ?',
    back: '21.07',
    steps: ['12.40 + 8.67 = 21.07.', 'CHECK: about 12 + 9 = 21 ✓'],
    after: [6],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: '0.85 + 0.6 = ?',
    back: '1.45',
    steps: ['0.85 + 0.60 = 1.45.', '85 + 60 hundredths = 145 hundredths.'],
    after: [6],
  },
  {
    n: 9, type: 'solve', difficulty: 3,
    front: '7 + 0.45 = ?',
    back: '7.45',
    steps: ['7 = 7.00.', '7.00 + 0.45 = 7.45.'],
    after: [3],
  },
  {
    n: 10, type: 'solve', difficulty: 4,
    front: '14.206 + 3.9 = ?',
    back: '18.106',
    steps: ['3.9 = 3.900.', '14.206 + 3.900 = 18.106.'],
    after: [7],
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'Ben lines up 2.5 + 0.75 on the right edge and adds 25 + 75 to get 1.00. What went wrong?',
    back: 'He lined up the last digits instead of the decimal points. 2.50 + 0.75 = 3.25.',
    commonMistake: 'Aligning the right edge.',
    after: [2],
  },
  {
    n: 12, type: 'misconception', difficulty: 5,
    front: 'True or False: 6.4 + 3 = 6.7.',
    back: 'False. The 3 is 3 wholes, not 3 tenths. 6.4 + 3.0 = 9.4.',
    after: [3],
  },
  {
    n: 13, type: 'real-life', difficulty: 3,
    front: 'Ava buys items that cost $3.49 and $2.75. What is her total?',
    back: '$6.24',
    after: [7],
  },
  {
    n: 14, type: 'challenge', difficulty: 4,
    front: 'Estimate, then add: 4.8 + 6.1 + 2.95.',
    back: 'Estimate: 5 + 6 + 3 = 14. Exact: 13.85.',
    steps: ['4.80 + 6.10 = 10.90.', '10.90 + 2.95 = 13.85.'],
    after: [7],
  },
  {
    n: 15, type: 'challenge', difficulty: 4,
    front: 'Find the missing number: 3.6 + ___ = 5.25.',
    back: '1.65',
    steps: ['Undo the addition: 5.25 − 3.60 = 1.65.', 'CHECK: 3.60 + 1.65 = 5.25 ✓'],
    after: [8],
  },
]);
