import { defineCards } from '@/content/defineCards';

export const decDivideCards = defineCards('dec-divide', ['decimals', 'division'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'How is dividing decimals like dividing whole numbers?',
    back: 'The steps are the same. You just place the decimal point correctly in the quotient.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'How do you divide a decimal by a whole number?',
    back: 'Divide as usual and put the decimal point in the quotient directly above the decimal point in the dividend. Add zeros to the dividend if needed.',
    example: '8.4 ÷ 4 = 2.1',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'How do you divide by a decimal?',
    back: 'Multiply the divisor and dividend by 10, 100, … to make the divisor a whole number, then divide.',
    example: '12 ÷ 0.4 → 120 ÷ 4 = 30',
    memoryHook: 'Both numbers move the same number of places, so the answer stays the same.',
    after: [2],
  },
  {
    n: 4, type: 'visual', difficulty: 2,
    front: 'A 4.8 m ribbon is cut into 4 equal pieces. How long is each piece?',
    back: '1.2 m',
    explanation: '4.8 ÷ 4 = 1.2. Check: 4 × 1.2 = 4.8.',
    visual: {
      kind: 'bar-model',
      total: '4.8 m',
      bars: [{ segments: Array.from({ length: 4 }, () => ({ label: '?', size: 1, tone: 'unknown' as const })) }],
    },
    after: [2],
  },
  {
    n: 5, type: 'solve', difficulty: 1,
    front: '6.4 ÷ 2 = ?',
    back: '3.2',
    after: [2],
    explanation: '6 ÷ 2 = 3 and 0.4 ÷ 2 = 0.2, so the answer is 3.2.',
  },
  {
    n: 6, type: 'solve', difficulty: 2,
    front: '7.5 ÷ 5 = ?',
    back: '1.5',
    steps: ['7 ÷ 5 = 1 R 2.', 'Decimal point, then 25 ÷ 5 = 5.', '1.5'],
    after: [2],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: '0.84 ÷ 4 = ?',
    back: '0.21',
    steps: ['84 ÷ 4 = 21.', 'Two decimal places in the dividend: 0.21.'],
    after: [6],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: '12 ÷ 0.4 = ?',
    back: '30',
    steps: ['Multiply both by 10: 120 ÷ 4.', '120 ÷ 4 = 30.'],
    after: [3],
  },
  {
    n: 9, type: 'solve', difficulty: 3,
    front: '3.6 ÷ 0.09 = ?',
    back: '40',
    steps: ['Multiply both by 100: 360 ÷ 9.', '360 ÷ 9 = 40.'],
    after: [8],
  },
  {
    n: 10, type: 'solve', difficulty: 4,
    front: '7 ÷ 8 = ? (Write a decimal.)',
    back: '0.875',
    steps: ['7 = 7.000.', '70 ÷ 8 = 8 R 6; 60 ÷ 8 = 7 R 4; 40 ÷ 8 = 5.', '0.875'],
    after: [7],
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'True or False: 6 ÷ 0.5 = 3.',
    back: 'False. 6 ÷ 0.5 = 12, because 12 halves fit in 6. Dividing by a number less than 1 makes the answer bigger.',
    after: [3],
  },
  {
    n: 12, type: 'misconception', difficulty: 5,
    front: 'True or False: 0.8 ÷ 4 = 2.',
    back: 'False. 0.8 ÷ 4 = 0.2. The decimal point was lost.',
    explanation: 'Check: 4 × 0.2 = 0.8.',
    after: [2],
  },
  {
    n: 13, type: 'real-life', difficulty: 3,
    front: '6 friends share a $7.20 bill equally. How much does each pay?',
    back: '$1.20',
    steps: ['7.20 ÷ 6 = 1.20.', 'CHECK: 6 × 1.20 = 7.20 ✓'],
    after: [6],
  },
  {
    n: 14, type: 'challenge', difficulty: 4,
    front: 'A 5.4 m rope is cut into pieces 0.6 m long. How many pieces?',
    back: '9 pieces',
    steps: ['5.4 ÷ 0.6 → 54 ÷ 6 = 9.', 'CHECK: 9 × 0.6 = 5.4 ✓'],
    after: [8],
  },
  {
    n: 15, type: 'challenge', difficulty: 4,
    front: 'Check 4.2 ÷ 0.07 = 60 using multiplication.',
    back: '60 × 0.07 = 4.2 ✓ It is correct.',
    after: [9],
    steps: ['Multiply both by 100: 420 ÷ 7 = 60.', 'CHECK: 60 × 0.07 = 4.2 ✓'],
  },
]);
