import { defineCards } from '@/content/defineCards';

export const decMultiplyCards = defineCards('dec-multiply', ['decimals', 'multiplication'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'How do you multiply decimals?',
    back: 'Multiply as if they were whole numbers, then place the decimal point in the product.',
    memoryHook: 'Ignore the points, multiply, then put the point back.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'Where does the decimal point go in the product?',
    back: 'Count the total number of decimal places in both factors. The product has that many decimal places.',
    example: '0.4 × 0.3 → 4 × 3 = 12 → 1 + 1 = 2 places → 0.12',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'How can you check that the decimal point is in the right place?',
    back: 'Estimate with rounded numbers. The product should be close to the estimate.',
    example: '3.9 × 2.1 ≈ 4 × 2 = 8, so 8.19 makes sense (not 81.9 or 0.819).',
    after: [2],
  },
  {
    n: 4, type: 'visual', difficulty: 2,
    front: 'Yellow rows show 0.4 (4 of 10 rows) and blue columns show 0.3 (3 of 10 columns). What is 0.4 × 0.3?',
    back: '0.12',
    explanation: 'The green overlap has 4 × 3 = 12 squares out of 100, which is 12 hundredths.',
    visual: { kind: 'fraction-area-model', rows: 10, cols: 10, shadeRows: 4, shadeCols: 3 },
    after: [2],
  },
  {
    n: 5, type: 'solve', difficulty: 1,
    front: '0.2 × 3 = ?',
    back: '0.6',
    steps: ['2 tenths × 3 = 6 tenths.'],
    after: [1],
  },
  {
    n: 6, type: 'solve', difficulty: 2,
    front: '0.5 × 0.4 = ?',
    back: '0.2',
    steps: ['5 × 4 = 20.', 'Two decimal places: 0.20 = 0.2.'],
    after: [2],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: '1.2 × 3.5 = ?',
    back: '4.2',
    steps: ['12 × 35 = 420.', 'Two decimal places: 4.20 = 4.2.', 'CHECK: about 1 × 4 = 4 ✓'],
    after: [6],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: '0.07 × 0.8 = ?',
    back: '0.056',
    steps: ['7 × 8 = 56.', 'Three decimal places in all (2 + 1): 0.056.'],
    after: [6],
  },
  {
    n: 9, type: 'solve', difficulty: 3,
    front: '2.5 × 4.2 = ?',
    back: '10.5',
    steps: ['25 × 42 = 1,050.', 'Two decimal places: 10.50 = 10.5.'],
    after: [7],
  },
  {
    n: 10, type: 'solve', difficulty: 4,
    front: '12.5 × 0.04 = ?',
    back: '0.5',
    steps: ['125 × 4 = 500.', 'Three decimal places (1 + 2): 0.500 = 0.5.'],
    after: [8],
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'Max says 0.3 × 0.2 = 0.6. What is wrong?',
    back: 'He forgot the decimal places. 3 × 2 = 6 and there are 2 places, so 0.06.',
    explanation: 'Also use sense: a part of a part is smaller than both, so the answer must be less than 0.2.',
    after: [2],
  },
  {
    n: 12, type: 'misconception', difficulty: 5,
    front: 'True or False: To multiply decimals you line up the decimal points, like in addition.',
    back: 'False. You only line up decimal points to add or subtract. To multiply, count the decimal places.',
    after: [2],
  },
  {
    n: 13, type: 'real-life', difficulty: 3,
    front: 'Gas costs $3.50 per gallon. How much do 8.2 gallons cost?',
    back: '$28.70',
    steps: ['35 × 82 = 2,870.', 'Three decimal places in all: 28.70.', 'CHECK: about 3.5 × 8 = 28 ✓'],
    after: [7],
  },
  {
    n: 14, type: 'challenge', difficulty: 4,
    front: 'Estimate, then solve: 4.8 × 2.5.',
    back: 'Estimate: 5 × 2.5 = 12.5. Exact: 12.',
    steps: ['48 × 25 = 1,200.', 'Two decimal places: 12.00 = 12.'],
    after: [9],
  },
  {
    n: 15, type: 'challenge', difficulty: 4,
    front: 'A rectangle is 3.5 m long and 2.4 m wide. What is its area?',
    back: '8.4 square meters',
    steps: ['35 × 24 = 840.', 'Two decimal places: 8.40 = 8.4.'],
    after: [9],
  },
]);
