import { defineCards } from '@/content/defineCards';

export const decPlacesCards = defineCards('dec-places', ['decimals', 'tenths', 'hundredths', 'thousandths'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'What are tenths, hundredths and thousandths?',
    back: 'Tenths: one whole cut into 10 equal parts (0.1). Hundredths: cut into 100 parts (0.01). Thousandths: cut into 1,000 parts (0.001).',
    memoryHook: 'Decimals are fractions with 10, 100 or 1,000 on the bottom.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'How are tenths, hundredths and thousandths related?',
    back: 'Each place is 1/10 of the place to its left. 10 thousandths = 1 hundredth, and 10 hundredths = 1 tenth.',
    example: '0.1 = 0.10 = 0.100',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'How do you rename tenths as hundredths?',
    back: 'Multiply the numerator and denominator by 10, or add a zero to the decimal.',
    example: '3/10 = 30/100, so 0.3 = 0.30',
    after: [2],
  },
  {
    n: 4, type: 'visual', difficulty: 1,
    front: 'This grid has 100 squares and 3 full columns of 10 are shaded. How many tenths and how many hundredths are shaded? Write it as a decimal.',
    back: '3 tenths = 30 hundredths = 0.3',
    explanation: 'Each column is one tenth (10 squares). Three columns is 3 tenths, or 30 of the 100 squares.',
    visual: { kind: 'shaded-grid', rows: 10, cols: 10, shaded: 30 },
    after: [2],
  },
  {
    n: 5, type: 'visual', difficulty: 2,
    front: 'This grid has 47 squares shaded. Write the decimal and say how many tenths and hundredths it is.',
    back: '0.47 — that is 4 tenths and 7 hundredths (or 47 hundredths).',
    visual: { kind: 'shaded-grid', rows: 10, cols: 10, shaded: 47 },
    after: [4],
  },
  {
    n: 6, type: 'solve', difficulty: 1,
    front: 'Write 7/10 as a decimal.',
    back: '0.7',
    after: [2],
    explanation: '7/10 is 7 tenths, which is written 0.7.',
  },
  {
    n: 7, type: 'solve', difficulty: 2,
    front: 'Write 23/100 as a decimal.',
    back: '0.23',
    after: [6],
    explanation: 'Hundredths means 2 decimal places: 23/100 = 0.23.',
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'Write 45/1,000 as a decimal.',
    back: '0.045',
    steps: ['Thousandths means 3 decimal places.', '45 needs a zero in front to fill 3 places: 0.045.'],
    after: [7],
  },
  {
    n: 9, type: 'solve', difficulty: 3,
    front: 'How many hundredths are in 0.6?',
    back: '60 hundredths',
    steps: ['0.6 = 0.60.', 'So there are 60 hundredths.'],
    after: [3],
  },
  {
    n: 10, type: 'solve', difficulty: 3,
    front: 'How many thousandths are in 0.25?',
    back: '250 thousandths',
    steps: ['0.25 = 0.250.', 'So there are 250 thousandths.'],
    after: [9],
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'True or False: 0.4 and 0.04 are the same, because both have a 4.',
    back: 'False. 0.4 is 4 tenths. 0.04 is 4 hundredths, which is 10 times smaller.',
    after: [2],
  },
  {
    n: 12, type: 'misconception', difficulty: 5,
    front: 'True or False: 1/100 is bigger than 1/10 because 100 is bigger than 10.',
    back: 'False. A bigger denominator means smaller pieces. 1/10 = 0.1 is greater than 1/100 = 0.01.',
    after: [2],
  },
  {
    n: 13, type: 'real-life', difficulty: 3,
    front: 'A dime is 1/10 of a dollar and a penny is 1/100 of a dollar. How many pennies equal 3 dimes, and how much is that in dollars?',
    back: '30 pennies, which is $0.30.',
    after: [9],
  },
  {
    n: 14, type: 'challenge', difficulty: 4,
    front: 'Write 3 tenths + 5 hundredths + 2 thousandths as a fraction with denominator 1,000 and as a decimal.',
    back: '352/1,000 = 0.352',
    steps: ['3 tenths = 300 thousandths.', '5 hundredths = 50 thousandths.', '300 + 50 + 2 = 352 thousandths.'],
    after: [10],
  },
  {
    n: 15, type: 'challenge', difficulty: 4,
    front: 'Which is greater: 6 tenths or 59 hundredths?',
    back: '6 tenths. 0.60 is greater than 0.59.',
    after: [9],
    steps: ['6 tenths = 0.60.', '59 hundredths = 0.59.', '0.60 > 0.59.'],
  },
]);
