import { defineCards } from '@/content/defineCards';

export const decRoundCards = defineCards('dec-round', ['decimals', 'rounding'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'Why do we round decimals?',
    back: 'To get an easier number, to estimate, or to match what you need — like rounding a price to the nearest cent.',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'What are the steps for rounding a decimal?',
    back: 'Underline the place you are rounding to. Look at the digit just to its right: 5 or more → round up; 4 or less → stay. Then drop the digits after your place.',
    memoryHook: 'Five or more, raise the score.',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'Which digit decides when rounding to the nearest whole number, tenth, or hundredth?',
    back: 'Whole number: look at the tenths digit. Tenth: look at the hundredths digit. Hundredth: look at the thousandths digit.',
    after: [2],
  },
  {
    n: 4, type: 'visual', difficulty: 1,
    front: 'Round 2.36 to the nearest tenth. Use the number line.',
    back: '2.4',
    explanation: '2.36 is past the halfway mark 2.35, so it is closer to 2.4.',
    visual: { kind: 'rounding-line', min: 2.3, max: 2.4, step: 0.1, value: 2.36, roundsTo: 2.4, showMidpoint: true },
    after: [2],
  },
  {
    n: 5, type: 'solve', difficulty: 1,
    front: 'Round 4.6 to the nearest whole number.',
    back: '5',
    steps: ['Look at the tenths digit: 6.', '6 is 5 or more → round up.'],
    after: [2],
  },
  {
    n: 6, type: 'solve', difficulty: 2,
    front: 'Round 7.382 to the nearest tenth.',
    back: '7.4',
    steps: ['Tenths digit is 3. Look at the hundredths digit: 8.', '8 → round up: 7.4.'],
    after: [3],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: 'Round 15.678 to the nearest hundredth.',
    back: '15.68',
    steps: ['Hundredths digit is 7. Look at the thousandths digit: 8.', '8 → round up: 15.68.'],
    after: [6],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'Round 3.049 to the nearest tenth.',
    back: '3.0',
    steps: ['Tenths digit is 0. Look at the hundredths digit: 4.', '4 → stay. Keep the 0: 3.0.'],
    after: [6],
  },
  {
    n: 9, type: 'solve', difficulty: 4,
    front: 'Round 9.995 to the nearest hundredth.',
    back: '10.00',
    steps: ['Hundredths digit is 9. Look at the thousandths digit: 5.', '5 → round up. 9 + 1 carries over: 9.99 + 0.01 = 10.00.'],
    after: [7],
  },
  {
    n: 10, type: 'misconception', difficulty: 5,
    front: 'True or False: 3.049 rounds to 3.1 to the nearest tenth because the 9 rounds up.',
    back: 'False. Only the digit right next to the tenths place counts: the hundredths digit, 4. So it rounds to 3.0.',
    commonMistake: 'Looking at a digit that is farther away.',
    after: [8],
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'True or False: 6.50 rounded to the nearest whole number is 6.',
    back: 'False. It is exactly halfway and halfway rounds up, so the answer is 7.',
    after: [5],
  },
  {
    n: 12, type: 'real-life', difficulty: 3,
    front: 'Estimate $4.89 + $2.15 + $6.05 by rounding each price to the nearest dollar. Then compare with the exact total.',
    back: 'Estimate: 5 + 2 + 6 = $13. Exact: $13.09 — very close.',
    after: [5],
  },
  {
    n: 13, type: 'real-life', difficulty: 3,
    front: 'A scale shows 2.468 kg. What is the weight to the nearest tenth of a kilogram?',
    back: '2.5 kg',
    steps: ['Tenths digit is 4. Look at the hundredths digit: 6.', '6 → round up: 2.5.'],
    after: [6],
  },
  {
    n: 14, type: 'challenge', difficulty: 4,
    front: 'A number rounds to 8.3 to the nearest tenth. What are the least and greatest numbers with two decimal places it could be?',
    back: 'Least 8.25, greatest 8.34.',
    steps: ['8.25 rounds up to 8.3.', '8.34 rounds down to 8.3.', '8.35 would round up to 8.4, and 8.24 would round down to 8.2.'],
    after: [7],
  },
  {
    n: 15, type: 'challenge', difficulty: 4,
    front: 'Round 4.5 and 4.49 to the nearest whole number. Why do the answers differ?',
    back: '4.5 → 5 and 4.49 → 4. The tenths digit is 5 in one (round up) and 4 in the other (stay).',
    after: [7],
    explanation: '4.5 has a 5 in the tenths place, so it rounds up. 4.49 has a 4 there, so it stays.',
  },
]);
