import { defineCards } from '@/content/defineCards';

export const fdFractionToDecimalCards = defineCards('fd-fraction-to-decimal', ['decimals', 'fractions', 'division'], [
  {
    n: 1, type: 'concept', difficulty: 1,
    front: 'How is a fraction turned into a decimal?',
    back: 'A fraction is a division: the numerator divided by the denominator.',
    example: '3/4 = 3 ÷ 4 = 0.75',
    memoryHook: 'The fraction bar means “divided by.”',
  },
  {
    n: 2, type: 'rule', difficulty: 2,
    front: 'How do you convert a fraction to a decimal by dividing?',
    back: 'Divide the numerator by the denominator. Write the numerator as a decimal with zeros (3 = 3.000) and keep dividing until it ends or you have enough places.',
    after: [1],
  },
  {
    n: 3, type: 'rule', difficulty: 2,
    front: 'Is there a shortcut when the denominator is 2, 4, 5, 10, 20, 25 or 50?',
    back: 'Yes. Rename the fraction with a denominator of 10, 100 or 1,000, then write it as a decimal.',
    example: '7/20 = 35/100 = 0.35',
    after: [2],
  },
  {
    n: 4, type: 'visual', difficulty: 2,
    front: 'The line is cut into tenths and the point is at 3/5. What decimal is that?',
    back: '0.6',
    explanation: '3/5 = 6/10, which is the 6th tenth mark: 0.6.',
    visual: {
      kind: 'number-line', min: 0, max: 1, partsPerWhole: 10,
      marks: [{ value: { numerator: 3, denominator: 5 }, label: '', position: 'above' }],
    },
    answerVisual: {
      kind: 'number-line', min: 0, max: 1, partsPerWhole: 10,
      marks: [{ value: { numerator: 3, denominator: 5 }, label: '0.6', position: 'above' }],
    },
    after: [3],
  },
  {
    n: 5, type: 'solve', difficulty: 1,
    front: 'Write 1/2 as a decimal by dividing.',
    back: '0.5',
    steps: ['1 ÷ 2 = 0.5.'],
    after: [2],
  },
  {
    n: 6, type: 'solve', difficulty: 2,
    front: 'Write 3/5 as a decimal.',
    back: '0.6',
    steps: ['Rename with tenths: 3/5 = 6/10.', '6/10 = 0.6.'],
    after: [3],
  },
  {
    n: 7, type: 'solve', difficulty: 3,
    front: 'Write 7/20 as a decimal.',
    back: '0.35',
    steps: ['Rename with hundredths: 7/20 = 35/100.', '35/100 = 0.35.'],
    after: [6],
  },
  {
    n: 8, type: 'solve', difficulty: 3,
    front: 'Write 3/8 as a decimal.',
    back: '0.375',
    steps: ['3 ÷ 8: 30 ÷ 8 = 3 R 6, 60 ÷ 8 = 7 R 4, 40 ÷ 8 = 5.', '0.375'],
    after: [2],
  },
  {
    n: 9, type: 'solve', difficulty: 3,
    front: 'Write 5/4 as a decimal.',
    back: '1.25',
    steps: ['5 ÷ 4 = 1 R 1.', '1 ÷ 4 = 0.25, so 1.25.'],
    after: [5],
  },
  {
    n: 10, type: 'solve', difficulty: 4,
    front: 'Write 1/3 as a decimal. Round to the nearest hundredth.',
    back: '0.333… which rounds to 0.33. The 3s repeat forever.',
    steps: ['1 ÷ 3: 10 ÷ 3 = 3 R 1 over and over.', 'Round: 0.33.'],
    after: [8],
  },
  {
    n: 11, type: 'misconception', difficulty: 5,
    front: 'Dev finds 3/4 by dividing 4 ÷ 3 and gets 1.33. What went wrong?',
    back: 'He divided the wrong way. Numerator ÷ denominator: 3 ÷ 4 = 0.75.',
    commonMistake: 'Dividing the denominator by the numerator.',
    after: [2],
  },
  {
    n: 12, type: 'misconception', difficulty: 5,
    front: 'True or False: 1/8 = 0.8.',
    back: 'False. 1/8 = 1 ÷ 8 = 0.125.',
    after: [8],
  },
  {
    n: 13, type: 'real-life', difficulty: 3,
    front: 'You ate 5/8 of a pizza. What decimal is that?',
    back: '0.625',
    steps: ['5 ÷ 8: 50 ÷ 8 = 6 R 2, 20 ÷ 8 = 2 R 4, 40 ÷ 8 = 5.', '0.625'],
    after: [8],
  },
  {
    n: 14, type: 'challenge', difficulty: 4,
    front: 'Which is greater: 5/8 or 0.6?',
    back: '5/8, because 5/8 = 0.625 and 0.625 > 0.6.',
    after: [10],
    steps: ['5/8 = 0.625.', '0.625 is greater than 0.600.'],
  },
  {
    n: 15, type: 'challenge', difficulty: 4,
    front: 'Write 2 3/4 as a decimal.',
    back: '2.75',
    steps: ['3/4 = 0.75.', 'Keep the whole number: 2.75.'],
    after: [9],
  },
]);
